In [24]:
from utils.utils import *

structures_path = "1.Minimal_structures/Minimal_structures"

Cif.path = structures_path
Cif.original_cifs_path = "/home/fnerin/Desktop/allodb_new/src/data" # <pdb>_updated.cif.gz

# Data

In [25]:
pocketsf = "3.Pockets/old_fpocket/pockets.pkl"

with open(pocketsf, "rb") as f:
    pockets = pickle.load(f)

pockets

,pdb,pocket,nres,site_in_pocket,pocket_in_site,label,Pocket Score,Drug Score,Number of alpha spheres,Mean alpha-sphere radius,...,Local hydrophobic density Score,Number of apolar alpha sphere,Proportion of apolar alpha sphere,Total SASA,Polar SASA,Apolar SASA,Proportion of polar atoms,Alpha sphere density,Cent. of mass - Alpha Sphere max dist,Flexibility
0,6ta3,pocket16,12,0.000000,0.0000,0,-0.0160,0.0145,79.0,3.4016,...,33.2273,44.0,0.5570,145.162,102.895,42.267,36.170,5.489,13.153,0.002
1,6ta3,pocket18,13,0.000000,0.0000,0,-0.0390,0.0001,48.0,3.5600,...,1.0000,2.0,0.0417,141.742,101.890,39.852,62.857,5.472,12.109,0.003
2,6ta3,pocket11,16,0.000000,0.0000,0,0.0606,0.0180,74.0,3.4367,...,26.6829,41.0,0.5541,116.997,36.739,80.258,41.304,5.183,12.464,0.395
3,6ta3,pocket15,11,0.000000,0.0000,0,-0.0097,0.0023,37.0,3.3932,...,12.5714,14.0,0.3784,97.871,30.244,67.627,42.857,4.211,10.405,0.407
4,6ta3,pocket7,42,0.000000,0.0000,0,0.2518,0.9883,244.0,3.5880,...,62.6740,181.0,0.7418,387.794,90.401,297.393,30.075,11.225,31.608,0.411
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8136,3d2p,pocket5,11,0.000000,0.0000,0,0.2167,0.0033,41.0,3.4642,...,13.8095,21.0,0.5122,74.790,31.316,43.475,36.364,5.179,9.584,0.281
8137,3d2p,pocket8,19,0.000000,0.0000,0,0.0886,0.0057,120.0,3.5617,...,8.9565,23.0,0.1917,205.618,101.049,104.569,45.588,6.886,19.284,0.417
8138,3d2p,pocket3,17,0.000000,0.0000,0,0.3030,0.0287,75.0,3.4781,...,16.0000,26.0,0.3467,116.634,42.969,73.665,44.681,6.894,15.728,0.509
8139,3d2p,pocket12,7,0.000000,0.0000,0,-0.0406,0.0007,36.0,3.6300,...,19.0000,20.0,0.5556,85.506,52.900,32.606,38.462,2.946,8.084,0.375
8140,3d2p,pocket6,16,0.043478,0.0625,0,0.1532,0.0075,92.0,3.5363,...,16.3448,29.0,0.3152,107.475,49.508,57.966,38.776,4.623,13.277,0.450

In [26]:
representatives = pockets.pdb.unique().tolist()

len(representatives), representatives

(293,
 ['6ta3',
  '5kwj',
  '6t4k',
  '5mo6',
  '3o0n',
  '1tjp',
  '4bqh',
  '1og0',
  '5jv1',
  '3auy',
  '5dl1',
  '1qqb',
  '6hgj',
  '4aau',
  '4cff',
  '7juv',
  '6nzf',
  '5uyy',
  '5xez',
  '2b08',
  '2c2b',
  '3i0s',
  '4dpq',
  '2d5x',
  '7amj',
  '2qmx',
  '3e5u',
  '4bo1',
  '6mo1',
  '2him',
  '5aa4',
  '5h08',
  '3kq7',
  '2qei',
  '8jii',
  '5y66',
  '6pgr',
  '2ha2',
  '5dzh',
  '7anw',
  '6e5g',
  '4pcu',
  '6bky',
  '6gfm',
  '4ejl',
  '5f2e',
  '6r4d',
  '7ehm',
  '6o0h',
  '4a79',
  '3dc2',
  '6ueg',
  '3kh5',
  '8hnn',
  '5ngz',
  '7mew',
  '5m1a',
  '3smq',
  '5hue',
  '4lrl',
  '5urj',
  '6huj',
  '1hkb',
  '2ldb',
  '2cdq',
  '5lvx',
  '2dz9',
  '6bvn',
  '1jlr',
  '5fii',
  '6sbv',
  '4bxc',
  '5ifu',
  '7ljc',
  '2jfz',
  '6o0n',
  '5swo',
  '6w6d',
  '4dn0',
  '6dhm',
  '5on7',
  '5hot',
  '3kjn',
  '6shq',
  '4coj',
  '6qjw',
  '5tkb',
  '5mro',
  '6i5g',
  '2bu6',
  '4zsk',
  '5x33',
  '5m0s',
  '6f7i',
  '6usa',
  '2vk1',
  '5kcv',
  '3f6g',
  '4avc',
  '3cmu',
  '5i73',
  '3c1n',
  '4ypl',
  '5oj0',
  '5f6y',
  '5htc',
  '6px5',
  '5nxd',
  '2o8e',
  '6cwy',
  '5c2o',
  '6uxy',
  '1i6k',
  '5wsb',
  '8v8c',
  '2ylq',
  '6zgv',
  '6tpk',
  '1ygc',
  '5we8',
  '6jta',
  '6qu3',
  '6c98',
  '1q43',
  '3x1m',
  '2zb2',
  '1msv',
  '3uvv',
  '5iv3',
  '6mc1',
  '5zwj',
  '5npk',
  '2p9g',
  '4n7j',
  '4b6e',
  '5v03',
  '6z89',
  '6li0',
  '5o2d',
  '8jr9',
  '8tb7',
  '4ofg',
  '5y8t',
  '7lz4',
  '6qxl',
  '7c7q',
  '6kun',
  '8jpf',
  '2zv2',
  '5kls',
  '6x83',
  '3eps',
  '4mi4',
  '3nqs',
  '4or2',
  '3zm9',
  '4gqq',
  '5kml',
  '6rrp',
  '6kkb',
  '5lrs',
  '4q9o',
  '2bty',
  '2fhy',
  '5l7i',
  '5kde',
  '3fud',
  '3wgg',
  '3cev',
  '3ho6',
  '7dtu',
  '5xzr',
  '6w2j',
  '2vvt',
  '7dpt',
  '3tho',
  '5wmv',
  '1bj4',
  '1vea',
  '5u7m',
  '5var',
  '4ov9',
  '5ogc',
  '4z07',
  '7q12',
  '6fba',
  '4ohf',
  '5xe9',
  '6vvd',
  '6ku3',
  '6iil',
  '5klq',
  '3d2e',
  '1zxm',
  '6yd5',
  '5f1u',
  '4w9n',
  '5w6y',
  '4nes',
  '3i59',
  '6eg3',
  '6boz',
  '1dku',
  '6d7o',
  '3uqd',
  '1egy',
  '4g9c',
  '6thc',
  '6swx',
  '5icn',
  '4c8b',
  '6wkn',
  '1tbf',
  '6pwh',
  '1ecb',
  '6qzh',
  '3edc',
  '6pf1',
  '3pjg',
  '6bbq',
  '7lw1',
  '1t5a',
  '6yuh',
  '4aqh',
  '5gug',
  '1kmp',
  '1rd4',
  '4kzt',
  '3zou',
  '5in4',
  '6hho',
  '6xp9',
  '6x9h',
  '5n9t',
  '1opl',
  '5i2c',
  '7d8x',
  '6qkw',
  '6yz4',
  '5f74',
  '6ms7',
  '2jfn',
  '4yb5',
  '5iov',
  '3dba',
  '6hv0',
  '5o1s',
  '6ui4',
  '6n3n',
  '6r02',
  '5ue4',
  '6jvu',
  '5j6f',
  '7fee',
  '5btr',
  '2i80',
  '5zma',
  '3mwb',
  '5jwc',
  '2q5o',
  '7p2l',
  '6np0',
  '4pa0',
  '2j0x',
  '5jjr',
  '3fzy',
  '6ruq',
  '3ath',
  '6s8g',
  '3kcc',
  '6izw',
  '8gti',
  '7aud',
  '6czm',
  '1i1q',
  '4tme',
  '6u1n',
  '4i7w',
  '5lwe',
  '3l76',
  '1ne7',
  '5ixe',
  '6iq4',
  '8dwg',
  '4rt7',
  '6rmd',
  '3mks',
  '3qh0',
  '4fha',
  '4zht',
  '8fe1',
  '4op0',
  '3d2p'])

In [27]:
sitesf = "1.Minimal_structures/sites.pkl"

with open(sitesf, "rb") as f:
    sites_reps = {k: v for k, v in pickle.load(f).items() if k in representatives} 

sites_reps

{'5c2o': {130: {'mod':   label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
   0           TTP             F               4            .                 ?

     auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
   0         704          TTP            A                  1              704

     pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
   0                       ?                      ?                      ?

     pdbx_sifts_xref_db_res
   0                      ?  ,
   'site':    label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
   0            ALA             A               1          106                 ?
   1            ALA             A               1          110                 ?
   2            ALA             A               1           75                 ?
   3            ALA             A               1           83                 ?
   4            ARG             A               1           55                 ?
   5            ASN             A               1          109                 ?
   6            ASN             A               1           79                 ?
   7            ASN             A               1           87                 ?
   8            ASP             A               1           84                 ?
   9            GLN             A               1          113                 ?
   10           GLY             A               1           77                 ?
   11           GLY             A               1           80                 ?
   12           GLY             A               1           81                 ?
   13           ILE             A               1           52                 ?
   14           THR             A               1           57                 ?
   15           THR             A               1           76                 ?
   16           THR             A               1           85                 ?
   17           TYR             A               1           78                 ?
   18           VAL             A               1          104                 ?
   19           VAL             A               1           82                 ?

      auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
   0           72          ALA            A                  1              106
   1           76          ALA            A                  1              110
   2           41          ALA            A                  1               75
   3           49          ALA            A                  1               83
   4           21          ARG            A                  1               55
   5           75          ASN            A                  1              109
   6           45          ASN            A                  1               79
   7           53          ASN            A                  1               87
   8           50          ASP            A                  1               84
   9           79          GLN            A                  1              113
   10          43          GLY            A                  1               77
   11          46          GLY            A                  1               80
   12          47          GLY            A                  1               81
   13          18          ILE            A                  1               52
   14          23          THR            A                  1               57
   15          42          THR            A                  1               76
   16          51          THR            A                  1               85
   17          44          TYR            A                  1               78
   18          70          VAL            A                  1              104
   19          48          VAL            A                  1               82

      pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
   0                      UNP                 Q8DSE5                     72
   1                      UNP                 Q8DSE5                     76
   2                      UNP                 Q8DSE5                     41
   3                      UNP                 Q8DSE5                     49
   4                      UNP                 Q8DSE5                     21
   5                      UNP                 Q8DSE5                     75
   6                      UNP                 Q8DSE5                     45
   7                      UNP                 Q8DSE5                     53
   8                      UNP                 Q8DSE5                     50
   9                      UNP                 Q8DSE5                     79
   10                     UNP                 Q8DSE5                     43
   11                     UNP                 Q8DSE5                     46
   12                     UNP                 Q8DSE5                     47
   13                     UNP                 Q8DSE5                     18
   14                     UNP                 Q8DSE5                     23
   15                     UNP                 Q8DSE5                     42
   16                     UNP                 Q8DSE5                     51
   17                     UNP                 Q8DSE5                     44
   18                     UNP                 Q8DSE5                     70
   19                     UNP                 Q8DSE5                     48

      pdbx_sifts_xref_db_res
   0                       A
   1                       A
   2                       A
   3                       A
   4                       R
   5                       N
   6                       N
   7                       N
   8                       D
   9                       Q
   10                      G
   11                      G
   12                      G
   13                      I
   14                      T
   15                      T
   16                      T
   17                      Y
   18                      V
   19                      V  ,
   'equivalent': []}},
 '5f1u': {131: {'mod':   label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
   0           3VN             E               2            .                 ?

     auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
   0         301          3VN            A                  1              301

     pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
   0                       ?                      ?                      ?

     pdbx_sifts_xref_db_res
   0                      ?  ,
   'site':    label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
   0            ALA             A               1           51                 ?
   1            ALA             A               1           84                 ?
   2            ALA             B               1           51                 ?
   3            ALA             B               1           84                 ?
   4            ASN             A               1           83                 ?
   5            ASN             B               1           83                 ?
   6            GLU             A               1           49                 ?
   7            GLU             A               1           87                 ?
   8            GLU             B               1           49                 ?
   9            GLU             B               1           87                 ?
   10           GLY             A               1           81                 ?
   11           GLY             B               1           81                 ?
   12           HIS             A               1           55                 ?
   13           HIS             A               1           58                 ?
   14           HIS             B               1           55                 ?
   15           HIS             B               1           58                 ?
   16           LEU             A               1           53                 ?
   17           LEU             A               1           91                 ?
   18           LEU             B               1           53                 ?
   19           LEU             B               1           91                 ?
   20           PHE             A               1          109                 ?
   21           PHE             B               1          109                 ?
   22           SER             A               1           50                 ?
   23           SER             A               1           82                 ?
   24           SER             B               1           50                 ?
   25           SER             B               1           82                 ?
   26           THR             A               1           52                 ?
   27           THR             A               1           54                 ?
   28           THR             B               1           52                 ?
   29           THR             B               1           54                 ?
   30           TYR             A               1          110                 ?
   31           TYR             B               1          110                 ?
   32           VAL             A               1           44                 ?
   33           VAL             B               1           44                 ?

      auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
   0           52          ALA            A                  1               51
   1           85          ALA            A                  1               84
   2           52          ALA            B                  1               51
   3           85          ALA            B                  1               84
   4           84          ASN            A                  1               83
   5           84          ASN            B                  1               83
   6           50          GLU            A                  1               49
   7           88          GLU            A                  1               87
   8           50          GLU            B                  1               49
   9           88          GLU            B                  1               87
   10          82          GLY            A                  1               81
   11          82          GLY            B                  1               81
   12          56          HIS            A                  1               55
   13          59          HIS            A                  1               58
   14          56          HIS            B                  1               55
   15          59          HIS            B                  1               58
   16          54          LEU            A                  1               53
   17          92          LEU            A                  1               91
   18          54          LEU            B                  1               53
   19          92          LEU            B                  1               91
   20         110          PHE            A                  1              109
   21         110          PHE            B                  1              109
   22          51          SER            A                  1               50
   23          83          SER            A                  1               82
   24          51          SER            B                  1               50
   25          83          SER            B                  1               82
   26          53          THR            A                  1               52
   27          55          THR            A                  1               54
   28          53          THR            B                  1               52
   29          55          THR            B                  1               54
   30         111          TYR            A                  1              110
   31         111          TYR            B                  1              110
   32          45          VAL            A                  1               44
   33          45          VAL            B                  1               44

      pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
   0                      UNP                 Q9PPB4                     52
   1                      UNP                 Q9PPB4                     85
   2                      UNP                 Q9PPB4                     52
   3                      UNP                 Q9PPB4                     85
   4                      UNP                 Q9PPB4                     84
   5                      UNP                 Q9PPB4                     84
   6                      UNP                 Q9PPB4                     50
   7                      UNP                 Q9PPB4                     88
   8                      UNP                 Q9PPB4                     50
   9                      UNP                 Q9PPB4                     88
   10                     UNP                 Q9PPB4                     82
   11                     UNP                 Q9PPB4                     82
   12                     UNP                 Q9PPB4                     56
   13                     UNP                 Q9PPB4                     59
   14                     UNP                 Q9PPB4                     56
   15                     UNP                 Q9PPB4                     59
   16                     UNP                 Q9PPB4                     54
   17                     UNP                 Q9PPB4                     92
   18                     UNP                 Q9PPB4                     54
   19                     UNP                 Q9PPB4                     92
   20                     UNP                 Q9PPB4                    110
   21                     UNP                 Q9PPB4                    110
   22                     UNP                 Q9PPB4                     51
   23                     UNP                 Q9PPB4                     83
   24                     UNP                 Q9PPB4                     51
   25                     UNP                 Q9PPB4                     83
   26                     UNP                 Q9PPB4                     53
   27                     UNP                 Q9PPB4                     55
   28                     UNP                 Q9PPB4                     53
   29                     UNP                 Q9PPB4                     55
   30                     UNP                 Q9PPB4                    111
   31                     UNP                 Q9PPB4                    111
   32                     UNP                 Q9PPB4                     45
   33                     UNP                 Q9PPB4                     45

      pdbx_sifts_xref_db_res
   0                       A
   1                       A
   2                       A
   3                       A
   4                       N
   5                       N
   6                       E
   7                       E
   8                       E
   9                       E
   10                      G
   11                      G
   12                      H
   13                      H
   14                      H
   15                      H
   16                      L
   17                      L
   18                      L
   19                      L
   20                      Y
   21                      Y
   22                      S
   23                      S
   24                      S
   25                      S
   26                      T
   27                      T
   28                      T
   29                      T
   30                      Y
   31                      Y
   32                      V
   33                      V  ,
   'equivalent': []}},
 '7q12': {176: {'mod':   label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
   0           G6P             I               3            .                 ?

     auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
   0         801          G6P            A                  1              801

     pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
   0                       ?                      ?                      ?

     pdbx_sifts_xref_db_res
   0                      ?  ,
   'site':    label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
   0            ALA             A               1          298                 ?
   1            ALA             G               1          289                 ?
   2            ARG             A               1          579                 ?
   3            ARG             A               1          582                 ?
   4            ARG             A               1          586                 ?
   5            ASN             A               1          295                 ?
   6            ASN             G               1          295                 ?
   7            GLN             A               1          294                 ?
   8            GLN             A               1          299                 ?
   9            GLU             G               1          292                 ?
   10           HIS             A               1          297                 ?
   11           HIS             A               1          501                 ?
   12           HIS             G               1          291                 ?
   13           ILE             A               1          583                 ?
   14           LYS             A               1          301                 ?
   15           SER             A               1          578                 ?
   16           SER             G               1          288                 ?
   17           THR             A               1          323                 ?

      auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
   0          298          ALA            A                  1              298
   1          289          ALA            C                  1              289
   2          579          ARG            A                  1              579
   3          582          ARG            A                  1              582
   4          586          ARG            A                  1              586
   5          295          ASN            A                  1              295
   6          295          ASN            C                  1              295
   7          294          GLN            A                  1              294
   8          299          GLN            A                  1              299
   9          292          GLU            C                  1              292
   10         297          HIS            A                  1              297
   11         501          HIS            A                  1              501
   12         291          HIS            C                  1              291
   13         583          ILE            A                  1              583
   14         301          LYS            A                  1              301
   15         578          SER            A                  1              578
   16         288          SER            C                  1              288
   17         323          THR            A                  1              323

      pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
   0                      UNP                 P13807                    298
   1                      UNP                 P13807                    289

# Features

In [5]:
features_path = "4.Features"
os.makedirs(f"{features_path}", exist_ok=True)

os.makedirs(f"{features_path}/features", exist_ok=True)

In [7]:
from utils.features_classes import * # Each FClass

BiopythonF.dssp_path = "utils/external/mkdssp-4.4.0-linux-x64"
HHBlitsF.uniref_path = "/data/fnerin/UniRef30_2023_02/UniRef30_2023_02"

┌──────────────────────────────────────────────────────────────────────────────┐
│                                 PyRosetta-4                                  │
│              Created in JHU by Sergey Lyskov and PyRosetta Team              │
│              (C) Copyright Rosetta Commons Member Institutions               │
│                                                                              │
│ NOTE: USE OF PyRosetta FOR COMMERCIAL PURPOSES REQUIRE PURCHASE OF A LICENSE │
│         See LICENSE.PyRosetta.md or email license@uw.edu for details         │
└──────────────────────────────────────────────────────────────────────────────┘
PyRosetta-4 2024 [Rosetta PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release 2024.42+release.3366cf78a3df04339d1982e94531b77b098ddb99 2024-10-11T08:24:04] retrieved from: http://www.pyrosetta.org
core.init: Checking for fconfig files in pwd and ./rosetta/flags
core.init: Rosetta version: PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release r388 2024.42+release.3366cf78a3 3366cf78a3df04339d1982e94531b77b098ddb99 http://www.pyrosetta.org 2024-10-11T08:24:04
core.init: Rosetta extras: [cxx11thread, serialization]
core.init: command: PyRosetta -mute core.pack basic core.scoring -ignore_zero_occupancy false -database /home/fnerin/miniconda3/envs/pybiomed/lib/python3.11/site-packages/pyrosetta/database

In [8]:
from utils.features_utils import calculate_features, get_pdb_features, res_cols

In [9]:
FClasses

[utils.features_classes.GrapheinF,
 utils.features_classes.FreeSASAF,
 utils.features_classes.DSSPF,
 utils.features_classes.MelodiaF,
 utils.features_classes.BiopythonF,
 utils.features_classes.PyRosettaF,
 utils.features_classes.ProDyF,
 utils.features_classes.TransferEntropyF,
 utils.features_classes.HHBlitsF]

# Calculation

## Synchronous

**Example**

In [33]:
pdb = "1r1v"

for fc in FClasses:
    pdbpath = f"{features_path}/features/{pdb}"
    file = f"{pdbpath}/{fc.__name__}.pkl"
    if not os.path.isfile(file):
        os.makedirs(pdbpath, exist_ok=True)
        calculated = calculate_features(pdb, fc, file, structures_path, original_cifs_path)
        if calculated is False:
            with open(f"{features_path}/calculation_errors.txt", "a") as f:
                f.write(f"{pdb}\t{fc}\n")

Output()

2025-01-23 12:43:23,601 - .prody - WARNING - WARNING Could not find _atom_site_anisotrop in lines.
2025-01-23 12:43:23,601 - .prody - WARNING - WARNING No anisotropic B factors found
2025-01-23 12:43:23,601 - .prody - DEBUG - 755 atoms and 1 coordinate set(s) were parsed in 0.01s.
2025-01-23 12:43:23,611 - .prody - DEBUG - Hessian was built in 0.01s.
2025-01-23 12:43:23,644 - .prody - DEBUG - 279 modes were calculated in 0.03s.
2025-01-23 12:43:23,659 - .prody - INFO - Calculating stiffness matrix.
2025-01-23 12:43:23,663 - .prody - DEBUG - Stiffness matrix calculated in 0.01s.
2025-01-23 12:43:23,663 - .prody - INFO - The range of effective force constant is: 1.9107205147631081 to 19.667074477427267.
2025-01-23 12:43:23,666 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,667 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,671 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,672 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,674 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,675 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,677 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,678 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,681 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,682 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,684 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,685 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,688 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,689 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,691 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,692 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,695 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,695 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,700 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,701 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,704 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,704 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,707 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,708 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,710 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,711 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,713 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,714 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,715 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,716 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,718 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,718 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,720 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,721 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,723 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,723 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,725 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,726 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,728 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,728 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,730 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,731 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,733 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,734 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,736 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,736 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,738 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,739 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,741 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,742 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,744 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,744 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,746 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,747 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,749 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,749 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,751 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,752 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,753 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,754 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,756 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,757 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,758 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,759 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,761 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,762 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,763 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,764 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,766 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,767 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,768 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,769 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,771 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,772 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,774 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,775 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,776 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,777 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,779 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,780 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,781 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,782 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,784 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,785 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,786 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,787 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,789 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,790 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,792 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,792 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,794 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,795 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,797 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,798 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,799 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,800 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,802 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,803 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,805 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,805 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,807 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,808 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,810 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,810 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,812 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,813 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,815 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,815 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,817 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,818 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,820 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,821 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,822 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,823 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,825 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,826 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,827 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,828 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,830 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,831 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,833 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,834 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,836 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,836 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,838 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,839 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,841 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,841 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,843 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,844 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,846 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,846 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,848 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,849 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,851 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,851 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,853 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,854 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,856 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,856 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,858 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,859 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,861 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,861 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,864 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,864 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,866 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,867 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,869 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,869 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,871 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,872 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,874 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,874 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,876 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,877 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,879 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,880 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,882 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,882 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,884 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,885 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,887 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,887 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,889 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,890 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,892 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,893 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,895 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,895 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,897 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,898 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,900 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,900 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,902 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,903 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,905 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,905 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,907 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,908 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,910 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,910 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,912 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,913 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,915 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,915 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,917 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,918 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,920 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,920 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,922 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 12:43:23,923 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 12:43:23,925 - .prody - DEBUG - 10 modes across 96 modesets were matched in 0.00s.

core.chemical.GlobalResidueTypeSet: Finished initializing fa_standard residue type set.  Created 985 residue types
core.chemical.GlobalResidueTypeSet: Total time to initialize 0.318451 seconds.
core.import_pose.import_pose: File '1.Minimal_structures/Minimal_structures/1r1v.cif' automatically determined to be of type mmCIF
core.conformation.Conformation: [ WARNING ] missing heavyatom:  OXT on residue GLU:CtermProteinFull 95

In [34]:
with open(f"{features_path}/errors.pkl", "wb") as f:
    pickle.dump(errors, f)

## Asynchronous

Features are calculated with the scripts on `utils/features_scripts`:
- TransferEntropy must be calculated with special memory handling.
- HHBlits must be calculated with reduced parallelization.
- ProDy is already parallel so it's calculated synchronously.
- The rest are parallelized normally.

<br>

**Example**

In [9]:
from concurrent.futures import ProcessPoolExecutor, as_completed

In [96]:
with ProcessPoolExecutor(max_workers=30) as executor:
    futures = {}
    
    for pdb in representatives[:2]:
        print(pdb)
        pdbpath = f"{features_path}/features/{pdb}"
        
        for fc in FClasses:
            file = f"{pdbpath}/{fc.__name__}.pkl"
            if not os.path.isfile(file):
                os.makedirs(pdbpath, exist_ok=True)
                future = executor.submit(calculate_features, pdb, fc, file, structures_path, original_cifs_path)
                futures[future] = [pdb, fc.__name__]
            
    for future in tqdm(as_completed(futures), total=len(futures), smoothing=0):
        pdb, fc = futures[future]
        try:
            calculated = future.result()
            if calculated is False:
                with open(f"{features_path}/calculation_errors.txt", "a") as f:
                    f.write(f"{pdb}\t{fc}\n")
        except:
            with open(f"{features_path}/errors.txt", "a") as f:
                f.write(f"{pdb}\t{fc}\n")

6ta3
5kwj

  0%|          | 0/9 [00:00<?, ?it/s]

2025-01-23 13:20:59,374 - .prody - WARNING - WARNING Could not find _atom_site_anisotrop in lines.
2025-01-23 13:20:59,375 - .prody - WARNING - WARNING No anisotropic B factors found
2025-01-23 13:20:59,376 - .prody - DEBUG - 2203 atoms and 1 coordinate set(s) were parsed in 0.02s.
2025-01-23 13:20:59,420 - .prody - DEBUG - Hessian was built in 0.04s.
2025-01-23 13:21:00,729 - .prody - DEBUG - 843 modes were calculated in 1.31s.
2025-01-23 13:21:00,791 - .prody - INFO - Calculating stiffness matrix.
2025-01-23 13:21:00,895 - .prody - DEBUG - Stiffness matrix calculated in 0.10s.
2025-01-23 13:21:00,897 - .prody - INFO - The range of effective force constant is: 8.907462350410235 to 27.904975154330124.
2025-01-23 13:21:00,907 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:00,916 - .prody - DEBUG - 10 modes were calculated in 0.01s.
2025-01-23 13:21:00,934 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:00,941 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:00,951 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:00,957 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:00,963 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:00,967 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:00,974 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:00,977 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:00,987 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 13:21:00,990 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:00,997 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 13:21:01,002 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,008 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,011 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,021 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,026 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,032 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 13:21:01,036 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,043 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 13:21:01,046 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,053 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,057 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,064 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 13:21:01,071 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,078 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 13:21:01,085 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,092 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,096 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,102 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 13:21:01,109 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,119 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,122 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,131 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 13:21:01,138 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,144 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 13:21:01,147 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,154 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 13:21:01,160 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,170 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 13:21:01,173 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,180 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,183 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,193 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,197 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,204 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,207 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,214 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,218 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,225 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 13:21:01,228 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,239 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,246 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,257 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,261 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,268 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,272 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,279 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 13:21:01,282 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,288 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 13:21:01,292 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,298 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 13:21:01,302 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,309 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,316 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,326 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,330 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,337 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,341 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,348 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,352 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,362 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,366 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,375 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,379 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,386 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,390 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,397 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,400 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,411 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,418 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,427 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,431 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,437 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,444 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,451 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 13:21:01,456 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,475 - .prody - DEBUG - Kirchhoff was built in 0.02s.
2025-01-23 13:21:01,482 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,492 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,495 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,506 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,510 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,518 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,521 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,528 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,535 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,545 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,549 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,557 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,561 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,569 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,572 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,579 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,583 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,591 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,595 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,602 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,605 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,612 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,618 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,626 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,629 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,637 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,641 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,648 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,652 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,659 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,663 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,670 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,674 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,681 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,684 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,691 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,695 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,703 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,707 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,714 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,717 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,725 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,729 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,736 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,739 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,746 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,749 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,756 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,760 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,767 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,771 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,778 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,782 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,789 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,792 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,799 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 13:21:01,803 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,809 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 13:21:01,813 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,821 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,824 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,831 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,836 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,843 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,847 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,854 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,857 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,866 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,870 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,876 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,880 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,887 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,891 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,898 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,902 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,909 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,914 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,921 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,925 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,931 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,935 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,941 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,945 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,952 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,956 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,963 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,967 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,974 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,978 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,985 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 13:21:01,989 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:01,995 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:01,999 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:02,006 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:02,010 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:02,017 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:02,021 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:02,028 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:02,032 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:02,039 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:02,043 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:02,050 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:02,053 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:02,061 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:02,065 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:02,072 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:02,076 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:02,083 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:02,087 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:02,096 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:02,100 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:02,108 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:02,111 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:02,118 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:02,121 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:02,128 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:02,132 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:02,138 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:02,142 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:02,149 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:02,152 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:02,159 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:02,163 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:02,169 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:02,173 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:02,180 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:02,183 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:02,189 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 13:21:02,193 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:02,200 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 13:21:02,203 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:02,210 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 13:21:02,213 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:02,220 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:02,223 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:02,230 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:02,234 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:02,241 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 13:21:02,244 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:02,250 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 13:21:02,254 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:02,260 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 13:21:02,263 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:02,270 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:02,274 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:02,281 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:02,285 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:02,291 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:02,295 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:02,301 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:02,305 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:02,311 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-01-23 13:21:02,314 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:02,321 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:02,325 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:02,332 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:02,336 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:02,342 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:02,346 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:02,354 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:02,358 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:02,365 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:02,368 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:02,375 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-01-23 13:21:02,378 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-01-23 13:21:02,385 - .prody - DEBUG - Kirchhoff was built in 0.00s.

#### Run

In [15]:
import subprocess

In [16]:
subprocess.run("""
cd 4.Features &&
python features.py > features_completion.log 2>&1 &&
python transferentropy_features.py > transferentropy_completion.log 2>&1 &&
python prody_features.py > prody_completion.log 2>&1 &&
python hhblits_features.py > hhblits_completion.log 2>&1
""", shell=True)

CompletedProcess(args='\ncd 4.Features &&\npython features.py > features_completion.log 2>&1 &&\npython transferentropy_features.py > transferentropy_completion.log 2>&1 &&\npython prody_features.py > prody_completion.log 2>&1 &&\npython hhblits_features.py > hhblits_completion.log 2>&1\n', returncode=0)

# Errors

In [24]:
# PDBs and feature classes from feature_classes that appear in an error file in the feature calculation folder
errors = pd.concat((
    pd.read_csv(f"{features_path}/{f}", sep="\t", header=None) 
    for f in os.listdir(features_path)
        if f.endswith("errors.txt")
)).sort_values(0)

errors

      0           1
3  4cff    MelodiaF
2  4pa0    MelodiaF
0  5kml    MelodiaF
1  5kml   FreeSASAF
4  5kml  PyRosettaF
5  6tpk   GrapheinF
6  6tpk   FreeSASAF
7  6tpk  PyRosettaF

In [25]:
errors_pdbs = errors[0].unique().tolist()
len(errors_pdbs), errors_pdbs

(4, ['4cff', '4pa0', '5kml', '6tpk'])

In [26]:
# PDBs that don't have an error but have a missing .pkl file of a feature class
missing = []

for pdb in representatives:
    if pdb not in errors_pdbs:
        files = tuple(f for f in os.listdir(f"{features_path}/features/{pdb}") if f.endswith(".pkl"))
        miss = tuple(fc.__name__ for fc in FClasses if f"{fc.__name__}.pkl" not in files)
        if len(miss):
            missing.append((pdb, miss))

missing

[]

In [27]:
errorsf = f"{features_path}/errors.pkl"

with open(errorsf, "wb") as f:
    pickle.dump(errors_pdbs, f)

# Processing

In [16]:
# Generate and save dictionary of a DataFrame of all the residues, labels, and features of each PDB
featuresf = f"{features_path}/features.pkl"

if not os.path.isfile(featuresf):
    featuresd = {}
    for pdb in tqdm(representatives, smoothing=0):
        if pdb not in errors_pdbs:
            feats = get_pdb_features(
                Cif(pdb),
                sites = [
                    sd["site"][res_cols]
                    for sid, site in sites_reps[pdb].items()
                    for sd in site["equivalent"] + [{"site": site["site"]},]
                ],
                features_path = features_path
            )
            featuresd[pdb] = pd.concat(
                (
                    pd.DataFrame([pdb]*len(feats), columns=pd.MultiIndex.from_tuples([("Residues", "pdb")])),
                    feats
                ),
                axis=1
            )
    with open(featuresf, "wb") as f:
        pickle.dump(featuresd, f)
else:
    with open(featuresf, "rb") as f:
        featuresd = pickle.load(f)

len(featuresd), featuresd

(289,
 {'6ta3':     Residues                                                          \
           pdb label_entity_id label_asym_id label_seq_id auth_asym_id
  0       6ta3               2             B            1            A
  1       6ta3               2             B            2            A
  2       6ta3               2             B            3            A
  3       6ta3               2             B            4            A
  4       6ta3               2             B            5            A
  ..       ...             ...           ...          ...          ...
  767     6ta3               3             C          387            K
  768     6ta3               3             C          388            K
  769     6ta3               3             C          389            K
  770     6ta3               3             C          390            K
  771     6ta3               3             C          391            K

                                    Label     Amino acids                  ...  \
      auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
  0             1                 ?     0               0               0  ...
  1             2                 ?     0               0               0  ...
  2             3                 ?     0               0               0  ...
  3             4                 ?     0               0               1  ...
  4             5                 ?     0               0               0  ...
  ..          ...               ...   ...             ...             ...  ...
  767         365                 ?     0               0               0  ...
  768         366                 ?     0               0               0  ...
  769         367                 ?     0               0               0  ...
  770         368                 ?     0               0               0  ...
  771         369                 ?     0               0               0  ...

        HHBlits                                                                 \
           M->M      M->I M->D      I->M      I->I      D->M      D->D    Neff
  0    0.998615  0.001223  0.0  1.000000  0.000000  0.000000  0.000000   9.088
  1    1.000000  0.000000  0.0  0.000000  0.000000  0.000000  0.000000   9.860
  2    0.997923  0.001963  0.0  0.656106  0.343885  0.000000  0.000000   9.988
  3    0.999307  0.000605  0.0  0.333325  0.666649  0.000000  0.000000  10.047
  4    1.000000  0.000000  0.0  0.000000  0.000000  0.000000  0.000000  10.026
  ..        ...       ...  ...       ...       ...       ...       ...     ...
  767  0.997923  0.002280  0.0  0.333325  0.666649  0.214641  0.785128   9.373
  768  0.986233  0.013602  0.0  0.050907  0.949342  0.632440  0.367547   9.351
  769  0.994470  0.005691  0.0  0.500000  0.500000  1.000000  0.000000   8.953
  770  1.000000  0.000000  0.0  0.000000  0.000000  0.000000  0.000000   8.749
  771  1.000000  0.000000  0.0  1.000000  0.000000  0.000000  0.000000   7.869


      Neff_I Neff_D
  0    1.005  0.000
  1    0.000  0.000
  2    1.007  0.000
  3    1.000  0.000
  4    0.000  0.000
  ..     ...    ...
  767  1.020  1.034
  768  1.032  1.025
  769  1.000  1.002
  770  0.000  0.000
  771  0.000  0.000

  [772 rows x 174 columns],
  '5kwj':     Residues                                                          \
           pdb label_entity_id label_asym_id label_seq_id auth_asym_id
  0       5kwj               1             B            1            B
  1       5kwj               1             B            2            B
  2       5kwj               1             B            3            B
  3       5kwj               1             B            4            B
  4       5kwj               1             B            5            B
  ..       ...             ...           ...          ...          ...
  278     5kwj               1             B          279            B
  279     5kwj               1             B          280            B
  280     5kwj               1             B          281            B
  281     5kwj               1             B          282            B
  282     5kwj               1             B          283            B

                                    Label     Amino acids                  ...  \
      auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
  0             0                 ?     0               0               0  ...
  1             1                 ?     0               0               0  ...
  2             2                 ?     0               0               0  ...
  3             3                 ?     0               0               0  ...
  4             4                 ?     0               0               0  ...
  ..          ...               ...   ...             ...             ...  ...
  278         278                 ?     0               0               0  ...
  279         279                 ?     0               0               0  ...
  280         280                 ?     0               0               0  ...
  281         281                 ?     0               0               0  ...
  282         282                 ?     0               0               0  ...

        HHBlits                                                              \
           M->M      M->I      M->D      I->M      I->I      D->M      D->D
  0    0.985549  0.000000  0.014548  0.000000  0.000000  0.000000  0.000000
  1    1.000000  0.000000  0.000000  0.000000  0.000000  1.000000  0.000000
  2    0.988286  0.011817  0.000000  1.000000  0.000000  0.000000  0.000000
  3    0.995850  0.004370  0.000000  0.500000  0.500000  0.000000  0.000000
  4    1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
  ..        ...       ...       ...       ...       ...       ...       ...
  278  0.994470  0.003657  0.002066  0.238490  0.761544  1.000000  0.000000
  279  0.994470  0.002472  0.002799  0.227510  0.772711  0.590496  0.409235
  280  0.991030  0.007933  0.001198  0.046071  0.953960  0.301034  0.698823
  281  0.991030  0.008777  0.000000  0.556711  0.443191  0.676424  0.323761
  282  0.990343  0.009578  0.000000  0.170282  0.829895  0.000000  1.000000


         Neff Neff_I Neff_D
  0    10.217  0.000  0.000
  1    11.268  0.000  1.005
  2    11.773  1.031  0.000
  3    11.926  1.004  0.000
  4    12.055  0.000  0.000
  ..      ...    ...    ...
  278  13.059  1.056  1.005
  279  13.017  1.032  1.019
  280  12.905  1.109  1.035
  281  12.822  1.129  1.037
  282  12.793  1.101  1.000

  [283 rows x 174 columns],
  '6t4k':     Residues                                                          \
           pdb label_entity_id label_asym_id label_seq_id auth_asym_id
  0       6t4k               1             A           23            A
  1       6t4k               1             A           24            A
  2       6t4k               1             A           25            A
  3       6t4k               1             A           26            A
  4       6t4k               1             A           27            A
  ..       ...             ...           ...          ...          ...
  235     6t4k               1             A          259            A
  236     6t4k               1             A          260            A
  237     6t4k               1             A          261            A
  238     6t4k               1             A          262            A
  239     6t4k               1             A          263            A

                                    Label     Amino acids                  ...  \
      auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
  0           267                 ?     0               0               0  ...
  1           268                 ?     0               0               0  ...
  2           269                 ?     0               0               0  ...
  3           270                 ?     0               0               0  ...
  4           271                 ?     0               0               0  ...
  ..          ...               ...   ...             ...             ...  ...
  235         503                 ?     0               0               0  ...
  236         504                 ?     0               0               0  ...
  237         505                 ?     0               0               0  ...
  238         506                 ?     0               0               0  ...
  239         507                 ?     0               0               0  ...

        HHBlits                                                              \
           M->M      M->I      M->D      I->M      I->I      D->M      D->D
  0    0.997231  0.000000  0.002514  0.000000  0.000000  0.871154  0.129050
  1    1.000000  0.000000  0.000000  0.000000  0.000000  0.454389  0.545632
  2    0.984866  0.009645  0.005479  0.381565  0.618566  0.000000  1.000000
  3    0.946714  0.030863  0.022655  0.078183  0.922103  0.574349  0.425727
  4    0.967276  0.030206  0.002648  1.000000  0.000000  0.601235  0.398596
  ..        ...       ...       ...       ...       ...       ...       ...
  235  1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
  236  0.993781  0.004914  0.001625  0.500000  0.500000  0.000000  0.000000
  237  0.998615  0.001070  0.000000  0.166662  0.833353  1.000000  0.000000
  238  0.997231  0.002650  0.000000  0.500000  0.500000  0.000000  0.000000
  239  1.000000  0.000000  0.000000  1.000000  0.000000  0.000000  0.000000


         Neff Neff_I Neff_D
  0    10.990  0.000  1.095
  1    10.962  0.000  1.018
  2    10.953  1.098  1.004
  3    10.921  1.242  1.048
  4    10.943  1.230  1.204
  ..      ...    ...    ...
  235  11.084  0.000  0.000
  236  11.080  1.028  0.000
  237  11.058  1.001  1.001
  238  11.033  1.000  0.000
  239  10.362  0.000  0.000

  [240 rows x 174 columns],
  '5mo6':     Residues                                                          \
           pdb label_entity_id label_asym_id label_seq_id auth_asym_id
  0       5mo6               1             B           26            A
  1       5mo6               1             B           27            A
  2       5mo6               1             B           28            A
  3       5mo6               1             B           29            A
  4       5mo6               1             B           30            A
  ..       ...             ...           ...          ...          ...
  320     5mo6               1             B          346            A
  321     5mo6               1             B          347            A
  322     5mo6               1             B          348            A
  323     5mo6               1             B          349            A
  324     5mo6               1             B          350            A

                                    Label     Amino acids                  ...  \
      auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
  0             3                 ?     0               0               0  ...
  1             4                 ?     0               0               0  ...
  2             5                 ?     0               0               0  ...
  3             6                 ?     0               0               0  ...
  4             7                 ?     0               0               0  ...
  ..          ...               ...   ...             ...             ...  ...
  320         323                 ?     0               0               0  ...
  321         324                 ?     0               0               0  ...
  322         325                 ?     0               0               0  ...
  323         326                 ?     0               0               0  ...
  324         327                 ?     0               0               0  ...

        HHBlits                                                              \
           M->M      M->I      M->D      I->M      I->I      D->M      D->D
  0    0.953960  0.038261  0.007960  0.366783  0.633317  0.351355  0.648420
  1    0.965267  0.010273  0.024332  0.248273  0.751581  0.100342  0.899378
  2    0.961927  0.026812  0.011502  0.187115  0.812816  0.431371  0.568803
  3    0.959264  0.011018  0.029523  0.571965  0.428094  0.319082  0.680657
  4    0.958599  0.009420  0.032106  0.231808  0.768438  0.363745  0.636397
  ..        ...       ...       ...       ...       ...       ...       ...
  320  1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
  321  0.995160  0.004951  0.000000  0.055553  0.944747  0.000000  0.000000
  322  0.991717  0.008591  0.000000  0.150726  0.849096  0.000000  0.000000
  323  0.992404  0.007573  0.000000  0.099995  0.900002  0.000000  0.000000
  324  1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000


         Neff Neff_I Neff_D
  0     9.635  1.202  1.247
  1     9.375  1.057  1.195
  2     9.430  1.129  1.315
  3     9.466  1.040  1.231
  4     9.465  1.028  1.307
  ..      ...    ...    ...
  320  10.818  0.000  0.000
  321  10.608  1.005  0.000
  322  10.338  1.027  0.000
  323  10.237  1.005  0.000
  324   9.822  0.000  0.000

  [325 rows x 174 columns],
  '3o0n':      Residues                                                          \
            pdb label_entity_id label_asym_id label_seq_id auth_asym_id
  0        3o0n               1             A            1            A
  1        3o0n               1             A            2            A
  2        3o0n               1             A            3            A
  3        3o0n               1             A            4            A
  4        3o0n               1             A            5            A
  ...       ...             ...           ...          ...          ...
  1213     3o0n               1             B          629            B
  1214     3o0n               1             B          630            B
  1215     3o0n               1             B          631            B
  1216     3o0n               1             B          632            B
  1217     3o0n               1             B          633            B

                                     Label     Amino acids                  ...  \
       auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
  0              1                 ?     0               0               0  ...
  1              2                 ?     0               0               0  ...
  2              3                 ?     0               0               0  ...
  3              4                 ?     0               0               0  ...
  4              5                 ?     0               0               0  ...
  ...          ...               ...   ...             ...             ...  ...
  1213         629                 ?     0               0               0  ...
  1214         630                 ?     0               0               0  ...
  1215         631                 ?     0               0               0  ...
  1216         632                 ?     0               0               0  ...
  1217         633                 ?     0               0               0  ...

         HHBlits                                                           \
            M->M      M->I      M->D      I->M      I->I D->M D->D   Neff
  0     1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0  4.807
  1     1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0  7.169
  2     1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0  7.734
  3     0.990343  0.009848  0.000000  1.000000  0.000000  0.0  0.0  7.969
  4     1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0  8.215
  ...        ...       ...       ...       ...       ...  ...  ...    ...
  1213  0.996540  0.002648  0.000772  0.590496  0.409235  0.0  0.0  8.514
  1214  0.997923  0.000727  0.001034  0.250000  0.750019  0.0  1.0  8.459
  1215  1.000000  0.000000  0.000000  0.000000  0.000000  1.0  0.0  8.360
  1216  0.978742  0.019424  0.002040  0.886996  0.112734  0.0  0.0  8.307
  1217  0.978063  0.005097  0.016828  0.436786  0.562919  1.0  0.0  8.011


       Neff_I Neff_D
  0     0.000  0.000
  1     0.000  0.000
  2     0.000  0.000
  3     1.000  0.000
  4     0.000  0.000
  ...     ...    ...
  1213  1.010  0.000
  1214  1.000  1.000
  1215  0.000  1.004
  1216  1.108  0.000
  1217  1.018  1.002

  [1218 rows x 174 columns],
  '1tjp':     Residues                                                          \
           pdb label_entity_id label_asym_id label_seq_id auth_asym_id
  0       1tjp               1             A            1            A
  1       1tjp               1             A            2            A
  2       1tjp               1             A            3            A
  3       1tjp               1             A            4            A
  4       1tjp               1             A            5            A
  ..       ...             ...           ...          ...          ...
  262     1tjp               1             A          263            A
  263     1tjp               1             A          264            A
  264     1tjp               1             A          265            A
  265     1tjp               1             A          266            A
  266     1tjp               1             A          267            A

                                    Label     Amino acids                  ...  \
      auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
  0             1                 ?     0               0               0  ...
  1             2                 ?     0               0               0  ...
  2             3                 ?     0               0               0  ...
  3             4                 ?     0               0               0  ...
  4             5                 ?     0               0               0  ...
  ..          ...               ...   ...             ...             ...  ...
  262         263                 ?     0               0               0  ...
  263         264                 ?     0               1               0  ...
  264         265                 ?     0               1               0  ...
  265         266                 ?     0               0               0  ...
  266         267                 ?     0               0               0  ...

        HHBlits                                                            \
           M->M      M->I      M->D      I->M      I->I D->M D->D    Neff
  0    0.991030  0.004083  0.004591  1.000000  0.000000  0.0  0.0  11.247
  1    0.988971  0.011249  0.000000  0.414085  0.586011  1.0  0.0  11.455
  2    0.996540  0.000000  0.003570  0.000000  0.000000  0.0  0.0  11.556
  3    0.994470  0.002834  0.002535  1.000000  0.000000  1.0  0.0  11.684
  4    0.994470  0.000000  0.005230  0.000000  0.000000  1.0  0.0  11.781
  ..        ...       ...       ...       ...       ...  ...  ...     ...
  262  0.997231  0.001565  0.001351  1.000000  0.000000  1.0  0.0  11.915
  263  0.997231  0.000000  0.002584  0.000000  0.000000  1.0  0.0  11.877
  264  0.988971  0.010881  0.000000  0.750019  0.249827  1.0  0.0  11.687
  265  1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0  11.624
  266  1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0  11.420


      Neff_I Neff_D
  0    1.000  0.000
  1    1.045  1.003
  2    0.000  0.000
  3    1.006  1.000
  4    0.000  1.001
  ..     ...    ...
  262  1.000  1.000
  263  0.000  1.000
  264  1.034  1.000
  265  0.000  0.000
  266  0.000  0.000

  [267 rows x 174 columns],
  '4bqh':     Residues                                                          \
           pdb label_entity_id label_asym_id label_seq_id auth_asym_id
  0       4bqh               1             A            1            A
  1       4bqh               1             A            2            A

- FreeSASA's `relative-area_side-chain` feature has a lot of NaNs due to glycines and it's not used.
- DSSP's `relative ASA` is NaN in some cases due to modified residues, e.g. 2qmx has MSE which was remapped to MET.
- Biopython is known to fail for some residues depending on their missing atoms.

<br>

## Per-pocket

Process the features and average per-pocket.

In [18]:
from utils.pocket_utils import get_mean_pocket_features

In [19]:
pockets = (
    pockets
    .query(f"pdb in {list(featuresd.keys())}")
)
pockets

,pdb,pocket,nres,site_in_pocket,pocket_in_site,label,Pocket Score,Drug Score,Number of alpha spheres,Mean alpha-sphere radius,...,Local hydrophobic density Score,Number of apolar alpha sphere,Proportion of apolar alpha sphere,Total SASA,Polar SASA,Apolar SASA,Proportion of polar atoms,Alpha sphere density,Cent. of mass - Alpha Sphere max dist,Flexibility
0,6ta3,pocket16,12,0.000000,0.0000,0,-0.0160,0.0145,79.0,3.4016,...,33.2273,44.0,0.5570,145.162,102.895,42.267,36.170,5.489,13.153,0.002
1,6ta3,pocket18,13,0.000000,0.0000,0,-0.0390,0.0001,48.0,3.5600,...,1.0000,2.0,0.0417,141.742,101.890,39.852,62.857,5.472,12.109,0.003
2,6ta3,pocket11,16,0.000000,0.0000,0,0.0606,0.0180,74.0,3.4367,...,26.6829,41.0,0.5541,116.997,36.739,80.258,41.304,5.183,12.464,0.395
3,6ta3,pocket15,11,0.000000,0.0000,0,-0.0097,0.0023,37.0,3.3932,...,12.5714,14.0,0.3784,97.871,30.244,67.627,42.857,4.211,10.405,0.407
4,6ta3,pocket7,42,0.000000,0.0000,0,0.2518,0.9883,244.0,3.5880,...,62.6740,181.0,0.7418,387.794,90.401,297.393,30.075,11.225,31.608,0.411
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8136,3d2p,pocket5,11,0.000000,0.0000,0,0.2167,0.0033,41.0,3.4642,...,13.8095,21.0,0.5122,74.790,31.316,43.475,36.364,5.179,9.584,0.281
8137,3d2p,pocket8,19,0.000000,0.0000,0,0.0886,0.0057,120.0,3.5617,...,8.9565,23.0,0.1917,205.618,101.049,104.569,45.588,6.886,19.284,0.417
8138,3d2p,pocket3,17,0.000000,0.0000,0,0.3030,0.0287,75.0,3.4781,...,16.0000,26.0,0.3467,116.634,42.969,73.665,44.681,6.894,15.728,0.509
8139,3d2p,pocket12,7,0.000000,0.0000,0,-0.0406,0.0007,36.0,3.6300,...,19.0000,20.0,0.5556,85.506,52.900,32.606,38.462,2.946,8.084,0.375
8140,3d2p,pocket6,16,0.043478,0.0625,0,0.1532,0.0075,92.0,3.5363,...,16.3448,29.0,0.3152,107.475,49.508,57.966,38.776,4.623,13.277,0.450

In [20]:
pockets = pd.concat(
    (
        pockets[["pdb", "pocket", "nres", "site_in_pocket", "pocket_in_site"]],
        pockets["label"],
        pockets.drop(columns=["pdb", "pocket", "label", "nres", "site_in_pocket", "pocket_in_site"])
    ),
    axis=1,
    keys=["Pockets", "Label", "FPocket"]
)

pockets

     Pockets                                              Label      FPocket  \
         pdb    pocket nres site_in_pocket pocket_in_site label Pocket Score
0       6ta3  pocket16   12       0.000000         0.0000     0      -0.0160
1       6ta3  pocket18   13       0.000000         0.0000     0      -0.0390
2       6ta3  pocket11   16       0.000000         0.0000     0       0.0606
3       6ta3  pocket15   11       0.000000         0.0000     0      -0.0097
4       6ta3   pocket7   42       0.000000         0.0000     0       0.2518
...      ...       ...  ...            ...            ...   ...          ...
8136    3d2p   pocket5   11       0.000000         0.0000     0       0.2167
8137    3d2p   pocket8   19       0.000000         0.0000     0       0.0886
8138    3d2p   pocket3   17       0.000000         0.0000     0       0.3030
8139    3d2p  pocket12    7       0.000000         0.0000     0      -0.0406
8140    3d2p   pocket6   16       0.043478         0.0625     0       0.1532

                                                                  ...  \
     Drug Score Number of alpha spheres Mean alpha-sphere radius  ...
0        0.0145                    79.0                   3.4016  ...
1        0.0001                    48.0                   3.5600  ...
2        0.0180                    74.0                   3.4367  ...
3        0.0023                    37.0                   3.3932  ...
4        0.9883                   244.0                   3.5880  ...
...         ...                     ...                      ...  ...
8136     0.0033                    41.0                   3.4642  ...
8137     0.0057                   120.0                   3.5617  ...
8138     0.0287                    75.0                   3.4781  ...
8139     0.0007                    36.0                   3.6300  ...
8140     0.0075                    92.0                   3.5363  ...

                                                                    \
     Local hydrophobic density Score Number of apolar alpha sphere
0                            33.2273                          44.0
1                             1.0000                           2.0
2                            26.6829                          41.0
3                            12.5714                          14.0
4                            62.6740                         181.0
...                              ...                           ...
8136                         13.8095                          21.0
8137                          8.9565                          23.0
8138                         16.0000                          26.0
8139                         19.0000                          20.0
8140                         16.3448                          29.0

                                                                          \
     Proportion of apolar alpha sphere Total SASA Polar SASA Apolar SASA
0                               0.5570    145.162    102.895      42.267
1                               0.0417    141.742    101.890      39.852
2                               0.5541    116.997     36.739      80.258
3                               0.3784     97.871     30.244      67.627
4                               0.7418    387.794     90.401     297.393
...                                ...        ...        ...         ...
8136                            0.5122     74.790     31.316      43.475
8137                            0.1917    205.618    101.049     104.569
8138                            0.3467    116.634     42.969      73.665
8139                            0.5556     85.506     52.900      32.606
8140                            0.3152    107.475     49.508      57.966

                                                     \
     Proportion of polar atoms Alpha sphere density
0                       36.170                5.489
1                       62.857                5.472
2                       41.304                5.183
3                       42.857                4.211
4                       30.075               11.225
...                        ...                  ...
8136                    36.364                5.179
8137                    45.588                6.886
8138                    44.681                6.894
8139                    38.462                2.946
8140                    38.776                4.623


     Cent. of mass - Alpha Sphere max dist Flexibility
0                                   13.153       0.002
1                                   12.109       0.003
2                                   12.464       0.395
3                                   10.405       0.407
4                                   31.608       0.411
...                                    ...         ...
8136                                 9.584       0.281
8137                                19.284       0.417
8138                                15.728       0.509
8139                                 8.084       0.375
8140                                13.277       0.450

[5405 rows x 28 columns]

In [21]:
pockets_features = pd.concat(
    (
        pockets,
        pockets.apply(
            lambda row: get_mean_pocket_features(
                row[("Pockets", "pdb")],
                row[("Pockets", "pocket")],
                pdb_features = featuresd[row[("Pockets", "pdb")]],
                pockets_path = "3.Pockets/old_fpocket/pockets" # # f"{pockets_path}/{pdb}/{pdb}_out/pockets/{pocket}_atm.cif"
            ), 
            axis=1 
        )
    ),
    axis=1
)

In [22]:
pockets_features

     Pockets                                              Label      FPocket  \
         pdb    pocket nres site_in_pocket pocket_in_site label Pocket Score
0       6ta3  pocket16   12       0.000000         0.0000     0      -0.0160
1       6ta3  pocket18   13       0.000000         0.0000     0      -0.0390
2       6ta3  pocket11   16       0.000000         0.0000     0       0.0606
3       6ta3  pocket15   11       0.000000         0.0000     0      -0.0097
4       6ta3   pocket7   42       0.000000         0.0000     0       0.2518
...      ...       ...  ...            ...            ...   ...          ...
8136    3d2p   pocket5   11       0.000000         0.0000     0       0.2167
8137    3d2p   pocket8   19       0.000000         0.0000     0       0.0886
8138    3d2p   pocket3   17       0.000000         0.0000     0       0.3030
8139    3d2p  pocket12    7       0.000000         0.0000     0      -0.0406
8140    3d2p   pocket6   16       0.043478         0.0625     0       0.1532

                                                                  ...  \
     Drug Score Number of alpha spheres Mean alpha-sphere radius  ...
0        0.0145                    79.0                   3.4016  ...
1        0.0001                    48.0                   3.5600  ...
2        0.0180                    74.0                   3.4367  ...
3        0.0023                    37.0                   3.3932  ...
4        0.9883                   244.0                   3.5880  ...
...         ...                     ...                      ...  ...
8136     0.0033                    41.0                   3.4642  ...
8137     0.0057                   120.0                   3.5617  ...
8138     0.0287                    75.0                   3.4781  ...
8139     0.0007                    36.0                   3.6300  ...
8140     0.0075                    92.0                   3.5363  ...

       HHBlits                                                              \
          M->M      M->I      M->D      I->M      I->I      D->M      D->D
0     0.971722  0.011249  0.017076  0.176411  0.823637  0.151071  0.848930
1     0.974105  0.012294  0.013511  0.187106  0.812923  0.253341  0.746686
2     0.968439  0.015852  0.015674  0.491783  0.508309  0.206654  0.793426
3     0.888404  0.030708  0.080922  0.274259  0.725673  0.135536  0.864436
4     0.957620  0.021926  0.020451  0.348753  0.627444  0.219810  0.780225
...        ...       ...       ...       ...       ...       ...       ...
8136  0.989698  0.006181  0.004065  0.505737  0.494248  0.289794  0.710212
8137  0.912140  0.040368  0.047440  0.444674  0.502660  0.245143  0.754912
8138  0.954826  0.028198  0.016987  0.390967  0.432574  0.214760  0.785243
8139  0.978512  0.008635  0.012686  0.558250  0.298870  0.209000  0.790977
8140  0.938259  0.039010  0.022726  0.460395  0.352079  0.364345  0.635664


           Neff    Neff_I    Neff_D
0      9.994750  1.156583  2.557083
1      9.824308  1.154846  2.152077
2     10.325625  1.141812  1.770438
3     10.183727  1.275091  3.316091
4     10.475976  1.187833  1.982500
...         ...       ...       ...
8136  12.009636  1.059273  1.135545
8137   8.720632  1.300158  2.198632
8138   8.712882  1.092588  1.600118
8139   8.564143  0.943143  2.130000
8140   9.773813  1.138000  1.508125

[5405 rows x 194 columns]

In [32]:
pockets_featuresf = f"{features_path}/pockets_features.pkl"

if not os.path.isfile(pockets_featuresf):
    pockets_featuresd = {
        pdb: pks
        for pdb, pks in pockets_features.groupby(("Pockets", "pdb"), sort=False)
    }
    with open(pockets_featuresf, "wb") as f:
        pickle.dump(pockets_featuresd, f)
else:
    with open(pockets_featuresf, "rb") as f:
        pockets_featuresd = pickle.load(f)

len(pockets_featuresd), pockets_featuresd

(289,
 {'6ta3':    Pockets                                              Label      FPocket  \
         pdb    pocket nres site_in_pocket pocket_in_site label Pocket Score
  0     6ta3  pocket16   12       0.000000       0.000000     0      -0.0160
  1     6ta3  pocket18   13       0.000000       0.000000     0      -0.0390
  2     6ta3  pocket11   16       0.000000       0.000000     0       0.0606
  3     6ta3  pocket15   11       0.000000       0.000000     0      -0.0097
  4     6ta3   pocket7   42       0.000000       0.000000     0       0.2518
  5     6ta3  pocket22   10       0.000000       0.000000     0      -0.1444
  6     6ta3  pocket13   31       0.000000       0.000000     0       0.0183
  7     6ta3  pocket14    9       0.000000       0.000000     0       0.0062
  8     6ta3   pocket1  141       0.000000       0.000000     0       2.0589
  9     6ta3   pocket2  114       1.000000       0.236842     1       0.7266
  10    6ta3  pocket20   13       0.000000       0.000000     0      -0.1059
  11    6ta3   pocket4   16       0.000000       0.000000     0       0.3327
  12    6ta3  pocket17   14       0.000000       0.000000     0      -0.0311
  13    6ta3   pocket9   13       0.148148       0.307692     0       0.1079
  14    6ta3  pocket10   27       0.000000       0.000000     0       0.0943
  15    6ta3   pocket5   20       0.185185       0.250000     0       0.2865
  16    6ta3   pocket8   62       0.074074       0.032258     0       0.2468
  17    6ta3   pocket3   43       0.185185       0.116279     0       0.4106
  18    6ta3  pocket12   14       0.000000       0.000000     0       0.0437
  19    6ta3  pocket19   12       0.000000       0.000000     0      -0.0998
  20    6ta3  pocket21   15       0.000000       0.000000     0      -0.1119
  21    6ta3   pocket6   12       0.000000       0.000000     0       0.2755

                                                                  ...   HHBlits  \
     Drug Score Number of alpha spheres Mean alpha-sphere radius  ...      M->M
  0      0.0145                    79.0                   3.4016  ...  0.971722
  1      0.0001                    48.0                   3.5600  ...  0.974105
  2      0.0180                    74.0                   3.4367  ...  0.968439
  3      0.0023                    37.0                   3.3932  ...  0.888404
  4      0.9883                   244.0                   3.5880  ...  0.957620
  5      0.0015                    36.0                   3.4677  ...  0.953983
  6      0.0118                   156.0                   3.5623  ...  0.957321
  7      0.0119                    37.0                   3.4417  ...  0.966856
  8      0.9660                   853.0                   3.5540  ...  0.964211
  9      0.0049                   811.0                   3.5464  ...  0.974490
  10     0.0214                    61.0                   3.5564  ...  0.969708
  11     0.0268                    52.0                   3.1947  ...  0.967896
  12     0.0015                    69.0                   3.4524  ...  0.941015
  13     0.0009                    45.0                   3.4082  ...  0.979069
  14     0.9656                   155.0                   3.5541  ...  0.965960
  15     0.2708                    84.0                   3.3554  ...  0.980856
  16     0.9105                   424.0                   3.5780  ...  0.979424
  17     0.9445                   216.0                   3.5403  ...  0.981092
  18     0.0403                    72.0                   3.4437  ...  0.937574
  19     0.0008                    43.0                   3.6968  ...  0.946060
  20     0.0061                    48.0                   3.4520  ...  0.944683
  21     0.0852                    55.0                   3.3567  ...  0.969218

                                                                             \
          M->I      M->D      I->M      I->I      D->M      D->D       Neff
  0   0.011249  0.017076  0.176411  0.823637  0.151071  0.848930   9.994750
  1   0.012294  0.013511  0.187106  0.812923  0.253341  0.746686   9.824308
  2   0.015852  0.015674  0.491783  0.508309  0.206654  0.793426  10.325625
  3   0.030708  0.080922  0.274259  0.725673  0.135536  0.864436  10.183727
  4   0.021926  0.020451  0.348753  0.627444  0.219810  0.780225  10.475976
  5   0.022694  0.023247  0.137002  0.863077  0.263108  0.736937   9.956200
  6   0.022367  0.020291  0.291321  0.676419  0.176864  0.823193  10.156226
  7   0.020386  0.012867  0.351463  0.648615  0.273618  0.726480  10.185444
  8   0.018522  0.017255  0.337046  0.606211  0.184416  0.780152  10.167780
  9   0.013216  0.012297  0.238150  0.735535  0.186681  0.813337   9.950246
  10  0.019436  0.010898  0.247944  0.675124  0.216993  0.782990  10.262692
  11  0.013925  0.018267  0.356358  0.643643  0.205989  0.794038  10.162688
  12  0.034275  0.024708  0.235921  0.692599  0.235403  0.621754   9.627571
  13  0.008298  0.012725  0.269145  0.730874  0.218154  0.781841   9.735462
  14  0.007784  0.026249  0.297850  0.516977  0.145406  0.706471  10.073926
  15  0.006940  0.012259  0.254824  0.595211  0.285981  0.714079  10.768550
  16  0.007700  0.012894  0.221064  0.698270  0.170582  0.829422   9.985871
  17  0.010172  0.008732  0.265893  0.687587  0.181903  0.818108   9.876209
  18  0.033641  0.028740  0.264281  0.735661  0.226041  0.774015  10.496714
  19  0.037557  0.016353  0.318881  0.681094  0.181081  0.818919  10.434917
  20  0.024801  0.030505  0.286246  0.713752  0.164194  0.835868  10.349533
  21  0.017874  0.012829  0.179998  0.736666  0.158770  0.841263   9.984417


        Neff_I    Neff_D
  0   1.156583  2.557083
  1   1.154846  2.152077
  2   1.141812  1.770438
  3   1.275091  3.316091
  4   1.187833  1.982500
  5   1.353000  2.863800
  6   1.306355  1.937258
  7   1.197222  2.162889
  8   1.147340  2.017773
  9   1.144404  1.919667
  10  1.195923  1.793923
  11  1.186688  1.970375
  12  1.359429  2.445143
  13  1.103077  1.566077
  14  0.924111  1.727741
  15  0.922500  1.612750
  16  1.027452  1.829758
  17  1.098651  1.870884
  18  1.326286  2.004643
  19  1.408000  1.967583
  20  1.211400  2.671733
  21  1.192333  2.000667

  [22 rows x 194 columns],
  '5kwj':    Pockets                                             Label      FPocket  \
         pdb   pocket nres site_in_pocket pocket_in_site label Pocket Score
  22    5kwj  pocket1   46            1.0       0.217391     1       0.5169
  23    5kwj  pocket2   19            0.0       0.000000     0       0.4387
  24    5kwj  pocket4   17            0.0       0.000000     0      -0.0222
  25    5kwj  pocket5   10            0.0       0.000000     0      -0.0381
  26    5kwj  pocket3   11            0.0       0.000000     0       0.0289
  27    5kwj  pocket6   21            0.0       0.000000     0      -0.1698

                                                                  ...   HHBlits  \
     Drug Score Number of alpha spheres Mean alpha-sphere radius  ...      M->M
  22     0.9745                   298.0                   3.4265  ...  0.943829
  23     0.3067                    86.0                   3.3908  ...  0.981054
  24     0.0002                    65.0                   3.7301  ...  0.982741
  25     0.0066                    52.0                   3.5630  ...  0.939657
  26     0.0029                    44.0                   3.6264  ...  0.945818
  27     0.0016                   102.0                   3.6643  ...  0.938257

                                                                             \
          M->I      M->D      I->M      I->I      D->M      D->D       Neff
  22  0.019534  0.036645  0.374693  0.538332  0.188763  0.811216  12.796000
  23  0.011601  0.007315  0.325240  0.674772  0.140677  0.859313  13.194263
  24  0.008372  0.008821  0.355841  0.585323  0.447145  0.552787  12.890706
  25  0.013509  0.046819  0.290462  0.709510  0.161189  0.838811  13.071500
  26  0.024418  0.029730  0.346038  0.654003  0.080462  0.919533  13.144091
  27  0.033942  0.027863  0.261115  0.691267  0.048214  0.951717  12.277714


        Neff_I    Neff_D
  22  1.211870  4.778174
  23  1.298421  3.082842
  24  1.117647  3.610000
  25  1.273100  5.003400
  26  1.502727  4.729273
  27  1.324952  8.558000

  [6 rows x 194 columns],
  '6t4k':    Pockets                                              Label      FPocket  \
         pdb    pocket nres site_in_pocket pocket_in_site label Pocket Score
  28    6t4k   pocket7   18       0.064516       0.111111     0       0.1011
  29    6t4k   pocket1   32       0.935484       0.906250     1       0.6382
  30    6t4k   pocket2   24       0.129032       0.166667     0       0.4838
  31    6t4k   pocket4   11       0.000000       0.000000     0       0.2847
  32    6t4k   pocket9   12       0.000000       0.000000     0       0.0635
  33    6t4k  pocket10    8       0.000000       0.000000     0      -0.0422
  34    6t4k   pocket5   18       0.000000       0.000000     0       0.1913
  35    6t4k   pocket8    9       0.096774       0.333333     0       0.0946
  36    6t4k   pocket3   12       0.000000       0.000000     0       0.3352
  37    6t4k   pocket6   12       0.032258       0.083333     0       0.1324

                                                                  ...   HHBlits  \
     Drug Score Number of alpha spheres Mean alpha-sphere radius  ...      M->M
  28     0.0012                    75.0                   3.6407  ...  0.961338
  29     0.9502                   149.0                   3.6986  ...  0.968969
  30     0.9420                   171.0                   3.6925  ...  0.968313
  31     0.0029                    49.0                   3.4688  ...  0.935729
  32     0.0188                    49.0                   3.6567  ...  0.982893
  33     0.0012                    38.0                   3.6787  ...  0.969902
  34     0.0119                    63.0                   3.5531  ...  0.927437
  35     0.0053                    52.0                   3.4860  ...  0.936462
  36     0.0126                    48.0                   3.2805  ...  0.991504
  37     0.0020                    61.0                   3.5795  ...  0.989241

                                                                             \
          M->I      M->D      I->M      I->I      D->M      D->D       Neff
  28  0.027893  0.010633  0.474535  0.525518  0.158070  0.841975  11.462000
  29  0.020236  0.010845  0.283325  0.685407  0.177944  0.822069  11.448000
  30  0.007167  0.024425  0.344152  0.614228  0.286666  0.630004  11.275292
  31  0.059560  0.004700  0.298608  0.701383  0.196235  0.803777  11.431364
  32  0.012333  0.004897  0.234106  0.765880  0.215397  0.701268  11.437583
  33  0.027011  0.003117  0.242001  0.757979  0.232351  0.767655  11.451875
  34  0.053758  0.018866  0.421422  0.578580  0.177287  0.822688  11.452667
  35  0.044533  0.019035  0.230699  0.769364  0.185228  0.814806  11.422556
  36  0.004088  0.004430  0.383513  0.533111  0.160868  0.839147  11.431417
  37  0.005947  0.004782  0.216933  0.366366  0.154912  0.845100  11.351333


        Neff_I    Neff_D
  28  1.514111  2.271889
  29  1.329625  1.950813
  30  1.024250  1.786708
  31  1.783818  1.717727
  32  1.223167  1.389583
  33  1.505125  1.685875
  34  1.580222  1.829167
  35  1.804000  2.977000
  36  0.988250  1.382917
  37  0.642750  1.320750

  [10 rows x 194 columns],
  '5mo6':    Pockets                                              Label      FPocket  \
         pdb    pocket nres site_in_pocket pocket_in_site label Pocket Score
  38    5mo6  pocket11   13           0.00       0.000000     0      -0.1130
  39    5mo6   pocket7    8           0.00       0.000000     0      -0.0600
  40    5mo6  pocket13   19           0.04       0.052632     0      -0.2784
  41    5mo6   pocket1   18           0.00       0.000000     0       0.3237
  42    5mo6   pocket2   10           0.16       0.400000     0       0.1524
  43    5mo6   pocket4    9           0.00       0.000000     0       0.0214
  44    5mo6   pocket9   13           0.00       0.000000     0      -0.1012
  45    5mo6  pocket10   15           0.00       0.000000     0      -0.1079
  46    5mo6   pocket5   31           0.84       0.677419     1      -0.0025
  47    5mo6   pocket8   25           0.20       0.200000     0      -0.0675
  48    5mo6   pocket3   19           0.00       0.000000     0       0.0873
  49    5mo6  pocket12   13           0.00       0.000000     0      -0.1199
  50    5mo6   pocket6   10           0.00       0.000000     0      -0.0065

                                                                  ...   HHBlits  \
     Drug Score Number of alpha spheres Mean alpha-sphere radius  ...      M->M
  38     0.0099                    63.0                   3.6274  ...  0.951539
  39     0.0056                    36.0                   3.6326  ...  0.943508
  40     0.0001                    76.0                   3.8518  ...  0.964869
  41     0.1541                   101.0                   3.4159  ...  0.966493
  42     0.0140                    41.0                   3.4549  ...  0.954177
  43     0.0002                    47.0                   3.5343  ...  0.953216
  44     0.0006                    65.0                   3.6023  ...  0.936528
  45     0.0004                    82.0                   3.6234  ...  0.940504
  46     0.8020                   213.0                   3.7234  ...  0.959588
  47     0.5844                   148.0                   3.7714  ...  0.977349
  48     0.0120                    83.0                   3.6272  ...  0.960254
  49     0.0002                    40.0                   3.6507  ...  0.945935
  50     0.0016                    40.0                   3.6030  ...  0.946316

                                                                             \
          M->I      M->D      I->M      I->I      D->M      D->D       Neff
  38  0.028551  0.019896  0.288454  0.711523  0.204639  0.795445  10.955000
  39  0.046292  0.010184  0.191645  0.808293  0.185557  0.814456  11.204250
  40  0.022752  0.012327  0.217185  0.782823  0.156821  0.843189  10.997895
  41  0.017513  0.015970  0.242300  0.702138  0.258928  0.741012  10.552611
  42  0.032706  0.013063  0.185849  0.814200  0.174329  0.825671  11.091900
  43  0.020923  0.025920  0.188281  0.811656  0.060424  0.939528  11.028778
  44  0.028008  0.035453  0.273657  0.726411  0.239466  0.760576  10.330923
  45  0.023004  0.036484  0.224497  0.775465  0.129703  0.870248  10.807400
  46  0.023735  0.016660  0.179458  0.820557  0.160399  0.839578  11.017387
  47  0.012802  0.009796  0.226854  0.773204  0.149391  0.850581  11.214400
  48  0.013397  0.026342  0.243282  0.704054  0.116220  0.883738  11.155737
  49  0.031154  0.022971  0.197532  0.802429  0.157486  0.842509  10.543308
  50  0.023215  0.030379  0.269575  0.730459  0.120133  0.879834  11.032700


        Neff_I    Neff_D
  38  1.458462  2.349077
  39  1.836750  1.856875
  40  1.412211  2.130474
  41  1.182889  1.489778
  42  1.541200  2.571100
  43  1.145222  4.229111
  44  1.379385  2.943000
  45  1.354400  3.648200
  46  1.436387  2.270258
  47  1.223440  1.791600
  48  1.036105  3.247789
  49  1.484154  2.565692
  50  1.298400  3.232200

  [13 rows x 194 columns],
  '3o0n':    Pockets                                              Label      FPocket  \
         pdb    pocket nres site_in_pocket pocket_in_site label Pocket Score
  51    3o0n  pocket16   12       0.000000       0.000000     0       0.1389
  52    3o0n  pocket28   20       0.115385       0.150000     0      -0.0176
  53    3o0n  pocket18   11       0.000000       0.000000     0       0.1252
  54    3o0n  pocket11   10       0.000000       0.000000     0       0.1802
  55    3o0n  pocket34   12       0.000000       0.000000     0      -0.0633
  56    3o0n  pocket25    9       0.000000       0.000000     0       0.0270
  57    3o0n  pocket15   20       0.000000       0.000000     0       0.1396
  58    3o0n  pocket40   12       0.000000       0.000000     0      -0.1048
  59    3o0n   pocket7   16       0.000000       0.000000     0       0.2740
  60    3o0n  pocket22   12       0.000000       0.000000     0       0.0798
  61    3o0n  pocket13   10       0.000000       0.000000     0       0.1467
  62    3o0n  pocket31   11       0.115385       0.272727     0      -0.0447
  63    3o0n  pocket39   11       0.000000       0.000000     0      -0.0882
  64    3o0n  pocket23   15       0.000000       0.000000     0       0.0706
  65    3o0n  pocket14   10       0.000000       0.000000     0       0.1461
  66    3o0n  pocket26   10       0.000000       0.000000     0       0.0232
  67    3o0n   pocket1   72       0.000000       0.000000     0       0.6151
  68    3o0n  pocket27   14       0.000000       0.000000     0       0.0117
  69    3o0n   pocket2   47       0.120000       0.063830     0       0.5351
  70    3o0n  pocket32   10       0.000000       0.000000     0      -0.0592
  71    3o0n  pocket20   15       0.000000       0.000000     0       0.1156
  72    3o0n   pocket4   11       0.000000       0.000000     0       0.3368
  73    3o0n  pocket29   15       0.000000       0.000000     0      -0.0207
  74    3o0n  pocket30    6       0.000000       0.000000     0      -0.0409
  75    3o0n  pocket17   11       0.000000       0.000000     0       0.1348
  76    3o0n   pocket9   15       0.000000       0.000000     0       0.2392
  77    3o0n  pocket10   15       0.000000       0.000000     0       0.2246
  78    3o0n  pocket35   20       0.730769       0.950000     1      -0.0702
  79    3o0n   pocket5   11       0.000000       0.000000     0       0.3044
  80    3o0n   pocket8   36       0.000000       0.000000     0       0.2677
  81    3o0n  pocket37   11       0.000000       0.000000     0      -0.0765
  82    3o0n  pocket24   10       0.000000       0.000000     0       0.0691
  83    3o0n   pocket3   54       0.800000       0.370370     1       0.4145
  84    3o0n  pocket12   11       0.000000       0.000000     0       0.1738
  85    3o0n  pocket38    9       0.000000       0.000000     0      -0.0814
  86    3o0n  pocket42   13       0.000000       0.000000     0      -0.1372
  87    3o0n  pocket19   14       0.000000       0.000000     0       0.1160
  88    3o0n  pocket21    8       0.000000       0.000000     0       0.1130
  89    3o0n  pocket33   10       0.000000       0.000000     0      -0.0599
  90    3o0n  pocket36   11       0.000000       0.000000     0      -0.0744
  91    3o0n  pocket41   27       0.230769       0.222222     0      -0.1128
  92    3o0n   pocket6   47       0.000000       0.000000     0       0.2878

                                                                  ...   HHBlits  \
     Drug Score Number of alpha spheres Mean alpha-sphere radius  ...      M->M
  51     0.0151                    49.0                   3.6148  ...  0.973952
  52     0.0010                    88.0                   3.6253  ...  0.962032
  53     0.0026                    58.0                   3.5005  ...  0.868131
  54     0.0713                    50.0                   3.4048  ...  0.978023
  55     0.0031                    44.0                   3.5127  ...  0.963009
  56     0.0004                    48.0                   3.6439  ...  0.881351
  57     0.0266                    81.0                   3.4013  ...  0.928790
  58     0.0059                    42.0                   3.5775  ...  0.963335
  59     0.6224                    65.0                   3.2682  ...  0.950726
  60     0.0052                    69.0                   3.6235  ...  0.989266
  61     0.0362                    48.0                   3.6375  ...  0.978023
  62     0.0047                    42.0                   3.6401  ...  0.889641
  63     0.1256                    46.0                   3.5509  ...  0.903707
  64     0.0748                    98.0                   3.5868  ...  0.982720