# Requisites

- Active environment with dependencies defined in `conda_env.yaml`
- External dependency to be downloaded and placed in `training_data/utils/external`:
    predict_ddG.py script from PyRosetta (https://github.com/RosettaCommons/PyRosetta.notebooks/blob/master/notebooks/additional_scripts/predict_ddG.py)

In [1]:
!wget https://github.com/RosettaCommons/PyRosetta.notebooks/raw/refs/heads/master/notebooks/additional_scripts/predict_ddG.py -O training_data/utils/external/predict_ddG.py

--2026-01-15 15:24:59--  https://github.com/RosettaCommons/PyRosetta.notebooks/raw/refs/heads/master/notebooks/additional_scripts/predict_ddG.py
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/RosettaCommons/PyRosetta.notebooks/refs/heads/master/notebooks/additional_scripts/predict_ddG.py [following]
--2026-01-15 15:24:59--  https://raw.githubusercontent.com/RosettaCommons/PyRosetta.notebooks/refs/heads/master/notebooks/additional_scripts/predict_ddG.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11993 (12K) [text/plain]
Saving to: ‘training_data/utils/external/predict_ddG.py’

training_data/utils 100%[===================>]  11.71K  --.-KB/s    in 0.003s

2026-01-15 15:25:00 (4.48 MB/s) - ‘training_data/utils/external/predict_ddG.py’ saved [11993/11993]

In [2]:
from predict import get_cif, view_pdb, predict, view_pockets, view_pockets_pathways, Site

/home/fnerin/miniforge3/envs/allopockets/lib/python3.11/site-packages/prody/utilities/misctools.py:424: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

┌──────────────────────────────────────────────────────────────────────────────┐
│                                 PyRosetta-4                                  │
│              Created in JHU by Sergey Lyskov and PyRosetta Team              │
│              (C) Copyright Rosetta Commons Member Institutions               │
│                                                                              │
│ NOTE: USE OF PyRosetta FOR COMMERCIAL PURPOSES REQUIRE PURCHASE OF A LICENSE │
│         See LICENSE.PyRosetta.md or email license@uw.edu for details         │
└──────────────────────────────────────────────────────────────────────────────┘
PyRosetta-4 2025 [Rosetta PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release 2025.24+release.8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 2025-06-06T09:20:57] retrieved from: http://www.pyrosetta.org
core.init: Checking for fconfig files in pwd and ./rosetta/flags
core.init: Rosetta version: PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release r403 2025.24+release.8e1e5e54f0 8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 http://www.pyrosetta.org 2025-06-06T09:20:57
core.init: Rosetta extras: [cxx11thread, serialization]
core.init: command: PyRosetta -mute core.pack basic core.scoring -ignore_zero_occupancy false -database /home/fnerin/miniforge3/envs/allopockets/lib/python3.11/site-packages/pyrosetta/database

Found 1 mismatches between original and current metadata:
	INFO: AutoGluon Python micro version mismatch (original=3.11.9, current=3.11.14)

<br>

**Files are written by default to the `predict` folder, customize it with using a different `path=` argument in the functions below.**

<br>

# Predict

## Protein structure

Provide a PDB ID or a valid .pdb or .cif (or .cif.gz) file.

In [3]:
pdb = get_cif(
    pdb_id = "6t4k"
    # file = "6t4k.pdb"
)

view_pdb(pdb)

## Predict

**ColabFold MSA**

For single predictions, HHBlits' resource-intensive calculations are substituted in this notebook by an HHM built from a Multiple Sequence Alignment computed through ColabFold. To use ColabFold's MSA services, please provide your email to the server's call below, respect [ColabFold's MSA server usage limits](https://github.com/sokrypton/ColabFold#:~:text=Is%20it%20okay%20to%20use%20the%20MMseqs2%20MSA%20server%20(cf.run_mmseqs2)%20on%20a%20local%20computer%3F) and [acknowledge the tool](https://github.com/sokrypton/ColabFold#how-do-i-reference-this-work) appropriately. Consider switching to the [local setup of HHBlits](https://github.com/frannerin/AlloPockets#hhblits-for-multiple-predictions) to perform multiple AlloPockets computations.

In [4]:
clean_pdb, predictions = predict(
    pdb,
    protein_chains=["A"],
    email="fnerin@bioacademy.gr"
)

***** POCKET HUNTING BEGINS *****
***** POCKET HUNTING ENDS *****

COMPLETE: 100%|██████████████████████████████████████████████████████████████| 150/150 [elapsed: 00:03 remaining: 00:00]

  0%|          | 0/9 [00:00<?, ?it/s]

Output()

core.chemical.GlobalResidueTypeSet: Finished initializing fa_standard residue type set.  Created 985 residue types
core.chemical.GlobalResidueTypeSet: Total time to initialize 0.380721 seconds.
core.import_pose.import_pose: File 'predict/6t4k.cif' automatically determined to be of type mmCIF from contents.

2026-01-15 15:25:42,525 - .prody - WARNING - WARNING Could not find _atom_site_anisotrop in lines.
2026-01-15 15:25:42,526 - .prody - WARNING - WARNING No anisotropic B factors found
2026-01-15 15:25:42,526 - .prody - DEBUG - 1974 atoms and 1 coordinate set(s) were parsed in 0.02s.
2026-01-15 15:25:42,555 - .prody - DEBUG - Hessian was built in 0.03s.
2026-01-15 15:25:43,130 - .prody - DEBUG - 714 modes were calculated in 0.57s.
2026-01-15 15:25:43,170 - .prody - INFO - Calculating stiffness matrix.
2026-01-15 15:25:43,234 - .prody - DEBUG - Stiffness matrix calculated in 0.07s.
2026-01-15 15:25:43,235 - .prody - INFO - The range of effective force constant is: 7.6088238200526535 to 24.36233389027474.
2026-01-15 15:25:43,241 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:43,329 - .prody - DEBUG - 10 modes were calculated in 0.09s.
2026-01-15 15:25:43,342 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:43,414 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:43,427 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:43,500 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:43,507 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:43,609 - .prody - DEBUG - 10 modes were calculated in 0.10s.
2026-01-15 15:25:43,619 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:43,717 - .prody - DEBUG - 10 modes were calculated in 0.09s.
2026-01-15 15:25:43,726 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:43,819 - .prody - DEBUG - 10 modes were calculated in 0.09s.
2026-01-15 15:25:43,828 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:43,916 - .prody - DEBUG - 10 modes were calculated in 0.09s.
2026-01-15 15:25:43,922 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:43,984 - .prody - DEBUG - 10 modes were calculated in 0.06s.
2026-01-15 15:25:43,995 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:44,090 - .prody - DEBUG - 10 modes were calculated in 0.09s.
2026-01-15 15:25:44,102 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:44,176 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:44,184 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:44,282 - .prody - DEBUG - 10 modes were calculated in 0.10s.
2026-01-15 15:25:44,291 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:44,369 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:44,383 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:44,481 - .prody - DEBUG - 10 modes were calculated in 0.09s.
2026-01-15 15:25:44,492 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:44,558 - .prody - DEBUG - 10 modes were calculated in 0.06s.
2026-01-15 15:25:44,571 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:44,625 - .prody - DEBUG - 10 modes were calculated in 0.05s.
2026-01-15 15:25:44,632 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:44,697 - .prody - DEBUG - 10 modes were calculated in 0.06s.
2026-01-15 15:25:44,706 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:44,778 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:44,786 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:44,860 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:44,868 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:44,959 - .prody - DEBUG - 10 modes were calculated in 0.09s.
2026-01-15 15:25:44,967 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:45,067 - .prody - DEBUG - 10 modes were calculated in 0.09s.
2026-01-15 15:25:45,074 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:45,139 - .prody - DEBUG - 10 modes were calculated in 0.06s.
2026-01-15 15:25:45,146 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:45,225 - .prody - DEBUG - 10 modes were calculated in 0.08s.
2026-01-15 15:25:45,234 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:45,336 - .prody - DEBUG - 10 modes were calculated in 0.10s.
2026-01-15 15:25:45,346 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:45,417 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:45,430 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:45,542 - .prody - DEBUG - 10 modes were calculated in 0.11s.
2026-01-15 15:25:45,550 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:45,627 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:45,635 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:45,697 - .prody - DEBUG - 10 modes were calculated in 0.06s.
2026-01-15 15:25:45,707 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:45,764 - .prody - DEBUG - 10 modes were calculated in 0.06s.
2026-01-15 15:25:45,776 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:45,841 - .prody - DEBUG - 10 modes were calculated in 0.06s.
2026-01-15 15:25:45,851 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:45,926 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:45,934 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:46,005 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:46,013 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:46,087 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:46,094 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:46,160 - .prody - DEBUG - 10 modes were calculated in 0.06s.
2026-01-15 15:25:46,172 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:46,245 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:46,252 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:46,312 - .prody - DEBUG - 10 modes were calculated in 0.06s.
2026-01-15 15:25:46,322 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:46,380 - .prody - DEBUG - 10 modes were calculated in 0.06s.
2026-01-15 15:25:46,393 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:46,481 - .prody - DEBUG - 10 modes were calculated in 0.09s.
2026-01-15 15:25:46,489 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:46,572 - .prody - DEBUG - 10 modes were calculated in 0.08s.
2026-01-15 15:25:46,580 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:46,668 - .prody - DEBUG - 10 modes were calculated in 0.09s.
2026-01-15 15:25:46,676 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:46,783 - .prody - DEBUG - 10 modes were calculated in 0.10s.
2026-01-15 15:25:46,795 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:46,864 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:46,873 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:46,959 - .prody - DEBUG - 10 modes were calculated in 0.08s.
2026-01-15 15:25:46,968 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:47,048 - .prody - DEBUG - 10 modes were calculated in 0.08s.
2026-01-15 15:25:47,057 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:47,123 - .prody - DEBUG - 10 modes were calculated in 0.06s.
2026-01-15 15:25:47,132 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:47,228 - .prody - DEBUG - 10 modes were calculated in 0.09s.
2026-01-15 15:25:47,236 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:47,302 - .prody - DEBUG - 10 modes were calculated in 0.06s.
2026-01-15 15:25:47,309 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:47,377 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:47,385 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:47,460 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:47,469 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:47,538 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:47,546 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:47,626 - .prody - DEBUG - 10 modes were calculated in 0.08s.
2026-01-15 15:25:47,637 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:47,703 - .prody - DEBUG - 10 modes were calculated in 0.06s.
2026-01-15 15:25:47,713 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:47,777 - .prody - DEBUG - 10 modes were calculated in 0.06s.
2026-01-15 15:25:47,786 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:47,867 - .prody - DEBUG - 10 modes were calculated in 0.08s.
2026-01-15 15:25:47,875 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:47,947 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:47,954 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:48,028 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:48,035 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:48,098 - .prody - DEBUG - 10 modes were calculated in 0.06s.
2026-01-15 15:25:48,109 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:48,183 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:48,192 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:48,265 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:48,272 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:48,339 - .prody - DEBUG - 10 modes were calculated in 0.06s.
2026-01-15 15:25:48,345 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:48,409 - .prody - DEBUG - 10 modes were calculated in 0.06s.
2026-01-15 15:25:48,417 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:48,489 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:48,497 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:48,554 - .prody - DEBUG - 10 modes were calculated in 0.05s.
2026-01-15 15:25:48,567 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:48,635 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:48,643 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:48,714 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:48,722 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:48,814 - .prody - DEBUG - 10 modes were calculated in 0.09s.
2026-01-15 15:25:48,824 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:48,915 - .prody - DEBUG - 10 modes were calculated in 0.09s.
2026-01-15 15:25:48,927 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:48,995 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:49,003 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:49,085 - .prody - DEBUG - 10 modes were calculated in 0.08s.
2026-01-15 15:25:49,096 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:49,180 - .prody - DEBUG - 10 modes were calculated in 0.08s.
2026-01-15 15:25:49,187 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:49,274 - .prody - DEBUG - 10 modes were calculated in 0.09s.
2026-01-15 15:25:49,283 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:49,357 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:49,371 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:49,458 - .prody - DEBUG - 10 modes were calculated in 0.08s.
2026-01-15 15:25:49,468 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:49,540 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:49,548 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:49,603 - .prody - DEBUG - 10 modes were calculated in 0.05s.
2026-01-15 15:25:49,612 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:49,671 - .prody - DEBUG - 10 modes were calculated in 0.06s.
2026-01-15 15:25:49,679 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:49,752 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:49,758 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:49,831 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:49,840 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:49,902 - .prody - DEBUG - 10 modes were calculated in 0.06s.
2026-01-15 15:25:49,910 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:49,974 - .prody - DEBUG - 10 modes were calculated in 0.06s.
2026-01-15 15:25:49,982 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:50,052 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:50,059 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:50,147 - .prody - DEBUG - 10 modes were calculated in 0.09s.
2026-01-15 15:25:50,154 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:50,227 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:50,235 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:50,304 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:50,311 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:50,389 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:50,397 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:50,478 - .prody - DEBUG - 10 modes were calculated in 0.08s.
2026-01-15 15:25:50,487 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:50,576 - .prody - DEBUG - 10 modes were calculated in 0.09s.
2026-01-15 15:25:50,584 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:50,677 - .prody - DEBUG - 10 modes were calculated in 0.09s.
2026-01-15 15:25:50,686 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:50,759 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:50,774 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:50,894 - .prody - DEBUG - 10 modes were calculated in 0.12s.
2026-01-15 15:25:50,903 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:51,017 - .prody - DEBUG - 10 modes were calculated in 0.11s.
2026-01-15 15:25:51,024 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:51,114 - .prody - DEBUG - 10 modes were calculated in 0.09s.
2026-01-15 15:25:51,120 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:51,203 - .prody - DEBUG - 10 modes were calculated in 0.08s.
2026-01-15 15:25:51,212 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:51,285 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:51,294 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:51,386 - .prody - DEBUG - 10 modes were calculated in 0.09s.
2026-01-15 15:25:51,395 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:51,464 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:51,476 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:51,529 - .prody - DEBUG - 10 modes were calculated in 0.05s.
2026-01-15 15:25:51,537 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:51,612 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:51,625 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:51,693 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:51,702 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:51,781 - .prody - DEBUG - 10 modes were calculated in 0.08s.
2026-01-15 15:25:51,789 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:51,858 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:51,865 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:51,934 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:51,946 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:52,018 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:52,026 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:52,088 - .prody - DEBUG - 10 modes were calculated in 0.06s.
2026-01-15 15:25:52,097 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:52,163 - .prody - DEBUG - 10 modes were calculated in 0.06s.
2026-01-15 15:25:52,171 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:52,259 - .prody - DEBUG - 10 modes were calculated in 0.09s.
2026-01-15 15:25:52,271 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:52,348 - .prody - DEBUG - 10 modes were calculated in 0.08s.
2026-01-15 15:25:52,356 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:52,427 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:52,433 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:52,549 - .prody - DEBUG - 10 modes were calculated in 0.11s.
2026-01-15 15:25:52,558 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:52,660 - .prody - DEBUG - 10 modes were calculated in 0.10s.
2026-01-15 15:25:52,668 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:52,736 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:52,744 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:52,838 - .prody - DEBUG - 10 modes were calculated in 0.09s.
2026-01-15 15:25:52,852 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:52,915 - .prody - DEBUG - 10 modes were calculated in 0.06s.
2026-01-15 15:25:52,924 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:53,013 - .prody - DEBUG - 10 modes were calculated in 0.09s.
2026-01-15 15:25:53,022 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:53,081 - .prody - DEBUG - 10 modes were calculated in 0.06s.
2026-01-15 15:25:53,094 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:53,225 - .prody - DEBUG - 10 modes were calculated in 0.13s.
2026-01-15 15:25:53,231 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:53,335 - .prody - DEBUG - 10 modes were calculated in 0.10s.
2026-01-15 15:25:53,345 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:53,423 - .prody - DEBUG - 10 modes were calculated in 0.08s.
2026-01-15 15:25:53,430 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:53,485 - .prody - DEBUG - 10 modes were calculated in 0.05s.
2026-01-15 15:25:53,491 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:53,612 - .prody - DEBUG - 10 modes were calculated in 0.12s.
2026-01-15 15:25:53,628 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:53,702 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:53,709 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:53,804 - .prody - DEBUG - 10 modes were calculated in 0.09s.
2026-01-15 15:25:53,815 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:53,888 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:53,896 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:54,003 - .prody - DEBUG - 10 modes were calculated in 0.11s.
2026-01-15 15:25:54,012 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2026-01-15 15:25:54,074 - .prody - DEBUG - 10 modes were calculated in 0.06s.
2026-01-15 15:25:54,081 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:54,133 - .prody - DEBUG - 10 modes were calculated in 0.05s.
2026-01-15 15:25:54,141 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:54,209 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2026-01-15 15:25:54,216 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2026-01-15 15:25:54,277 - .prody - DEBUG - 10 modes were calculated in 0.06s.
2026-01-15 15:25:54,285 - .prody - DEBUG - Kirchhoff was built in 0.00s.

('6t4k', 'DSSPF', 'dssp') Not all feature columns {'auth_asym_id', 'pdbx_PDB_ins_code', 'auth_seq_id'}

In [5]:
predictions

          Allosteric score
pocket2           0.848556
pocket1           0.601409
pocket5           0.004664
pocket7           0.000515
pocket9           0.000385
pocket4           0.000332
pocket3           0.000322
pocket6           0.000169
pocket10          0.000142
pocket8           0.000135

## View

In [6]:
view_pockets(
    clean_pdb,
    pockets={"pocket2": {"color": "green"}, "pocket1": {"color": "blue"}}, # {"pocketn": {"color": ""}}
)

### Optional: view allosteric network pathways

**View the allosteric pathways originating from the predicted pocket towards spatially distant residues in the structure.**

The allosteric network can be chosen between [correlationplus](https://github.com/tekpinar/correlationplus) (Dynamical Cross-Correlation from Elastic Network Models) or ProDy's [Perturbation Response Scanning](http://www.bahargroup.org/prody/prs/). The shortest paths between residues of the source pocket and other spatially distant residues (given a distance threshold) are calculated using [NetworkX](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.shortest_paths.weighted.multi_source_dijkstra.html) with Dijkstra’s algorithm.

In [7]:
view_pockets_pathways(
    clean_pdb, 
    pathways="correlationplus", # or 'prs'
    source_pocket="pocket2", # Source pocket to calculate paths to/from
    pathway_dist_threshold=20, # Minimum distance between residues to calculate paths from
    n_top_pathways=10, # Number of pathways to view in the structure
    pockets={"pocket2": {"color": "green"}}, # {"pocketn": {"color": ""}} # Same dictionary of pockets as above to visualize pockets alongside paths
)

2026-01-15 15:35:30,149 - .prody - WARNING - WARNING Could not find _atom_site_anisotrop in lines.
2026-01-15 15:35:30,150 - .prody - WARNING - WARNING No anisotropic B factors found
2026-01-15 15:35:30,150 - .prody - DEBUG - 1974 atoms and 1 coordinate set(s) were parsed in 0.02s.
2026-01-15 15:35:30,182 - .prody - DEBUG - Hessian was built in 0.03s.
2026-01-15 15:35:31,107 - .prody - DEBUG - 100 modes were calculated in 0.92s.

Pathway #1 (blue): A:LYS:354, A:ALA:449
Pathway #2 (cyan): A:VAL:332, A:LEU:448
Pathway #3 (green): A:ILE:270, A:LEU:353
Pathway #4 (yellow): A:LEU:353, A:HIS:451
Pathway #5 (red): A:TRP:317, A:ALA:371
Pathway #6 (purple): A:LEU:353, A:HIS:453
Pathway #7 (grey): A:ARG:296, A:TRP:317
Pathway #8 (light blue): A:LEU:353, A:HIS:452
Pathway #9 (light cyan): A:ASN:373, A:LEU:483
Pathway #10 (mint green): A:ARG:302, A:LEU:324

### Optional: view a target site

Set an object of the `Site` class passing a modulator molecule (and defining the site around it) or a list of residues. Then visualize it in the structure to assess overlap with predicted pockets (residues of the site will be colored green in the protein cartoon visualization).

<br>

#### With a modulator molecule

In [8]:
# Desired modulator is label_asym_id 'C'
pdb.residues.query("label_asym_id == 'C'")

,label_comp_id,label_asym_id,label_entity_id,label_seq_id,pdbx_PDB_ins_code,auth_seq_id,auth_comp_id,auth_asym_id,pdbx_PDB_model_num,pdbx_label_index,pdbx_sifts_xref_db_name,pdbx_sifts_xref_db_acc,pdbx_sifts_xref_db_num,pdbx_sifts_xref_db_res
2061,4F1,C,3,.,?,602,4F1,A,1,602,?,?,?,?

In [9]:
site = Site(
    pdb, 
    modulator_residues=pdb.residues.query("label_asym_id == 'C'")
)
site

In [10]:
view_pockets_pathways(
    clean_pdb, 
    pathways="correlationplus",
    source_pocket="pocket2", 
    pockets={"pocket2": {"color": "green"}}, # {"pocketn": {"color": ""}} 
    site_residues=site.residues,
    modulator_residues=site.modulator_residues,
)

2026-01-15 15:35:52,987 - .prody - WARNING - WARNING Could not find _atom_site_anisotrop in lines.
2026-01-15 15:35:52,987 - .prody - WARNING - WARNING No anisotropic B factors found
2026-01-15 15:35:52,988 - .prody - DEBUG - 1974 atoms and 1 coordinate set(s) were parsed in 0.02s.

Pathway #1 (blue): A:LYS:354, A:ALA:449
Pathway #2 (cyan): A:VAL:332, A:LEU:448
Pathway #3 (green): A:ILE:270, A:LEU:353
Pathway #4 (yellow): A:LEU:353, A:HIS:451
Pathway #5 (red): A:TRP:317, A:ALA:371
Pathway #6 (purple): A:LEU:353, A:HIS:453
Pathway #7 (grey): A:ARG:296, A:TRP:317
Pathway #8 (light blue): A:LEU:353, A:HIS:452
Pathway #9 (light cyan): A:ASN:373, A:LEU:483
Pathway #10 (mint green): A:ARG:302, A:LEU:324

#### With a list of residues

In [11]:
# List of residue numbers of site
resnums = site.residues.label_seq_id.to_list()
resnums

['73',
 '77',
 '78',
 '80',
 '81',
 '84',
 '85',
 '88',
 '109',
 '110',
 '111',
 '112',
 '113',
 '114',
 '232',
 '235',
 '236',
 '238',
 '239',
 '240',
 '241',
 '243',
 '248',
 '250',
 '251',
 '252',
 '253',
 '254',
 '255',
 '257',
 '258',
 '261',
 '262']

In [12]:
# Site can be defined with a list of residues instead of a modulator
res_site = Site(
    pdb=pdb,
    residues=[{"label_asym_id": "A", "label_seq_id": seqnum} for seqnum in resnums]
)
res_site.residues

,label_comp_id,label_asym_id,label_entity_id,label_seq_id,pdbx_PDB_ins_code,auth_seq_id,auth_comp_id,auth_asym_id,pdbx_PDB_model_num,pdbx_label_index,pdbx_sifts_xref_db_name,pdbx_sifts_xref_db_acc,pdbx_sifts_xref_db_num,pdbx_sifts_xref_db_res
0,TRP,A,1,73,?,317,TRP,A,1,73,UNP,P51449,317,W
1,ALA,A,1,77,?,321,ALA,A,1,77,UNP,P51449,321,A
2,HIS,A,1,78,?,322,HIS,A,1,78,UNP,P51449,322,H
3,LEU,A,1,80,?,324,LEU,A,1,80,UNP,P51449,324,L
4,THR,A,1,81,?,325,THR,A,1,81,UNP,P51449,325,T
5,ILE,A,1,84,?,328,ILE,A,1,84,UNP,P51449,328,I
6,GLN,A,1,85,?,329,GLN,A,1,85,UNP,P51449,329,Q
7,VAL,A,1,88,?,332,VAL,A,1,88,UNP,P51449,332,V
8,LEU,A,1,109,?,353,LEU,A,1,109,UNP,P51449,353,L
9,LYS,A,1,110,?,354,LYS,A,1,110,UNP,P51449,354,K
10,ALA,A,1,111,?,355,ALA,A,1,111,UNP,P51449,355,A
11,GLY,A,1,112,?,356,GLY,A,1,112,UNP,P51449,356,G
12,ALA,A,1,113,?,357,ALA,A,1,113,UNP,P51449,357,A
13,MET,A,1,114,?,358,MET,A,1,114,UNP,P51449,358,M
14,CYS,A,1,232,?,476,CYS,A,1,232,UNP,P51449,476,C
15,HIS,A,1,235,?,479,HIS,A,1,235,UNP,P51449,479,H
16,VAL,A,1,236,?,480,VAL,A,1,236,UNP,P51449,480,V
17,ARG,A,1,238,?,482,ARG,A,1,238,UNP,P51449,482,R
18,LEU,A,1,239,?,483,LEU,A,1,239,UNP,P51449,483,L
19,GLN,A,1,240,?,484,GLN,A,1,240,UNP,P51449,484,Q
20,ILE,A,1,241,?,485,ILE,A,1,241,UNP,P51449,485,I
21,GLN,A,1,243,?,487,GLN,A,1,243,UNP,P51449,487,Q
22,ILE,A,1,248,?,492,ILE,A,1,248,UNP,P51449,492,I
23,VAL,A,1,250,?,494,VAL,A,1,250,UNP,P51449,494,V
24,GLN,A,1,251,?,495,GLN,A,1,251,UNP,P51449,495,Q
25,ALA,A,1,252,?,496,ALA,A,1,252,UNP,P51449,496,A
26,ALA,A,1,253,?,497,ALA,A,1,253,UNP,P51449,497,A
27,PHE,A,1,254,?,498,PHE,A,1,254,UNP,P51449,498,F
28,PRO,A,1,255,?,499,PRO,A,1,255,UNP,P51449,499,P
29,LEU,A,1,257,?,501,LEU,A,1,257,UNP,P51449,501,L
30,TYR,A,1,258,?,502,TYR,A,1,258,UNP,P51449,502,Y
31,LEU,A,1,261,?,505,LEU,A,1,261,UNP,P51449,505,L
32,PHE,A,1,262,?,506,PHE,A,1,262,UNP,P51449,506,F

In [13]:
view_pockets_pathways(
    clean_pdb, 
    pathways="correlationplus",
    source_pocket="pocket2", 
    pockets={"pocket2": {"color": "green"}}, # {"pocketn": {"color": ""}} 
    site_residues=site.residues,
)

2026-01-15 15:36:01,929 - .prody - WARNING - WARNING Could not find _atom_site_anisotrop in lines.
2026-01-15 15:36:01,930 - .prody - WARNING - WARNING No anisotropic B factors found
2026-01-15 15:36:01,930 - .prody - DEBUG - 1974 atoms and 1 coordinate set(s) were parsed in 0.02s.

Pathway #1 (blue): A:LYS:354, A:ALA:449
Pathway #2 (cyan): A:VAL:332, A:LEU:448
Pathway #3 (green): A:ILE:270, A:LEU:353
Pathway #4 (yellow): A:LEU:353, A:HIS:451
Pathway #5 (red): A:TRP:317, A:ALA:371
Pathway #6 (purple): A:LEU:353, A:HIS:453
Pathway #7 (grey): A:ARG:296, A:TRP:317
Pathway #8 (light blue): A:LEU:353, A:HIS:452
Pathway #9 (light cyan): A:ASN:373, A:LEU:483
Pathway #10 (mint green): A:ARG:302, A:LEU:324