- Original ALLO features from DoGSiteScorer cannot be used.
- Highest probability pocket for each PDB is taken as the positive prediction.

<br>

In [1]:
pdbs = ['21du', '22mj', '6s3a', '6vvq', '6z1m', '7e40', '7f8p', '7gqu', '7p2v', '7qpn', '7u4k', '7v39', '7yg5', '7zpe', '8cgw', '8crc', '8f4s', '8fpi', '8jp0', '8qtk', '8uk6', '8v81', '8y6w', '9dol', '9ebs', '9fsj', '9mfs', '9o2m', '9prs', '9oul']

# DoGSiteScorer

In [2]:
import os, requests, json, time

In [3]:
def get_state(location):
    response = requests.get(location)
    return response.status_code, response

In [4]:
def upload_pdb(file_path, max_retries=5, wait_time=5):
    pdb_upload_url = "https://proteins.plus/api/pdb_files_rest"
    headers = {"Accept": "application/json"}
    
    pdb_file = open(file_path, "rb")
    files = {"pdb_file[pathvar]": pdb_file}
    upload_response = requests.post(pdb_upload_url, headers=headers, files=files)
    pdb_file.close()
    
    location = upload_response.json().get("location")

    time.sleep(10)
    status_code, response = get_state(location)

    retries = 0
    while status_code != 200 and retries < max_retries:
        wait = wait_time*(retries+1)
        print("({}) {}: try again after {} seconds".format(file_path, response.json().get("message"), wait))
        time.sleep(wait)
        status_code, response = get_state(location)
        retries += 1

    return response.json().get("id")

In [5]:
def run_dogsite_analysis(pdb_id, max_retries=5, wait_time=30):
    dogsite_url = "https://proteins.plus/api/dogsite_rest"
    headers = {
        "Accept": "application/json",
        "Content-Type": "application/json"
    }
    data = {
        "dogsite": {
            "pdbCode": pdb_id,
            "analysisDetail": "0",
            "bindingSitePredictionGranularity": "1",
            "ligand": "",
            "chain": ""
        }
    }

    upload_response = requests.post(dogsite_url, headers=headers, data=json.dumps(data))
    location = upload_response.json().get("location")
    
    time.sleep(10)
    status_code, response = get_state(location)

    retries = 0
    while status_code != 200 and retries < max_retries:
        wait = wait_time*(retries+1)
        print("({}) {}: try again after {} seconds".format(pdb_id, response.json().get("message"), wait))
        time.sleep(wait)
        status_code, response = get_state(location)
        retries += 1

    return response.json()

In [6]:
def download(url, path):
    response = requests.get(url)
    if response.status_code == 200:
        with open("{}/{}".format(path, url.split("/")[-1]), "wb") as f:
            f.write(response.content)

In [7]:
for pdb in pdbs:
    pdb_path = "../structures/{}.pdb".format(pdb)
    if not os.path.isdir(pdb):
        os.makedirs(pdb)
        pockets = "{}/pockets".format(pdb)
        if not os.path.isdir(pockets):
            os.makedirs(pockets)

        pdb_id = upload_pdb(pdb_path)
        time.sleep(1)        
        result = run_dogsite_analysis(pdb_id)
        
        if result is not None:
            for url in result.get("pockets", []) + result.get("residues", []):
                download(url, pockets)
            
            download(result.get("descriptor_explanation"), pdb)
            download(result.get("result_table"), pdb)

(7e40pdb975e42fb-e345-4a99-ac4d-1ab351f8b959) Job exists and is still in 'processing' state: try again after 30 seconds

(7e40pdb975e42fb-e345-4a99-ac4d-1ab351f8b959) Job exists and is still in 'processing' state: try again after 60 seconds

(7f8ppdb99594846-5015-4f49-b43f-a3f46b97f22c) Job exists and is still in 'processing' state: try again after 30 seconds

(7f8ppdb99594846-5015-4f49-b43f-a3f46b97f22c) Job exists and is still in 'processing' state: try again after 60 seconds

(7u4kpdbb69d7528-74da-4f54-8f89-80c8519cf450) Job exists and is still in 'processing' state: try again after 30 seconds

(7v39pdb7e7915a2-6e16-472b-9309-03974881eaf6) Job exists and is still in 'processing' state: try again after 30 seconds

(8cgwpdb500d2158-5667-46a1-a6b9-a6f52efcbef0) Job exists and is still in 'processing' state: try again after 30 seconds

(8cgwpdb500d2158-5667-46a1-a6b9-a6f52efcbef0) Job exists and is still in 'processing' state: try again after 60 seconds

(9o2mpdb2cf5c333-5a9a-4060-8f44-8bf48f862f4c) Job exists and is still in 'processing' state: try again after 30 seconds

(9o2mpdb2cf5c333-5a9a-4060-8f44-8bf48f862f4c) Job exists and is still in 'processing' state: try again after 60 seconds

## Old vs. new version

In [8]:
import pandas as pd

In [9]:
old = pd.read_csv("allo/src/test_input/AS091022202_3PJG_complex.txt", sep="\t")
old

,name,lig_cov,poc_cov,lig_name,4A_crit,volume,hull,surface,lid,depth,...,I,N,DA,DC,DG,DT,DN,UNK,simpleScore,drugScore
0,AS091022202_3PJG_complex_chains_desc_P_1,0.0000,0.00000,non,0,926.336,1125.44,956.64,168.80,18.40000,...,0,0,0,0,0,0,0,0,0.537801,0.520085
1,AS091022202_3PJG_complex_chains_desc_P_2,0.0000,0.00000,non,0,782.464,917.44,707.52,209.92,29.12320,...,0,0,0,0,0,0,0,0,0.445098,0.417353
2,AS091022202_3PJG_complex_chains_desc_P_3,23.7288,7.66129,UGA_A_90,1,555.520,659.52,551.68,107.84,16.04490,...,0,0,0,0,0,0,0,0,0.404041,0.363490
3,AS091022202_3PJG_complex_chains_desc_P_4,0.0000,0.00000,non,0,285.312,419.20,406.24,12.96,13.93700,...,0,0,0,0,0,0,0,0,0.282709,0.100086
4,AS091022202_3PJG_complex_chains_desc_P_5,0.0000,0.00000,non,0,251.328,356.96,351.20,5.76,12.65540,...,0,0,0,0,0,0,0,0,0.365878,0.202703
5,AS091022202_3PJG_complex_chains_desc_P_6,0.0000,0.00000,non,0,148.544,198.24,152.32,45.92,7.16659,...,0,0,0,0,0,0,0,0,0.256271,0.420902
6,AS091022202_3PJG_complex_chains_desc_P_7,42.3729,85.42170,UGA_A_90,1,131.264,178.08,143.20,34.88,9.55824,...,0,0,0,0,0,0,0,0,0.532231,0.652536
7,AS091022202_3PJG_complex_chains_desc_P_8,0.0000,0.00000,non,0,116.224,169.76,148.96,20.80,8.88144,...,0,0,0,0,0,0,0,0,0.053244,0.447991
8,AS091022202_3PJG_complex_chains_desc_P_9,0.0000,0.00000,non,0,115.776,168.00,120.48,47.52,8.40952,...,0,0,0,0,0,0,0,0,0.000000,0.266754
9,AS091022202_3PJG_complex_chains_desc_P_10,0.0000,0.00000,non,0,113.344,173.44,152.64,20.80,9.67471,...,0,0,0,0,0,0,0,0,0.231786,0.324773
10,AS091022202_3PJG_complex_chains_desc_P_11,0.0000,0.00000,non,0,100.864,196.96,196.48,0.48,10.83700,...,0,0,0,0,0,0,0,0,0.485441,0.163130

In [10]:
new = pd.read_csv("7gqu/7gqupdb1eccfc79-6d92-4241-bb30-60d0587ea079_desc.txt", sep="\t")
new

,name,lig_cov,poc_cov,lig_name,volume,enclosure,surface,depth,surf/vol,lid/hull,...,MET,PHE,PRO,SER,THR,TRP,TYR,VAL,simpleScore,drugScore
0,P_0,0.0,0.0,NaN,1516.22,0.06,1705.19,21.71,1.124632,-,...,3,4,0,4,3,0,4,1,0.65,0.797680
1,P_1,0.0,0.0,NaN,343.30,0.05,404.34,12.22,1.177804,-,...,3,1,0,0,3,0,2,1,0.17,0.577353
2,P_2,0.0,0.0,NaN,336.70,0.04,570.81,12.87,1.695307,-,...,0,2,1,1,1,0,2,2,0.19,0.568479
3,P_3,0.0,0.0,NaN,313.41,0.12,459.98,15.46,1.467662,-,...,1,1,2,1,1,0,2,0,0.18,0.649976
4,P_4,0.0,0.0,NaN,182.34,0.24,397.51,11.11,2.180048,-,...,0,1,2,1,0,2,0,1,0.02,0.411775
5,P_5,0.0,0.0,NaN,173.31,0.18,362.55,12.36,2.091916,-,...,0,2,0,2,1,0,0,0,0.00,0.416132
6,P_6,0.0,0.0,NaN,148.42,0.18,254.42,8.37,1.714189,-,...,1,0,1,1,0,0,1,0,0.01,0.261178
7,P_7,0.0,0.0,NaN,144.26,0.23,245.32,8.85,1.700541,-,...,0,1,0,2,0,0,1,0,0.00,0.269649
8,P_8,0.0,0.0,NaN,136.13,0.16,274.20,11.38,2.014251,-,...,1,1,0,0,0,0,0,0,0.00,0.370560
9,P_9,0.0,0.0,NaN,127.81,0.25,242.80,6.57,1.899695,-,...,0,0,0,0,1,0,0,3,0.00,0.199447
10,P_10,0.0,0.0,NaN,123.65,0.15,349.51,7.74,2.826607,-,...,1,0,2,0,0,0,0,1,0.00,0.227560
11,P_11,0.0,0.0,NaN,113.66,0.00,114.27,11.58,1.005367,-,...,1,0,0,0,0,0,1,2,0.00,0.375892

### Different columns

In [11]:
set(new.columns) - set(old.columns)

{'enclosure', 'hydrophobic_interactions'}

In [12]:
new[list(set(new.columns) - set(old.columns))]

    hydrophobic_interactions  enclosure
0                         94       0.06
1                         19       0.05
2                         28       0.04
3                         27       0.12
4                         17       0.24
5                         10       0.18
6                         12       0.18
7                          7       0.23
8                         13       0.16
9                          7       0.25
10                        27       0.15
11                         3       0.00

In [13]:
set(old.columns) - set(new.columns)

{'4A_crit',
 'A',
 'C',
 'CSO',
 'DA',
 'DC',
 'DG',
 'DN',
 'DT',
 'G',
 'I',
 'N',
 'U',
 'UNK',
 'aromat',
 'hull',
 'lid',
 'sumAA'}

In [14]:
old[sorted(set(old.columns) - set(new.columns), key=lambda x: old.columns.tolist().index(x))]

,4A_crit,hull,lid,aromat,sumAA,CSO,A,C,G,U,I,N,DA,DC,DG,DT,DN,UNK
0,0,1125.44,168.80,17,40,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,917.44,209.92,9,36,0,0,0,0,0,0,0,0,0,0,0,0,0
2,1,659.52,107.84,9,27,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,419.20,12.96,4,22,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,356.96,5.76,15,19,0,0,0,0,0,0,0,0,0,0,0,0,0
5,0,198.24,45.92,14,8,0,0,0,0,0,0,0,0,0,0,0,0,0
6,1,178.08,34.88,10,6,0,0,0,0,0,0,0,0,0,0,0,0,0
7,0,169.76,20.80,3,10,0,0,0,0,0,0,0,0,0,0,0,0,0
8,0,168.00,47.52,0,10,0,0,0,0,0,0,0,0,0,0,0,0,0
9,0,173.44,20.80,4,10,0,0,0,0,0,0,0,0,0,0,0,0,0
10,0,196.96,0.48,6,17,0,0,0,0,0,0,0,0,0,0,0,0,0

**4A_crit is part of the labelling system of ALLO and must be kept/added.**

<br>

### Missing data in new output

In [15]:
new.dtypes.sort_values(ascending=False)

name                         object
ellVol                       object
lid/hull                     object
apolarAA                    float64
posAA                       float64
simpleScore                 float64
hydrophobicity              float64
ell b/a                     float64
ell c/a                     float64
surf/vol                    float64
depth                       float64
surface                     float64
enclosure                   float64
volume                      float64
lig_name                    float64
poc_cov                     float64
lig_cov                     float64
polarAA                     float64
drugScore                   float64
negAA                       float64
accept                        int64
VAL                           int64
TYR                           int64
TRP                           int64
THR                           int64
SER                           int64
PRO                           int64
PHE                           int64
MET                           int64
LYS                           int64
LEU                           int64
ILE                           int64
HIS                           int64
siteAtms                      int64
ASN                           int64
ARG                           int64
hydrophobic_interactions      int64
GLY                           int64
metal                         int64
Cs                            int64
Ns                            int64
Os                            int64
Ss                            int64
Xs                            int64
GLU                           int64
GLN                           int64
CYS                           int64
ASP                           int64
ALA                           int64
donor                         int64
dtype: object

In [16]:
new[["lid/hull", "ellVol"]]

   lid/hull ellVol
0         -      -
1         -      -
2         -      -
3         -      -
4         -      -
5         -      -
6         -      -
7         -      -
8         -      -
9         -      -
10        -      -
11        -      -

### Patch

- Create a fake new aplc.tsv to train the neural network using only the features that are available.
- Process all outputs to remove features not available in old output

#### Training data

In [17]:
if not os.path.isfile("allo/data/aplc_original.tsv"):
    os.system("mv allo/data/aplc.tsv allo/data/aplc_original.tsv")

In [18]:
aplc = pd.read_csv("allo/data/aplc_original.tsv", sep="\t")
aplc

,name,lig_cov,poc_cov,lig_name,4A_crit,volume,hull,surface,lid,depth,...,I,N,DA,DC,DG,DT,DN,UNK,simpleScore,drugScore
0,AS001000501_3UO9_complex_chains_desc_P_1,0.00000,0.000000,non,0,661.207,749.567,678.2210,71.346400,24.90670,...,0,0,0,0,0,0,0,0,0.468934,0.271149
1,AS001000501_3UO9_complex_chains_desc_P_2,0.00000,0.000000,non,0,492.799,558.164,434.6690,123.495000,17.28740,...,0,0,0,0,0,0,0,0,0.262105,0.215701
2,AS001000501_3UO9_complex_chains_desc_P_3,88.13560,72.303800,04A_B_2,1,480.683,558.164,502.8630,55.300700,20.22080,...,0,0,0,0,0,0,0,0,0.593739,0.695285
3,AS001000501_3UO9_complex_chains_desc_P_4,0.00000,0.000000,non,0,463.811,565.327,453.2930,112.034000,20.41120,...,0,0,0,0,0,0,0,0,0.285292,0.254757
4,AS001000501_3UO9_complex_chains_desc_P_5,0.00000,0.000000,non,0,398.013,519.196,388.2510,130.945000,20.24210,...,0,0,0,0,0,0,0,0,0.260897,0.147678
5,AS001000501_3UO9_complex_chains_desc_P_6,0.00000,0.000000,non,0,381.601,493.694,428.6520,65.042700,21.60460,...,0,0,0,0,0,0,0,0,0.386060,0.136666
6,AS001000501_3UO9_complex_chains_desc_P_7,0.00000,0.000000,non,0,373.626,436.102,369.9130,66.188900,17.80990,...,0,0,0,0,0,0,0,0,0.510129,0.285342
7,AS001000501_3UO9_complex_chains_desc_P_8,0.00000,0.000000,non,0,373.166,496.273,412.3190,83.953800,22.42460,...,0,0,0,0,0,0,0,0,0.391934,0.178084
8,AS001000501_3UO9_complex_chains_desc_P_9,0.00000,0.000000,non,0,353.380,476.789,396.8470,79.942400,24.36580,...,0,0,0,0,0,0,0,0,0.397897,0.088986
9,AS001000501_3UO9_complex_chains_desc_P_10,3.38983,0.591447,04A_B_2,0,337.122,408.594,303.1510,105.444000,17.75350,...,0,0,0,0,0,0,0,0,0.144927,0.317734
10,AS001000501_3UO9_complex_chains_desc_P_11,0.00000,0.000000,non,0,311.815,412.319,349.8550,62.464000,18.27830,...,0,0,0,0,0,0,0,0,0.380474,0.129707
11,AS001000501_3UO9_complex_chains_desc_P_12,0.00000,0.000000,non,0,246.170,301.432,250.4290,51.002700,11.43060,...,0,0,0,0,0,0,0,0,0.039693,0.478687
12,AS001000501_3UO9_complex_chains_desc_P_13,0.00000,0.000000,non,0,241.875,292.549,198.8530,93.695900,13.57350,...,0,0,0,0,0,0,0,0,0.000000,0.333766
13,AS001000501_3UO9_complex_chains_desc_P_14,0.00000,0.000000,non,0,236.200,284.813,229.7990,55.014100,12.73490,...,0,0,0,0,0,0,0,0,0.000000,0.630971
14,AS001000501_3UO9_complex_chains_desc_P_15,0.00000,0.000000,non,0,234.973,294.841,243.2660,51.575700,11.89730,...,0,0,0,0,0,0,0,0,0.145671,0.234008
15,AS001000501_3UO9_complex_chains_desc_P_16,0.00000,0.000000,non,0,223.317,289.111,206.0160,83.094300,16.35910,...,0,0,0,0,0,0,0,0,0.165784,0.239326
16,AS001000501_3UO9_complex_chains_desc_P_17,0.00000,0.000000,non,0,193.561,224.068,174.2110,49.856600,9.94251,...,0,0,0,0,0,0,0,0,0.000000,0.172415
17,AS001000501_3UO9_complex_chains_desc_P_18,0.00000,0.000000,non,0,191.414,221.489,160.4580,61.031300,10.22660,...,0,0,0,0,0,0,0,0,0.000000,0.186452
18,AS001000501_3UO9_complex_chains_desc_P_19,0.00000,0.000000,non,0,182.672,228.366,156.1600,72.206000,10.99620,...,0,0,0,0,0,0,0,0,0.091872,0.293654
19,AS001000501_3UO9_complex_chains_desc_P_20,0.00000,0.000000,non,0,178.837,237.248,205.7300,31.518500,13.13360,...,0,0,0,0,0,0,0,0,0.000000,0.276817
20,AS001000501_3UO9_complex_chains_desc_P_21,0.00000,0.000000,non,0,170.862,191.690,138.9680,52.721900,8.36145,...,0,0,0,0,0,0,0,0,0.025899,0.084847
21,AS001000501_3UO9_complex_chains_desc_P_22,0.00000,0.000000,non,0,164.113,196.847,150.7160,46.131600,9.88470,...,0,0,0,0,0,0,0,0,0.117322,0.291195
22,AS001000501_3UO9_complex_chains_desc_P_23,0.00000,0.000000,non,0,158.745,201.145,143.5520,57.592900,9.16263,...,0,0,0,0,0,0,0,0,0.000000,0.542819
23,AS001000501_3UO9_complex_chains_desc_P_24,0.00000,0.000000,non,0,148.469,247.850,246.9910,0.859596,13.72050,...,0,0,0,0,0,0,0,0,0.349654,0.070811
24,AS001000501_3UO9_complex_chains_desc_P_25,0.00000,0.000000,non,0,137.886,232.950,232.0910,0.859596,14.50220,...,0,0,0,0,0,0,0,0,0.293905,0.061666
25,AS001000501_3UO9_complex_chains_desc_P_26,0.00000,0.000000,non,0,134.665,171.919,108.3090,63.610100,8.61463,...,0,0,0,0,0,0,0,0,0.044748,0.500000
26,AS001000501_3UO9_complex_chains_desc_P_27,0.00000,0.000000,non,0,123.468,172.779,147.2770,25.501300,9.85567,...,0,0,0,0,0,0,0,0,0.055295,0.301519
27,AS001000501_3UO9_complex_chains_desc_P_28,0.00000,0.000000,non,0,122.395,156.160,112.6070,43.552800,8.77936,...,0,0,0,0,0,0,0,0,0.000000,0.243930
28,AS001000501_3UO9_complex_chains_desc_P_29,0.00000,0.000000,non,0,120.554,161.604,133.8100,27.793600,7.49401,...,0,0,0,0,0,0,0,0,0.135139,0.346295
29,AS001000501_3UO9_complex_chains_desc_P_30,0.00000,0.000000,non,0,114.419,163.323,150.7160,12.607400,9.25597,...,0,0,0,0,0,0,0,0,0.000000,0.795132
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1845,AS099025701_2BE9_complex_chains_desc_P_4,0.00000,0.000000,non,0,150.144,195.200,160.0000,35.200000,7.28835,...,0,0,0,0,0,0,0,0,0.085488,0.280380
1846,AS099025701_2BE9_complex_chains_desc_P_5,0.00000,0.000000,non,0,121.088,198.400,155.0400,43.360000,11.74390,...,0,0,0,0,0,0,0,0,0.042339,0.628926
1847,AS105026301_1NJJ_complex_chains_desc_P_1,0.00000,0.000000,non,0,1464.060,1811.380,1533.3300,278.051000,31.84040,...,0,0,0,0,0,0,0,0,0.797738,0.826298
1848,AS105026301_1NJJ_complex_chains_desc_P_2,0.00000,0.000000,non,0,1242.680,1618.440,1401.4200,217.011000,31.46320,...,0,0,0,0,0,0,0,0,0.716697,0.703852
1849,AS105026301_1NJJ_complex_chains_desc_P_3,13.51350,4.110920,GET_B_60,0,694.727,785.244,646.6040,138.641000,17.88930,...,0,0,0,0,0,0,0,0,0.641468,0.794766
1850,AS105026301_1NJJ_complex_chains_desc_P_4,0.00000,0.000000,non,0,660.168,782.934,654.1140,128.820000,18.95040,...,0,0,0,0,0,0,0,0,0.466302,0.532533
1851,AS105026301_1NJJ_complex_chains_desc_P_5,51.35140,41.809500,GET_B_60,1,409.045,522.790,450.7740,72.016000,16.66910,...,0,0,0,0,0,0,0,0,0.198042,0.351657
1852,AS105026301_1NJJ_complex_chains_desc_P_6,0.00000,0.000000,non,0,408.707,396.858,277.6660,119.192000,13.89030,...,0,0,0,0,0,0,0,0,0.373206,0.464208
1853,AS105026301_1NJJ_complex_chains_desc_P_7,0.00000,0.000000,non,0,353.954,374.522,268.8090,105.713000,14.54710,...,0,0,0,0,0,0,0,0,0.254280,0.313779
1854,AS105026301_1NJJ_complex_chains_desc_P_8,0.00000,0.000000,non,0,312.466,358.155,297.1140,61.040300,12.76330,...,0,0,0,0,0,0,0,0,0.055750,0.526015
1855,AS105026301_1NJJ_complex_chains_desc_P_9,0.00000,0.000000,non,1,239.208,342.750,255.1370,87.613100,17.54150,...,0,0,0,0,0,0,0,0,0.336884,0.212688
1856,AS105026301_1NJJ_complex_chains_desc_P_10,0.00000,0.000000,non,0,199.833,248.975,215.0850,33.889900,10.35630,...,0,0,0,0,0,0,0,0,0.136278,0.296809
1857,AS105026301_1NJJ_complex_chains_desc_P_11,0.00000,0.000000,non,0,188.088,224.713,170.7970,53.915800,9.05698,...,0,0,0,0,0,0,0,0,0.000000,0.030319
1858,AS105026301_1NJJ_complex_chains_desc_P_12,0.00000,0.000000,non,0,183.863,223.365,159.6290,63.736100,10.97910,...,0,0,0,0,0,0,0,0,0.218507,0.322358
1859,AS105026301_1NJJ_complex_chains_desc_P_13,0.00000,0.000000,non,0,175.921,202.569,129.2050,73.363900,9.18366,...,0,0,0,0,0,0,0,0,0.144148,0.045159
1860,AS105026301_1NJJ_complex_chains_desc_P_14,0.00000,0.000000,non,0,143.136,191.208,155.2000,36.008000,9.39099,...,0,0,0,0,0,0,0,0,0.072642,0.478421
1861,AS105026301_1NJJ_complex_chains_desc_P_15,0.00000,0.000000,non,0,142.714,182.351,150.3860,31.964300,7.66353,...,0,0,0,0,0,0,0,0,0.000000,0.236622
1862,AS105026301_1NJJ_complex_chains_desc_P_16,0.00000,0.000000,non,0,141.953,178.692,114.1860,64.506300,9.70361,...,0,0,0,0,0,0,0,0,0.245482,0.470756
1863,AS105026301_1NJJ_complex_chains_desc_P_17,0.00000,0.000000,non,0,134.433,180.618,117.6520,62.965900,7.68861,...,0,0,0,0,0,0,0,0,0.371046,0.772754
1864,AS105026301_1NJJ_complex_chains_desc_P_18,0.00000,0.000000,non,0,130.969,178.307,117.6520,60.655200,11.44280,...,0,0,0,0,0,0,0,0,0.139698,0.214977
1865,AS105026301_1NJJ_complex_chains_desc_P_19,0.00000,0.000000,non,0,130.377,159.437,85.8801,73.556500,8.69912,...,0,0,0,0,0,0,0,0,0.000000,0.011404
1866,AS105026301_1NJJ_complex_chains_desc_P_20,0.00000,0.000000,non,0,116.098,164.250,136.5220,27.728100,8.78721,...,0,0,0,0,0,0,0,0,0.348402,0.365270
1867,AS105026301_1NJJ_complex_chains_desc_P_21,0.00000,0.000000,non,0,109.760,149.424,108.6020,40.821900,8.52019,...,0,0,0,0,0,0,0,0,0.489803,0.914104
1868,AS105026301_1NJJ_complex_chains_desc_P_22,0.00000,0.000000,non,0,109.591,147.691,108.4090,39.281500,8.34897,...,0,0,0,0,0,0,0,0,0.115417,0.277056
1869,AS105026301_1NJJ_complex_chains_desc_P_23,0.00000,0.000000,non,0,105.451,139.796,83.1843,56.611500,8.78721,...,0,0,0,0,0,0,0,0,0.000000,0.032651
1870,AS105026301_1NJJ_complex_chains_desc_P_24,0.00000,0.000000,non,0,100.297,156.356,118.4220,37.933600,7.66353,...,0,0,0,0,0,0,0,0,0.000000,0.833732
1871,AS107027301_2VPR_complex_chains_desc_P_1,98.11320,27.694000,TDC_A_12,1,1519.230,1895.840,1644.0000,251.840000,30.29720,...,0,0,0,0,0,0,0,0,0.941930,0.927478
1872,AS107027301_2VPR_complex_chains_desc_P_2,0.00000,0.000000,non,0,289.536,385.120,309.1200,76.000000,15.01470,...,0,0,0,0,0,0,0,0,0.138724,0.246442
1873,AS107027301_2VPR_complex_chains_desc_P_3,0.00000,0.000000,non,0,187.904,280.800,237.4400,43.360000,10.51480,...,0,0,0,0,0,0,0,0,0.000000,0.419828
1874,AS107027301_2VPR_complex_chains_desc_P_4,0.00000,0.000000,non,0,117.568,166.560,127.3600,39.200000,7.76660,...,0,0,0,0,0,0,0,0,0.000000,0.010835

In [19]:
assert set(aplc.columns) == set(old.columns)

In [20]:
columns = [c for c in aplc.columns if c not in set(
    list( set(new.columns) - set(aplc.columns) )
    + list( set(aplc.columns) - set(new.columns) )
    + ["lid/hull", "ellVol"]
) - {"4A_crit",}]
columns

['name',
 'lig_cov',
 'poc_cov',
 'lig_name',
 '4A_crit',
 'volume',
 'surface',
 'depth',
 'surf/vol',
 'ell c/a',
 'ell b/a',
 'siteAtms',
 'accept',
 'donor',
 'hydrophobicity',
 'metal',
 'Cs',
 'Ns',
 'Os',
 'Ss',
 'Xs',
 'negAA',
 'posAA',
 'polarAA',
 'apolarAA',
 'ALA',
 'ARG',
 'ASN',
 'ASP',
 'CYS',
 'GLN',
 'GLU',
 'GLY',
 'HIS',
 'ILE',
 'LEU',
 'LYS',
 'MET',
 'PHE',
 'PRO',
 'SER',
 'THR',
 'TRP',
 'TYR',
 'VAL',
 'simpleScore',
 'drugScore']

In [21]:
fake_aplc = aplc[columns]
fake_aplc

,name,lig_cov,poc_cov,lig_name,4A_crit,volume,surface,depth,surf/vol,ell c/a,...,MET,PHE,PRO,SER,THR,TRP,TYR,VAL,simpleScore,drugScore
0,AS001000501_3UO9_complex_chains_desc_P_1,0.00000,0.000000,non,0,661.207,678.2210,24.90670,0.549061,0.120963,...,2,3,2,5,0,0,2,1,0.468934,0.271149
1,AS001000501_3UO9_complex_chains_desc_P_2,0.00000,0.000000,non,0,492.799,434.6690,17.28740,0.472144,0.117456,...,2,1,1,4,0,0,1,1,0.262105,0.215701
2,AS001000501_3UO9_complex_chains_desc_P_3,88.13560,72.303800,04A_B_2,1,480.683,502.8630,20.22080,0.559987,0.081842,...,0,2,0,0,0,0,2,0,0.593739,0.695285
3,AS001000501_3UO9_complex_chains_desc_P_4,0.00000,0.000000,non,0,463.811,453.2930,20.41120,0.523148,0.093727,...,2,2,2,3,0,0,0,2,0.285292,0.254757
4,AS001000501_3UO9_complex_chains_desc_P_5,0.00000,0.000000,non,0,398.013,388.2510,20.24210,0.522158,0.090831,...,0,1,3,1,0,0,0,3,0.260897,0.147678
5,AS001000501_3UO9_complex_chains_desc_P_6,0.00000,0.000000,non,0,381.601,428.6520,21.60460,0.601286,0.055553,...,2,0,0,1,3,0,0,2,0.386060,0.136666
6,AS001000501_3UO9_complex_chains_desc_P_7,0.00000,0.000000,non,0,373.626,369.9130,17.80990,0.529967,0.145510,...,0,2,2,1,0,0,0,0,0.510129,0.285342
7,AS001000501_3UO9_complex_chains_desc_P_8,0.00000,0.000000,non,0,373.166,412.3190,22.42460,0.591451,0.048928,...,0,2,2,1,1,1,1,2,0.391934,0.178084
8,AS001000501_3UO9_complex_chains_desc_P_9,0.00000,0.000000,non,0,353.380,396.8470,24.36580,0.601128,0.032981,...,0,2,3,1,1,1,0,2,0.397897,0.088986
9,AS001000501_3UO9_complex_chains_desc_P_10,3.38983,0.591447,04A_B_2,0,337.122,303.1510,17.75350,0.481347,0.102600,...,0,1,1,1,0,0,0,1,0.144927,0.317734
10,AS001000501_3UO9_complex_chains_desc_P_11,0.00000,0.000000,non,0,311.815,349.8550,18.27830,0.600590,0.101519,...,0,4,2,1,0,0,0,0,0.380474,0.129707
11,AS001000501_3UO9_complex_chains_desc_P_12,0.00000,0.000000,non,0,246.170,250.4290,11.43060,0.544548,0.260425,...,0,1,1,1,2,0,0,1,0.039693,0.478687
12,AS001000501_3UO9_complex_chains_desc_P_13,0.00000,0.000000,non,0,241.875,198.8530,13.57350,0.440076,0.154202,...,0,0,1,1,0,0,0,1,0.000000,0.333766
13,AS001000501_3UO9_complex_chains_desc_P_14,0.00000,0.000000,non,0,236.200,229.7990,12.73490,0.520779,0.190725,...,0,0,1,1,2,0,0,1,0.000000,0.630971
14,AS001000501_3UO9_complex_chains_desc_P_15,0.00000,0.000000,non,0,234.973,243.2660,11.89730,0.554178,0.211010,...,1,3,1,1,1,0,0,0,0.145671,0.234008
15,AS001000501_3UO9_complex_chains_desc_P_16,0.00000,0.000000,non,0,223.317,206.0160,16.35910,0.493819,0.055682,...,1,0,1,1,1,0,0,0,0.165784,0.239326
16,AS001000501_3UO9_complex_chains_desc_P_17,0.00000,0.000000,non,0,193.561,174.2110,9.94251,0.481775,0.402688,...,0,1,0,1,0,0,1,0,0.000000,0.172415
17,AS001000501_3UO9_complex_chains_desc_P_18,0.00000,0.000000,non,0,191.414,160.4580,10.22660,0.448718,0.407645,...,0,1,0,2,0,0,1,0,0.000000,0.186452
18,AS001000501_3UO9_complex_chains_desc_P_19,0.00000,0.000000,non,0,182.672,156.1600,10.99620,0.457599,0.152992,...,1,1,0,1,1,0,0,0,0.091872,0.293654
19,AS001000501_3UO9_complex_chains_desc_P_20,0.00000,0.000000,non,0,178.837,205.7300,13.13360,0.615780,0.177663,...,1,3,1,1,1,0,0,1,0.000000,0.276817
20,AS001000501_3UO9_complex_chains_desc_P_21,0.00000,0.000000,non,0,170.862,138.9680,8.36145,0.435368,0.486332,...,0,1,1,0,1,0,0,0,0.025899,0.084847
21,AS001000501_3UO9_complex_chains_desc_P_22,0.00000,0.000000,non,0,164.113,150.7160,9.88470,0.491589,0.328606,...,1,1,1,0,1,0,0,0,0.117322,0.291195
22,AS001000501_3UO9_complex_chains_desc_P_23,0.00000,0.000000,non,0,158.745,143.5520,9.16263,0.484058,0.211758,...,1,1,0,1,2,0,0,0,0.000000,0.542819
23,AS001000501_3UO9_complex_chains_desc_P_24,0.00000,0.000000,non,0,148.469,246.9910,13.72050,0.890496,0.095816,...,1,1,0,1,1,0,1,2,0.349654,0.070811
24,AS001000501_3UO9_complex_chains_desc_P_25,0.00000,0.000000,non,0,137.886,232.0910,14.50220,0.901001,0.073350,...,0,0,0,1,0,0,1,2,0.293905,0.061666
25,AS001000501_3UO9_complex_chains_desc_P_26,0.00000,0.000000,non,0,134.665,108.3090,8.61463,0.430524,0.211774,...,0,0,2,0,0,0,0,1,0.044748,0.500000
26,AS001000501_3UO9_complex_chains_desc_P_27,0.00000,0.000000,non,0,123.468,147.2770,9.85567,0.638509,0.202193,...,0,1,0,0,2,0,0,0,0.055295,0.301519
27,AS001000501_3UO9_complex_chains_desc_P_28,0.00000,0.000000,non,0,122.395,112.6070,8.77936,0.492481,0.384978,...,0,0,0,1,1,0,1,0,0.000000,0.243930
28,AS001000501_3UO9_complex_chains_desc_P_29,0.00000,0.000000,non,0,120.554,133.8100,7.49401,0.594148,0.536827,...,0,1,0,0,2,0,0,0,0.135139,0.346295
29,AS001000501_3UO9_complex_chains_desc_P_30,0.00000,0.000000,non,0,114.419,150.7160,9.25597,0.705094,0.214443,...,0,0,1,1,0,0,0,0,0.000000,0.795132
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1845,AS099025701_2BE9_complex_chains_desc_P_4,0.00000,0.000000,non,0,150.144,160.0000,7.28835,0.426257,0.601671,...,0,0,0,1,0,0,0,1,0.085488,0.280380
1846,AS099025701_2BE9_complex_chains_desc_P_5,0.00000,0.000000,non,0,121.088,155.0400,11.74390,0.512156,0.108095,...,1,0,0,1,1,0,0,0,0.042339,0.628926
1847,AS105026301_1NJJ_complex_chains_desc_P_1,0.00000,0.000000,non,0,1464.060,1533.3300,31.84040,0.459572,0.136990,...,0,4,5,5,4,1,5,8,0.797738,0.826298
1848,AS105026301_1NJJ_complex_chains_desc_P_2,0.00000,0.000000,non,0,1242.680,1401.4200,31.46320,0.494866,0.294893,...,1,4,3,4,5,1,5,7,0.716697,0.703852
1849,AS105026301_1NJJ_complex_chains_desc_P_3,13.51350,4.110920,GET_B_60,0,694.727,646.6040,17.88930,0.408416,0.060362,...,1,3,3,2,2,0,0,2,0.641468,0.794766
1850,AS105026301_1NJJ_complex_chains_desc_P_4,0.00000,0.000000,non,0,660.168,654.1140,18.95040,0.434788,0.057310,...,1,3,1,2,3,0,1,3,0.466302,0.532533
1851,AS105026301_1NJJ_complex_chains_desc_P_5,51.35140,41.809500,GET_B_60,1,409.045,450.7740,16.66910,0.483578,0.097851,...,0,0,2,1,2,0,0,2,0.198042,0.351657
1852,AS105026301_1NJJ_complex_chains_desc_P_6,0.00000,0.000000,non,0,408.707,277.6660,13.89030,0.298119,0.157479,...,1,1,0,0,0,0,0,3,0.373206,0.464208
1853,AS105026301_1NJJ_complex_chains_desc_P_7,0.00000,0.000000,non,0,353.954,268.8090,14.54710,0.333254,0.154078,...,1,1,0,0,0,0,1,3,0.254280,0.313779
1854,AS105026301_1NJJ_complex_chains_desc_P_8,0.00000,0.000000,non,0,312.466,297.1140,12.76330,0.417253,0.187072,...,0,1,1,1,2,0,1,0,0.055750,0.526015
1855,AS105026301_1NJJ_complex_chains_desc_P_9,0.00000,0.000000,non,1,239.208,255.1370,17.54150,0.468032,0.055789,...,1,0,4,0,0,1,2,0,0.336884,0.212688
1856,AS105026301_1NJJ_complex_chains_desc_P_10,0.00000,0.000000,non,0,199.833,215.0850,10.35630,0.472304,0.433239,...,0,1,1,0,2,0,1,0,0.136278,0.296809
1857,AS105026301_1NJJ_complex_chains_desc_P_11,0.00000,0.000000,non,0,188.088,170.7970,9.05698,0.398473,0.424725,...,0,0,0,1,0,0,0,2,0.000000,0.030319
1858,AS105026301_1NJJ_complex_chains_desc_P_12,0.00000,0.000000,non,0,183.863,159.6290,10.97910,0.380974,0.239081,...,1,2,1,0,1,0,0,0,0.218507,0.322358
1859,AS105026301_1NJJ_complex_chains_desc_P_13,0.00000,0.000000,non,0,175.921,129.2050,9.18366,0.322286,0.272679,...,0,0,1,0,2,0,0,0,0.144148,0.045159
1860,AS105026301_1NJJ_complex_chains_desc_P_14,0.00000,0.000000,non,0,143.136,155.2000,9.39099,0.475797,0.206103,...,1,2,2,0,0,0,0,0,0.072642,0.478421
1861,AS105026301_1NJJ_complex_chains_desc_P_15,0.00000,0.000000,non,0,142.714,150.3860,7.66353,0.462404,0.409359,...,0,0,0,1,0,0,0,2,0.000000,0.236622
1862,AS105026301_1NJJ_complex_chains_desc_P_16,0.00000,0.000000,non,0,141.953,114.1860,9.70361,0.352976,0.200870,...,0,0,1,0,0,0,1,3,0.245482,0.470756
1863,AS105026301_1NJJ_complex_chains_desc_P_17,0.00000,0.000000,non,0,134.433,117.6520,7.68861,0.384035,0.202825,...,0,0,4,0,0,0,2,0,0.371046,0.772754
1864,AS105026301_1NJJ_complex_chains_desc_P_18,0.00000,0.000000,non,0,130.969,117.6520,11.44280,0.394194,0.101296,...,0,1,1,0,1,1,1,0,0.139698,0.214977
1865,AS105026301_1NJJ_complex_chains_desc_P_19,0.00000,0.000000,non,0,130.377,85.8801,8.69912,0.289047,0.306953,...,0,0,0,0,0,0,0,1,0.000000,0.011404
1866,AS105026301_1NJJ_complex_chains_desc_P_20,0.00000,0.000000,non,0,116.098,136.5220,8.78721,0.516012,0.517090,...,0,2,0,0,0,0,2,2,0.348402,0.365270
1867,AS105026301_1NJJ_complex_chains_desc_P_21,0.00000,0.000000,non,0,109.760,108.6020,8.52019,0.434180,0.362392,...,0,2,0,0,0,0,1,1,0.489803,0.914104
1868,AS105026301_1NJJ_complex_chains_desc_P_22,0.00000,0.000000,non,0,109.591,108.4090,8.34897,0.434079,0.274254,...,0,1,1,2,1,0,0,1,0.115417,0.277056
1869,AS105026301_1NJJ_complex_chains_desc_P_23,0.00000,0.000000,non,0,105.451,83.1843,8.78721,0.346154,0.338573,...,0,2,0,1,1,0,0,0,0.000000,0.032651
1870,AS105026301_1NJJ_complex_chains_desc_P_24,0.00000,0.000000,non,0,100.297,118.4220,7.66353,0.518113,0.259348,...,0,0,2,0,2,1,1,1,0.000000,0.833732
1871,AS107027301_2VPR_complex_chains_desc_P_1,98.11320,27.694000,TDC_A_12,1,1519.230,1644.0000,30.29720,0.432850,0.268145,...,2,4,1,6,3,1,2,3,0.941930,0.927478
1872,AS107027301_2VPR_complex_chains_desc_P_2,0.00000,0.000000,non,0,289.536,309.1200,15.01470,0.427056,0.138384,...,1,2,0,1,1,0,0,0,0.138724,0.246442
1873,AS107027301_2VPR_complex_chains_desc_P_3,0.00000,0.000000,non,0,187.904,237.4400,10.51480,0.505450,0.198598,...,1,0,0,0,0,0,1,1,0.000000,0.419828
1874,AS107027301_2VPR_complex_chains_desc_P_4,0.00000,0.000000,non,0,117.568,127.3600,7.76660,0.433315,0.553134,...,0,0,0,0,1,0,0,0,0.000000,0.010835

In [22]:
fake_aplc.to_csv("allo/data/aplc.tsv", sep="\t", index=False) #"allo/data/aplc_new.tsv"

#### New data

In [23]:
for pdb in pdbs:
    if os.path.isdir(pdb):
        inf = next((f for f in os.listdir(pdb) if f.startswith(pdb) and f.endswith("_desc.txt")))
        (
            pd.read_csv("{}/{}".format(pdb, inf), sep="\t")
            .assign(**{"4A_crit": 0})
            [columns]
            .to_csv("{}/{}.txt".format(pdb, pdb), sep="\t", index=False)
        )

# Predictions

In [24]:
data = pd.concat((
    (
        pd.read_csv("{}/{}.txt".format(pdb, pdb), sep="\t")
        .assign(
            name=lambda x: x["name"].apply(
                lambda y: "{}_{}".format(pdb, y)
            )
        )
        [columns]
    )
    for pdb in pdbs
    if os.path.isdir(pdb) and os.path.isfile("{}/{}.txt".format(pdb, pdb))
))
data

,name,lig_cov,poc_cov,lig_name,4A_crit,volume,surface,depth,surf/vol,ell c/a,...,MET,PHE,PRO,SER,THR,TRP,TYR,VAL,simpleScore,drugScore
0,21du_P_0,0.0,0.0,NaN,0,833.60,1111.82,20.26,1.333757,0.32,...,2,6,1,4,2,1,0,1,0.48,0.833163
1,21du_P_1,0.0,0.0,NaN,0,409.47,479.91,16.01,1.172027,0.10,...,2,0,1,1,0,0,1,1,0.22,0.718965
2,21du_P_2,0.0,0.0,NaN,0,242.69,464.98,16.99,1.915942,0.07,...,2,1,0,2,0,0,0,1,0.12,0.665895
3,21du_P_3,0.0,0.0,NaN,0,217.54,365.28,8.26,1.679139,0.33,...,1,1,0,0,1,0,1,1,0.19,0.352360
4,21du_P_4,0.0,0.0,NaN,0,148.03,94.18,12.27,0.636222,0.15,...,1,2,0,2,1,1,0,0,0.00,0.426913
5,21du_P_5,0.0,0.0,NaN,0,117.31,296.52,8.04,2.527662,0.28,...,0,0,0,0,1,0,3,0,0.00,0.222529
6,21du_P_6,0.0,0.0,NaN,0,114.24,205.20,6.71,1.796218,0.10,...,1,4,0,0,2,0,0,0,0.05,0.204640
0,22mj_P_0,0.0,0.0,NaN,0,1245.70,1487.94,20.10,1.194461,0.08,...,1,3,4,4,3,1,1,1,0.67,0.801305
1,22mj_P_1,0.0,0.0,NaN,0,213.50,121.33,15.72,0.568290,0.09,...,0,2,0,0,0,1,0,5,0.01,0.591262
2,22mj_P_2,0.0,0.0,NaN,0,212.67,354.56,8.64,1.667184,0.25,...,0,0,0,1,0,1,0,0,0.11,0.316916
3,22mj_P_3,0.0,0.0,NaN,0,198.78,339.93,9.72,1.710081,0.40,...,0,1,0,0,0,0,1,0,0.03,0.359514
4,22mj_P_4,0.0,0.0,NaN,0,178.50,303.64,9.86,1.701064,0.20,...,1,0,0,2,0,0,0,0,0.00,0.321403
5,22mj_P_5,0.0,0.0,NaN,0,158.78,205.40,7.81,1.293614,0.52,...,0,0,1,0,1,1,1,0,0.00,0.221262
6,22mj_P_6,0.0,0.0,NaN,0,118.72,246.55,10.75,2.076735,0.16,...,0,0,1,0,1,0,2,0,0.00,0.288528
7,22mj_P_7,0.0,0.0,NaN,0,117.44,273.79,7.64,2.331318,0.49,...,0,0,1,2,0,1,0,1,0.00,0.229477
8,22mj_P_8,0.0,0.0,NaN,0,109.50,225.96,6.67,2.063562,0.29,...,0,0,0,2,1,0,0,0,0.00,0.137983
9,22mj_P_9,0.0,0.0,NaN,0,104.83,202.14,6.12,1.928265,0.45,...,0,0,0,0,0,0,0,0,0.00,0.141665
0,6s3a_P_0,0.0,0.0,NaN,0,765.50,1011.51,17.14,1.321372,0.07,...,1,3,3,3,0,0,0,1,0.52,0.815667
1,6s3a_P_1,0.0,0.0,NaN,0,382.08,612.06,14.16,1.601916,0.10,...,0,1,0,1,1,0,0,3,0.28,0.639287
2,6s3a_P_2,0.0,0.0,NaN,0,264.26,381.63,16.10,1.444146,0.10,...,0,3,2,1,1,0,1,2,0.14,0.652304
3,6s3a_P_3,0.0,0.0,NaN,0,173.50,344.75,13.80,1.987032,0.05,...,0,0,0,2,0,0,0,1,0.00,0.487242
4,6s3a_P_4,0.0,0.0,NaN,0,165.89,362.63,11.38,2.185967,0.22,...,1,2,1,0,0,0,1,1,0.00,0.407985
5,6s3a_P_5,0.0,0.0,NaN,0,148.42,264.24,7.47,1.780353,0.30,...,0,0,0,1,2,0,0,0,0.00,0.212801
6,6s3a_P_6,0.0,0.0,NaN,0,138.75,406.41,13.98,2.929081,0.03,...,1,1,0,0,0,0,0,0,0.00,0.443768
7,6s3a_P_7,0.0,0.0,NaN,0,134.27,308.87,8.74,2.300365,0.13,...,1,0,1,2,0,0,0,0,0.00,0.257565
8,6s3a_P_8,0.0,0.0,NaN,0,110.53,262.22,8.06,2.372388,0.15,...,1,0,1,0,1,0,1,0,0.00,0.199795
9,6s3a_P_9,0.0,0.0,NaN,0,103.17,190.50,7.39,1.846467,0.32,...,1,0,1,1,0,0,0,1,0.00,0.186464
0,6vvq_P_0,0.0,0.0,NaN,0,1077.25,1317.02,21.81,1.222576,0.24,...,1,5,2,3,5,1,3,3,0.66,0.803182
1,6vvq_P_1,0.0,0.0,NaN,0,387.90,566.30,19.51,1.459912,0.09,...,0,2,1,1,1,0,1,3,0.25,0.787325
2,6vvq_P_2,0.0,0.0,NaN,0,315.46,444.04,15.02,1.407595,0.08,...,0,2,0,2,0,1,3,0,0.06,0.640347
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13,9o2m_P_13,0.0,0.0,NaN,0,146.05,236.67,10.23,1.620472,0.38,...,1,2,1,0,0,1,1,1,0.11,0.355170
14,9o2m_P_14,0.0,0.0,NaN,0,113.73,268.43,8.10,2.360239,0.51,...,0,0,0,0,0,0,1,0,0.00,0.237000
15,9o2m_P_15,0.0,0.0,NaN,0,113.22,189.00,7.61,1.669316,0.52,...,0,0,0,0,0,0,2,0,0.00,0.145492
0,9prs_P_0,0.0,0.0,NaN,0,1187.98,909.20,29.74,0.765333,0.13,...,4,6,2,5,2,3,3,8,0.61,0.810507
1,9prs_P_1,0.0,0.0,NaN,0,895.14,1120.89,22.45,1.252195,0.10,...,0,2,3,5,1,3,3,5,0.59,0.834237
2,9prs_P_2,0.0,0.0,NaN,0,301.66,286.47,23.42,0.949645,0.04,...,2,3,1,3,0,2,1,4,0.07,0.824644
3,9prs_P_3,0.0,0.0,NaN,0,290.20,466.69,13.69,1.608167,0.06,...,1,0,1,0,1,0,0,1,0.07,0.564642
4,9prs_P_4,0.0,0.0,NaN,0,286.21,489.83,10.57,1.711436,0.23,...,0,0,1,0,0,0,1,1,0.07,0.434765
5,9prs_P_5,0.0,0.0,NaN,0,230.36,304.17,15.49,1.320412,0.08,...,0,1,1,0,0,0,1,1,0.04,0.600898
6,9prs_P_6,0.0,0.0,NaN,0,199.55,367.41,7.54,1.841193,0.16,...,2,0,0,1,0,0,0,2,0.15,0.297744
7,9prs_P_7,0.0,0.0,NaN,0,180.20,140.22,13.45,0.778135,0.16,...,1,1,0,7,1,1,1,1,0.00,0.500000
8,9prs_P_8,0.0,0.0,NaN,0,174.60,227.86,11.39,1.305040,0.13,...,0,1,0,1,0,0,0,0,0.00,0.348843
9,9prs_P_9,0.0,0.0,NaN,0,142.00,268.36,9.28,1.889859,0.34,...,1,1,1,0,1,1,0,1,0.00,0.318304
10,9prs_P_10,0.0,0.0,NaN,0,121.46,190.35,14.29,1.567183,0.05,...,1,4,0,0,3,0,1,1,0.00,0.485238
11,9prs_P_11,0.0,0.0,NaN,0,101.69,236.89,9.38,2.329531,0.27,...,0,1,0,0,0,2,1,0,0.03,0.271662
0,9oul_P_0,0.0,0.0,NaN,0,1223.67,1521.30,19.33,1.243227,0.09,...,3,1,3,4,5,1,0,1,0.64,0.810649
1,9oul_P_1,0.0,0.0,NaN,0,1117.34,1542.01,24.66,1.380072,0.10,...,3,2,3,2,3,0,2,5,0.62,0.818621
2,9oul_P_2,0.0,0.0,NaN,0,345.34,502.38,16.46,1.454740,0.05,...,0,0,3,0,0,0,1,0,0.13,0.697315
3,9oul_P_3,0.0,0.0,NaN,0,330.48,540.97,11.01,1.636922,0.12,...,0,1,2,2,1,0,2,1,0.21,0.526583
4,9oul_P_4,0.0,0.0,NaN,0,273.34,307.01,12.91,1.123180,0.19,...,0,2,1,2,2,3,1,1,0.17,0.548346
5,9oul_P_5,0.0,0.0,NaN,0,237.05,383.89,13.29,1.619447,0.16,...,0,1,0,1,1,1,2,0,0.12,0.480739
6,9oul_P_6,0.0,0.0,NaN,0,224.93,487.77,15.08,2.168541,0.09,...,0,1,0,0,3,0,1,0,0.01,0.567004
7,9oul_P_7,0.0,0.0,NaN,0,204.99,253.90,16.79,1.238597,0.07,...,3,1,2,0,0,0,1,5,0.00,0.625739
8,9oul_P_8,0.0,0.0,NaN,0,168.83,242.65,12.50,1.437245,0.14,...,1,2,2,2,4,0,1,0,0.00,0.449056
9,9oul_P_9,0.0,0.0,NaN,0,161.59,335.92,11.51,2.078842,0.16,...,1,0,0,1,0,1,0,0,0.00,0.352581
10,9oul_P_10,0.0,0.0,NaN,0,144.98,301.18,12.16,2.077390,0.16,...,1,1,0,2,0,0,0,0,0.00,0.383332
11,9oul_P_11,0.0,0.0,NaN,0,119.31,247.22,5.95,2.072081,0.24,...,0,0,1,0,1,0,0,1,0.00,0.169904
12,9oul_P_12,0.0,0.0,NaN,0,110.25,313.71,10.89,2.845442,0.27,...,1,0,0,1,0,0,0,0,0.00,0.300653
13,9oul_P_13,0.0,0.0,NaN,0,108.42,351.06,8.53,3.237963,0.33,...,0,1,1,0,0,1,1,0,0.03,0.247165
14,9oul_P_14,0.0,0.0,NaN,0,102.49,257.74,7.70,2.514782,0.46,...,1,1,1,0,0,0,1,0,0.00,0.209381

In [25]:
data.to_csv("data.txt", sep="\t", index=False)

In [26]:
os.system("cd allo/src && python rank_nn.py {}/data.txt".format( os.getcwd() ))

0

# Process

In [27]:
preds = pd.read_csv("data_nn_out.txt")
preds

          name  predicted probability
0     9prs_P_0                0.20681
1     8jp0_P_0                0.17328
2     8cgw_P_0                0.12425
3     8qtk_P_0                0.11766
4     8y6w_P_0                0.11200
5     9ebs_P_0                0.10903
6     6z1m_P_0                0.10138
7     9dol_P_0                0.09097
8     9o2m_P_5                0.09069
9     7p2v_P_0                0.07345
10    8uk6_P_1                0.07056
11    7gqu_P_0                0.06015
12    9mfs_P_0                0.05574
13    8fpi_P_0                0.04751
14    6z1m_P_1                0.04619
15   8fpi_P_17                0.04444
16    7qpn_P_1                0.04348
17    8v81_P_0                0.04108
18    9dol_P_1                0.03955
19    9prs_P_7                0.03873
20   8f4s_P_13                0.03832
21    8v81_P_2                0.03763
22    9prs_P_1                0.03756
23    8uk6_P_0                0.03558
24    9oul_P_0                0.03533
25    8v81_P_3                0.03507
26    6vvq_P_0                0.03278
27    7v39_P_0                0.03191
28    21du_P_4                0.03068
29    22mj_P_0                0.03041
..         ...                    ...
499  8fpi_P_54                0.01999
500  8uk6_P_19                0.01999
501  9oul_P_12                0.01999
502   6vvq_P_9                0.01998
503   6z1m_P_5                0.01998
504   6z1m_P_6                0.01998
505   7e40_P_6                0.01998
506  7e40_P_10                0.01998
507  7e40_P_17                0.01998
508   7qpn_P_9                0.01998
509   7u4k_P_4                0.01998
510   8crc_P_8                0.01998
511   22mj_P_7                0.01997
512   6s3a_P_6                0.01997
513   8f4s_P_8                0.01997
514  8fpi_P_38                0.01997
515  8v81_P_42                0.01997
516  9mfs_P_24                0.01997
517  9o2m_P_14                0.01997
518  9oul_P_14                0.01997
519  8qtk_P_12                0.01996
520   9fsj_P_8                0.01996
521   9oul_P_9                0.01996
522  7e40_P_11                0.01995
523  8crc_P_10                0.01995
524  8v81_P_37                0.01995
525  7qpn_P_15                0.01994
526   7v39_P_7                0.01994
527  8cgw_P_27                0.01994
528  9dol_P_18                0.01994

[529 rows x 2 columns]

In [28]:
preds = preds.assign(
    **dict(
        zip(
            ("pdb", "pocket"),
            zip(*preds["name"].apply(lambda x: x.split("_", 1)).tolist())
        )
    )
)

preds

          name  predicted probability   pdb pocket
0     9prs_P_0                0.20681  9prs    P_0
1     8jp0_P_0                0.17328  8jp0    P_0
2     8cgw_P_0                0.12425  8cgw    P_0
3     8qtk_P_0                0.11766  8qtk    P_0
4     8y6w_P_0                0.11200  8y6w    P_0
5     9ebs_P_0                0.10903  9ebs    P_0
6     6z1m_P_0                0.10138  6z1m    P_0
7     9dol_P_0                0.09097  9dol    P_0
8     9o2m_P_5                0.09069  9o2m    P_5
9     7p2v_P_0                0.07345  7p2v    P_0
10    8uk6_P_1                0.07056  8uk6    P_1
11    7gqu_P_0                0.06015  7gqu    P_0
12    9mfs_P_0                0.05574  9mfs    P_0
13    8fpi_P_0                0.04751  8fpi    P_0
14    6z1m_P_1                0.04619  6z1m    P_1
15   8fpi_P_17                0.04444  8fpi   P_17
16    7qpn_P_1                0.04348  7qpn    P_1
17    8v81_P_0                0.04108  8v81    P_0
18    9dol_P_1                0.03955  9dol    P_1
19    9prs_P_7                0.03873  9prs    P_7
20   8f4s_P_13                0.03832  8f4s   P_13
21    8v81_P_2                0.03763  8v81    P_2
22    9prs_P_1                0.03756  9prs    P_1
23    8uk6_P_0                0.03558  8uk6    P_0
24    9oul_P_0                0.03533  9oul    P_0
25    8v81_P_3                0.03507  8v81    P_3
26    6vvq_P_0                0.03278  6vvq    P_0
27    7v39_P_0                0.03191  7v39    P_0
28    21du_P_4                0.03068  21du    P_4
29    22mj_P_0                0.03041  22mj    P_0
..         ...                    ...   ...    ...
499  8fpi_P_54                0.01999  8fpi   P_54
500  8uk6_P_19                0.01999  8uk6   P_19
501  9oul_P_12                0.01999  9oul   P_12
502   6vvq_P_9                0.01998  6vvq    P_9
503   6z1m_P_5                0.01998  6z1m    P_5
504   6z1m_P_6                0.01998  6z1m    P_6
505   7e40_P_6                0.01998  7e40    P_6
506  7e40_P_10                0.01998  7e40   P_10
507  7e40_P_17                0.01998  7e40   P_17
508   7qpn_P_9                0.01998  7qpn    P_9
509   7u4k_P_4                0.01998  7u4k    P_4
510   8crc_P_8                0.01998  8crc    P_8
511   22mj_P_7                0.01997  22mj    P_7
512   6s3a_P_6                0.01997  6s3a    P_6
513   8f4s_P_8                0.01997  8f4s    P_8
514  8fpi_P_38                0.01997  8fpi   P_38
515  8v81_P_42                0.01997  8v81   P_42
516  9mfs_P_24                0.01997  9mfs   P_24
517  9o2m_P_14                0.01997  9o2m   P_14
518  9oul_P_14                0.01997  9oul   P_14
519  8qtk_P_12                0.01996  8qtk   P_12
520   9fsj_P_8                0.01996  9fsj    P_8
521   9oul_P_9                0.01996  9oul    P_9
522  7e40_P_11                0.01995  7e40   P_11
523  8crc_P_10                0.01995  8crc   P_10
524  8v81_P_37                0.01995  8v81   P_37
525  7qpn_P_15                0.01994  7qpn   P_15
526   7v39_P_7                0.01994  7v39    P_7
527  8cgw_P_27                0.01994  8cgw   P_27
528  9dol_P_18                0.01994  9dol   P_18

[529 rows x 4 columns]

In [29]:
from Bio import PDB

def process_pocket(pdb, pocket):
    f = next((
        f 
        for f in os.listdir("{}/pockets".format(pdb)) 
        if f.startswith(pdb) and f.endswith("_{}_res.pdb".format(pocket))
    ))
    s = PDB.PDBParser(QUIET=True).get_structure("protein", "{}/pockets/{}".format(pdb, f))
    return pd.DataFrame(
        {
            "auth_asym_id": chain.id,
            "auth_seq_id": res.get_id()[1],
            "pdbx_PDB_ins_code": res.get_id()[2] if res.get_id()[2] != " " else "?"
        }
        for model in s
        for chain in model
        for res in chain
    ).drop_duplicates()

In [30]:
results = {}

for pdb, pockets in preds.groupby("pdb"):
    d = {}
    
    pockets = (
        pockets
        .sort_values(["predicted probability", "pocket"], ascending=[False, True])
        [["predicted probability", "pocket"]]
        .values.tolist()
    )

    # Top pocket
    prob, pocket = pockets.pop(0)
    d[pocket] = {
        "prob": prob,
        "pred": 1,
        "residues": process_pocket(pdb, pocket)
    }
    
    for prob, pocket in pockets:
        d[pocket] = {
            "prob": prob,
            "pred": 0,
            "residues": process_pocket(pdb, pocket)
        }
        
    results[pdb] = d

results

{'21du': {'P_0': {'pred': 0,
   'prob': 0.024659999999999998,
   'residues':    auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0             R          841                 ?
   1             R          842                 ?
   2             R          843                 ?
   3             R          844                 ?
   4             R          845                 ?
   5             R          846                 ?
   6             R          847                 ?
   7             R          848                 ?
   8             R          849                 ?
   9             R          850                 ?
   10            R          851                 ?
   11            R          852                 ?
   12            R          853                 ?
   13            R          854                 ?
   14            R          855                 ?
   15            R          856                 ?
   16            R          861                 ?
   17            R          864                 ?
   18            R         1003                 ?
   19            R         1009                 ?
   20            R         1010                 ?
   21            R         1011                 ?
   22            R         1012                 ?
   23            R         1013                 ?
   24            R         1014                 ?
   25            R         1015                 ?
   26            R         1016                 ?
   27            R         1021                 ?
   28            R         1083                 ?
   29            R         1084                 ?
   30            R         1087                 ?
   31            R         1092                 ?
   32            R         1093                 ?
   33            R         1095                 ?
   34            R         1096                 ?
   35            R         1099                 ?
   36            R         1100                 ?},
  'P_1': {'pred': 0,
   'prob': 0.02108,
   'residues':    auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0             R          886                 ?
   1             R          891                 ?
   2             R          892                 ?
   3             R          893                 ?
   4             R          894                 ?
   5             R          895                 ?
   6             R          897                 ?
   7             R          898                 ?
   8             R          900                 ?
   9             R          901                 ?
   10            R          902                 ?
   11            R          951                 ?
   12            R          954                 ?
   13            R          955                 ?
   14            R          958                 ?
   15            R          959                 ?
   16            R         1076                 ?
   17            R         1114                 ?
   18            R         1118                 ?
   19            R         1120                 ?
   20            R         1121                 ?},
  'P_2': {'pred': 0,
   'prob': 0.020130000000000002,
   'residues':    auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0             R          959                 ?
   1             R         1043                 ?
   2             R         1044                 ?
   3             R         1046                 ?
   4             R         1047                 ?
   5             R         1050                 ?
   6             R         1068                 ?
   7             R         1069                 ?
   8             R         1072                 ?
   9             R         1073                 ?
   10            R         1076                 ?
   11            R         1113                 ?
   12            R         1114                 ?
   13            R         1117                 ?
   14            R         1118                 ?},
  'P_3': {'pred': 0,
   'prob': 0.02022,
   'residues':    auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0             R          945                 ?
   1             R          946                 ?
   2             R          949                 ?
   3             R          950                 ?
   4             R          953                 ?
   5             R          977                 ?
   6             R          981                 ?
   7             R         1028                 ?
   8             R         1031                 ?
   9             R         1032                 ?
   10            R         1035                 ?},
  'P_4': {'pred': 1,
   'prob': 0.030680000000000002,
   'residues':    auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0             R          843                 ?
   1             R          872                 ?
   2             R          875                 ?
   3             R          904                 ?
   4             R          908                 ?
   5             R          911                 ?
   6             R          912                 ?
   7             R          941                 ?
   8             R          944                 ?
   9             R          945                 ?
   10            R          948                 ?
   11            R         1081                 ?
   12            R         1103                 ?
   13            R         1104                 ?
   14            R         1105                 ?
   15            R         1106                 ?
   16            R         1107                 ?},
  'P_5': {'pred': 0,
   'prob': 0.01999,
   'residues':   auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0            R          896                 ?
   1            R          954                 ?
   2            R          957                 ?
   3            R          958                 ?
   4            R          965                 ?
   5            R          966                 ?
   6            R          967                 ?
   7            R          970                 ?},
  'P_6': {'pred': 0,
   'prob': 0.02026,
   'residues':   auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0            R         1033                 ?
   1            R         1074                 ?
   2            R         1079                 ?
   3            R         1080                 ?
   4            R         1082                 ?
   5            R         1083                 ?
   6            R         1085                 ?
   7            R         1086                 ?}},
 '22mj': {'P_0': {'pred': 1,
   'prob': 0.030410000000000003,
   'residues':    auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0             A          114                 ?
   1             A          115                 ?
   2             A          116                 ?
   3             A          117                 ?
   4             A          118                 ?
   5             A          119                 ?
   6             A          120                 ?
   7             A          122                 ?
   8             A          130                 ?
   9             A          131                 ?
   10            A          132                 ?
   11            A          133                 ?
   12            A          134                 ?
   13            A          135                 ?
   14            A          144                 ?
   15            A          146                 ?
   16            A          147                 ?
   17            A          148                 ?
   18            A          150                 ?
   19            A          151                 ?
   20            A          152                 ?
   21            A          153                 ?
   22            A          155                 ?
   23            A          156                 ?
   24            A          157                 ?
   25            A          158                 ?
   26            A          159                 ?
   27            A          160                 ?
   28            A          161                 ?
   29            A          163                 ?
   30            A          164                 ?
   31            A          167                 ?
   32            A          171                 ?
   33            A          172                 ?
   34            A          178                 ?
   35            A          179                 ?
   36            A          180                 ?
   37            A          181                 ?
   38            A          184                 ?
   39            A          189                 ?
   40            A          193                 ?
   41            A          194                 ?
   42            A          195                 ?
   43            A          196                 ?
   44            A          198                 ?
   45            A          222                 ?
   46            A          223                 ?
   47            A          225                 ?
   48            A          226                 ?
   49            A          229                 ?
   50            A          230                 ?
   51            A          233                 ?
   52            A          236                 ?
   53            A          272                 ?},
  'P_1': {'pred': 0,
   'prob': 0.02345,
   'residues':    auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0             A           16                 ?
   1             A           18                 ?
   2             A           47                 ?
   3             A           49                 ?
   4             A           88                 ?
   5             A          100                 ?
   6             A          101                 ?
   7             A          102                 ?
   8             A          110                 ?
   9             A          136                 ?
   10            A          138                 ?
   11            A          143                 ?
   12            A          145                 ?
   13            A          186                 ?
   14            A          188                 ?
   15            A          271                 ?
   16            A          272                 ?
   17            A          273                 ?
   18            A          289                 ?
   19            A          312                 ?
   20            A          314                 ?},
  'P_2': {'pred': 0,
   'prob': 0.020130000000000002,
   'residues':    auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0             A          218                 ?
   1             A          221                 ?
   2             A          223                 ?
   3             A          224                 ?
   4             A          227                 ?
   5             A          238                 ?
   6             A          239                 ?
   7             A          240                 ?
   8             A          241                 ?
   9             A          242                 ?
   10            A          270                 ?},
  'P_3': {'pred': 0,
   'prob': 0.0201,
   'residues':    auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0             A           36                 ?
   1             A           37                 ?
   2             A           38                 ?
   3             A           39                 ?
   4             A           40                 ?
   5             A           41                 ?
   6             A           43                 ?
   7             A           44                 ?
   8             A           45                 ?
   9             A           48                 ?
   10            A           83                 ?
   11            A           85                 ?
   12            A          103                 ?},
  'P_4': {'pred': 0,
   'prob': 0.02015,
   'residues':    auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0             A           24                 ?
   1             A           25                 ?
   2             A           53                 ?
   3             A           54                 ?
   4             A           55                 ?
   5             A           56                 ?
   6             A           57                 ?
   7             A           93                 ?
   8             A           94                 ?
   9             A           95                 ?
   10            A           96                 ?
   11            A          128                 ?
   12            A          129                 ?
   13            A          149                 ?},
  'P_5': {'pred': 0,
   'prob': 0.02044,
   'residues':    auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0             A           22                 ?
   1             A           24                 ?
   2             A           54                 ?
   3             A          126                 ?
   4             A          149                 ?
   5             A          152                 ?
   6             A          192                 ?
   7             A          194                 ?
   8             A          196                 ?
   9             A          247                 ?
   10            A          268                 ?
   11            A          304                 ?
   12            A          305                 ?},
  'P_6': {'pred': 0,
   'prob': 0.020030000000000003,
   'residues':    auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0             A          202                 ?
   1             A          206                 ?
   2             A          247                 ?
   3             A          248                 ?
   4             A          256                 ?
   5             A          257                 ?
   6             A          258                 ?
   7             A          262                 ?
   8             A          263                 ?
   9             A          264                 ?
   10            A          265                 ?},
  'P_7': {'pred': 0,
   'prob': 0.019969999999999998,
   'residues':    auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0             A           23                 ?
   1             A           25                 ?
   2             A           26                 ?
   3             A           27                 ?
   4             A           28                 ?
   5             A           55                 ?
   6             A           56                 ?
   7             A           70                 ?
   8             A           71                 ?
   9             A           72                 ?
   10            A           92                 ?},
  'P_8': {'pred': 0,
   'prob': 0.020059999999999998,
   'residues':   auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0            A           17                 ?
   1            A           37                 ?
   2            A           40                 ?
   3            A           43                 ?
   4            A          293                 ?
   5            A          295                 ?
   6            A          297                 ?
   7            A          309                 ?
   8            A          311                 ?},
  'P_9': {'pred': 0,
   'prob': 0.020040000000000002,
   'residues':   auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0            A          153                 ?
   1            A          154                 ?
   2            A          196                 ?
   3            A          197                 ?
   4            A          198                 ?
   5            A          199                 ?
   6            A          222                 ?
   7            A          264                 ?}},
 '6s3a': {'P_0': {'pred': 1,
   'prob': 0.02283,
   'residues':    auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0             A          126                 ?
   1             A          128                 ?
   2             A          156                 ?
   3             A          157                 ?
   4             A          158                 ?
   5             A          159                 ?
   6             A          164                 ?
   7             A          174                 ?
   8             A          175                 ?
   9             A          176                 ?
   10            A          177                 ?
   11            A          178                 ?
   12            A          179                 ?
   13            A          182                 ?
   14            A          186                 ?
   15            A          187                 ?
   16            A          189                 ?
   17            A          190                 ?
   18            A          225                 ?
   19            A          226                 ?
   20            A          227                 ?
   21            A          228                 ?
   22            A          229                 ?
   23            A          235                 ?
   24            A          238                 ?
   25            A          239                 ?
   26            A          242                 ?
   27            A          245                 ?
   28            A          295                 ?},
  'P_1': {'pred': 0,
   'prob': 0.02026,
   'residues':    auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0             A          141                 ?
   1             A          144                 ?
   2             A          145                 ?
   3             A          148                 ?
   4             A          149                 ?
   5             A          266                 ?
   6             A          267                 ?
   7             A          268                 ?
   8             A          276                 ?
   9             A          277                 ?
   10            A          278                 ?
   11            A          279                 ?
   12            A          280                 ?
   13            A          281                 ?
   14            A          282                 ?
   15            A          284                 ?
   16            A          285                 ?},
  'P_2': {'pred': 0,
   'prob': 0.02028,
   'residues':    auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0             A          119                 ?
   1             A          120                 ?
   2             A          121                 ?
   3             A          122                 ?
   4             A          123                 ?
   5             A          197                 ?
   6             A          198                 ?
   7             A          199                 ?
   8             A          212                 ?
   9             A          213                 ?
   10            A          214                 ?
   11            A          215                 ?
   12            A          216                 ?
   13            A          217                 ?
   14            A          314                 ?
   15            A          317                 ?
   16            A          318                 ?},
  'P_3': {'pred': 0,
   'prob': 0.02012,
   'residues':    auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0             A          128                 ?
   1             A          129                 ?
   2             A          130                 ?
   3             A          132                 ?
   4             A          133                 ?
   5             A          224                 ?
   6             A          225                 ?
   7             A          247                 ?

In [31]:
import pickle

resultsf = "ALLO_results.pkl"

In [32]:
with open(resultsf, "wb") as f:
    pickle.dump(results, f)

In [33]:
with open(resultsf, "rb") as f:
    results = pickle.load(f)

results

{'21du': {'P_0': {'pred': 0,
   'prob': 0.024659999999999998,
   'residues':    auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0             R          841                 ?
   1             R          842                 ?
   2             R          843                 ?
   3             R          844                 ?
   4             R          845                 ?
   5             R          846                 ?
   6             R          847                 ?
   7             R          848                 ?
   8             R          849                 ?
   9             R          850                 ?
   10            R          851                 ?
   11            R          852                 ?
   12            R          853                 ?
   13            R          854                 ?
   14            R          855                 ?
   15            R          856                 ?
   16            R          861                 ?
   17            R          864                 ?
   18            R         1003                 ?
   19            R         1009                 ?
   20            R         1010                 ?
   21            R         1011                 ?
   22            R         1012                 ?
   23            R         1013                 ?
   24            R         1014                 ?
   25            R         1015                 ?
   26            R         1016                 ?
   27            R         1021                 ?
   28            R         1083                 ?
   29            R         1084                 ?
   30            R         1087                 ?
   31            R         1092                 ?
   32            R         1093                 ?
   33            R         1095                 ?
   34            R         1096                 ?
   35            R         1099                 ?
   36            R         1100                 ?},
  'P_1': {'pred': 0,
   'prob': 0.02108,
   'residues':    auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0             R          886                 ?
   1             R          891                 ?
   2             R          892                 ?
   3             R          893                 ?
   4             R          894                 ?
   5             R          895                 ?
   6             R          897                 ?
   7             R          898                 ?
   8             R          900                 ?
   9             R          901                 ?
   10            R          902                 ?
   11            R          951                 ?
   12            R          954                 ?
   13            R          955                 ?
   14            R          958                 ?
   15            R          959                 ?
   16            R         1076                 ?
   17            R         1114                 ?
   18            R         1118                 ?
   19            R         1120                 ?
   20            R         1121                 ?},
  'P_2': {'pred': 0,
   'prob': 0.020130000000000002,
   'residues':    auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0             R          959                 ?
   1             R         1043                 ?
   2             R         1044                 ?
   3             R         1046                 ?
   4             R         1047                 ?
   5             R         1050                 ?
   6             R         1068                 ?
   7             R         1069                 ?
   8             R         1072                 ?
   9             R         1073                 ?
   10            R         1076                 ?
   11            R         1113                 ?
   12            R         1114                 ?
   13            R         1117                 ?
   14            R         1118                 ?},
  'P_3': {'pred': 0,
   'prob': 0.02022,
   'residues':    auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0             R          945                 ?
   1             R          946                 ?
   2             R          949                 ?
   3             R          950                 ?
   4             R          953                 ?
   5             R          977                 ?
   6             R          981                 ?
   7             R         1028                 ?
   8             R         1031                 ?
   9             R         1032                 ?
   10            R         1035                 ?},
  'P_4': {'pred': 1,
   'prob': 0.030680000000000002,
   'residues':    auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0             R          843                 ?
   1             R          872                 ?
   2             R          875                 ?
   3             R          904                 ?
   4             R          908                 ?
   5             R          911                 ?
   6             R          912                 ?
   7             R          941                 ?
   8             R          944                 ?
   9             R          945                 ?
   10            R          948                 ?
   11            R         1081                 ?
   12            R         1103                 ?
   13            R         1104                 ?
   14            R         1105                 ?
   15            R         1106                 ?
   16            R         1107                 ?},
  'P_5': {'pred': 0,
   'prob': 0.01999,
   'residues':   auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0            R          896                 ?
   1            R          954                 ?
   2            R          957                 ?
   3            R          958                 ?
   4            R          965                 ?
   5            R          966                 ?
   6            R          967                 ?
   7            R          970                 ?},
  'P_6': {'pred': 0,
   'prob': 0.02026,
   'residues':   auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0            R         1033                 ?
   1            R         1074                 ?
   2            R         1079                 ?
   3            R         1080                 ?
   4            R         1082                 ?
   5            R         1083                 ?
   6            R         1085                 ?
   7            R         1086                 ?}},
 '22mj': {'P_0': {'pred': 1,
   'prob': 0.030410000000000003,
   'residues':    auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0             A          114                 ?
   1             A          115                 ?
   2             A          116                 ?
   3             A          117                 ?
   4             A          118                 ?
   5             A          119                 ?
   6             A          120                 ?
   7             A          122                 ?
   8             A          130                 ?
   9             A          131                 ?
   10            A          132                 ?
   11            A          133                 ?
   12            A          134                 ?
   13            A          135                 ?
   14            A          144                 ?
   15            A          146                 ?
   16            A          147                 ?
   17            A          148                 ?
   18            A          150                 ?
   19            A          151                 ?
   20            A          152                 ?
   21            A          153                 ?
   22            A          155                 ?
   23            A          156                 ?
   24            A          157                 ?
   25            A          158                 ?
   26            A          159                 ?
   27            A          160                 ?
   28            A          161                 ?
   29            A          163                 ?
   30            A          164                 ?
   31            A          167                 ?
   32            A          171                 ?
   33            A          172                 ?
   34            A          178                 ?
   35            A          179                 ?
   36            A          180                 ?
   37            A          181                 ?
   38            A          184                 ?
   39            A          189                 ?
   40            A          193                 ?
   41            A          194                 ?
   42            A          195                 ?
   43            A          196                 ?
   44            A          198                 ?
   45            A          222                 ?
   46            A          223                 ?
   47            A          225                 ?
   48            A          226                 ?
   49            A          229                 ?
   50            A          230                 ?
   51            A          233                 ?
   52            A          236                 ?
   53            A          272                 ?},
  'P_1': {'pred': 0,
   'prob': 0.02345,
   'residues':    auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0             A           16                 ?
   1             A           18                 ?
   2             A           47                 ?
   3             A           49                 ?
   4             A           88                 ?
   5             A          100                 ?
   6             A          101                 ?
   7             A          102                 ?
   8             A          110                 ?
   9             A          136                 ?
   10            A          138                 ?
   11            A          143                 ?
   12            A          145                 ?
   13            A          186                 ?
   14            A          188                 ?
   15            A          271                 ?
   16            A          272                 ?
   17            A          273                 ?
   18            A          289                 ?
   19            A          312                 ?
   20            A          314                 ?},
  'P_2': {'pred': 0,
   'prob': 0.020130000000000002,
   'residues':    auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0             A          218                 ?
   1             A          221                 ?
   2             A          223                 ?
   3             A          224                 ?
   4             A          227                 ?
   5             A          238                 ?
   6             A          239                 ?
   7             A          240                 ?
   8             A          241                 ?
   9             A          242                 ?
   10            A          270                 ?},
  'P_3': {'pred': 0,
   'prob': 0.0201,
   'residues':    auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0             A           36                 ?
   1             A           37                 ?
   2             A           38                 ?
   3             A           39                 ?
   4             A           40                 ?
   5             A           41                 ?
   6             A           43                 ?
   7             A           44                 ?
   8             A           45                 ?
   9             A           48                 ?
   10            A           83                 ?
   11            A           85                 ?
   12            A          103                 ?},
  'P_4': {'pred': 0,
   'prob': 0.02015,
   'residues':    auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0             A           24                 ?
   1             A           25                 ?
   2             A           53                 ?
   3             A           54                 ?
   4             A           55                 ?
   5             A           56                 ?
   6             A           57                 ?
   7             A           93                 ?
   8             A           94                 ?
   9             A           95                 ?
   10            A           96                 ?
   11            A          128                 ?
   12            A          129                 ?
   13            A          149                 ?},
  'P_5': {'pred': 0,
   'prob': 0.02044,
   'residues':    auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0             A           22                 ?
   1             A           24                 ?
   2             A           54                 ?
   3             A          126                 ?
   4             A          149                 ?
   5             A          152                 ?
   6             A          192                 ?
   7             A          194                 ?
   8             A          196                 ?
   9             A          247                 ?
   10            A          268                 ?
   11            A          304                 ?
   12            A          305                 ?},
  'P_6': {'pred': 0,
   'prob': 0.020030000000000003,
   'residues':    auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0             A          202                 ?
   1             A          206                 ?
   2             A          247                 ?
   3             A          248                 ?
   4             A          256                 ?
   5             A          257                 ?
   6             A          258                 ?
   7             A          262                 ?
   8             A          263                 ?
   9             A          264                 ?
   10            A          265                 ?},
  'P_7': {'pred': 0,
   'prob': 0.019969999999999998,
   'residues':    auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0             A           23                 ?
   1             A           25                 ?
   2             A           26                 ?
   3             A           27                 ?
   4             A           28                 ?
   5             A           55                 ?
   6             A           56                 ?
   7             A           70                 ?
   8             A           71                 ?
   9             A           72                 ?
   10            A           92                 ?},
  'P_8': {'pred': 0,
   'prob': 0.020059999999999998,
   'residues':   auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0            A           17                 ?
   1            A           37                 ?
   2            A           40                 ?
   3            A           43                 ?
   4            A          293                 ?
   5            A          295                 ?
   6            A          297                 ?
   7            A          309                 ?
   8            A          311                 ?},
  'P_9': {'pred': 0,
   'prob': 0.020040000000000002,
   'residues':   auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0            A          153                 ?
   1            A          154                 ?
   2            A          196                 ?
   3            A          197                 ?
   4            A          198                 ?
   5            A          199                 ?
   6            A          222                 ?
   7            A          264                 ?}},
 '6s3a': {'P_0': {'pred': 1,
   'prob': 0.02283,
   'residues':    auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0             A          126                 ?
   1             A          128                 ?
   2             A          156                 ?
   3             A          157                 ?
   4             A          158                 ?
   5             A          159                 ?
   6             A          164                 ?
   7             A          174                 ?
   8             A          175                 ?
   9             A          176                 ?
   10            A          177                 ?
   11            A          178                 ?
   12            A          179                 ?
   13            A          182                 ?
   14            A          186                 ?
   15            A          187                 ?
   16            A          189                 ?
   17            A          190                 ?
   18            A          225                 ?
   19            A          226                 ?
   20            A          227                 ?
   21            A          228                 ?
   22            A          229                 ?
   23            A          235                 ?
   24            A          238                 ?
   25            A          239                 ?
   26            A          242                 ?
   27            A          245                 ?
   28            A          295                 ?},
  'P_1': {'pred': 0,
   'prob': 0.02026,
   'residues':    auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0             A          141                 ?
   1             A          144                 ?
   2             A          145                 ?
   3             A          148                 ?
   4             A          149                 ?
   5             A          266                 ?
   6             A          267                 ?
   7             A          268                 ?
   8             A          276                 ?
   9             A          277                 ?
   10            A          278                 ?
   11            A          279                 ?
   12            A          280                 ?
   13            A          281                 ?
   14            A          282                 ?
   15            A          284                 ?
   16            A          285                 ?},
  'P_2': {'pred': 0,
   'prob': 0.02028,
   'residues':    auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0             A          119                 ?
   1             A          120                 ?
   2             A          121                 ?
   3             A          122                 ?
   4             A          123                 ?
   5             A          197                 ?
   6             A          198                 ?
   7             A          199                 ?
   8             A          212                 ?
   9             A          213                 ?
   10            A          214                 ?
   11            A          215                 ?
   12            A          216                 ?
   13            A          217                 ?
   14            A          314                 ?
   15            A          317                 ?
   16            A          318                 ?},
  'P_3': {'pred': 0,
   'prob': 0.02012,
   'residues':    auth_asym_id  auth_seq_id pdbx_PDB_ins_code
   0             A          128                 ?
   1             A          129                 ?
   2             A          130                 ?
   3             A          132                 ?
   4             A          133                 ?
   5             A          224                 ?
   6             A          225                 ?
   7             A          247                 ?

In [34]:
resultsd = {
    pdb: {
        pocket: {
            k: v if k != "residues" else v.astype(str).to_dict(orient="list")
            for k, v in pocketd.items()
        }
        for pocket, pocketd in pockets.items()
    } for pdb, pockets in results.items()
}

resultsd

{'21du': {'P_0': {'pred': 0,
   'prob': 0.024659999999999998,
   'residues': {'auth_asym_id': ['R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R'],
    'auth_seq_id': ['841',
     '842',
     '843',
     '844',
     '845',
     '846',
     '847',
     '848',
     '849',
     '850',
     '851',
     '852',
     '853',
     '854',
     '855',
     '856',
     '861',
     '864',
     '1003',
     '1009',
     '1010',
     '1011',
     '1012',
     '1013',
     '1014',
     '1015',
     '1016',
     '1021',
     '1083',
     '1084',
     '1087',
     '1092',
     '1093',
     '1095',
     '1096',
     '1099',
     '1100'],
    'pdbx_PDB_ins_code': ['?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?']}},
  'P_1': {'pred': 0,
   'prob': 0.02108,
   'residues': {'auth_asym_id': ['R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R'],
    'auth_seq_id': ['886',
     '891',
     '892',
     '893',
     '894',
     '895',
     '897',
     '898',
     '900',
     '901',
     '902',
     '951',
     '954',
     '955',
     '958',
     '959',
     '1076',
     '1114',
     '1118',
     '1120',
     '1121'],
    'pdbx_PDB_ins_code': ['?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?']}},
  'P_2': {'pred': 0,
   'prob': 0.020130000000000002,
   'residues': {'auth_asym_id': ['R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R'],
    'auth_seq_id': ['959',
     '1043',
     '1044',
     '1046',
     '1047',
     '1050',
     '1068',
     '1069',
     '1072',
     '1073',
     '1076',
     '1113',
     '1114',
     '1117',
     '1118'],
    'pdbx_PDB_ins_code': ['?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?']}},
  'P_3': {'pred': 0,
   'prob': 0.02022,
   'residues': {'auth_asym_id': ['R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R'],
    'auth_seq_id': ['945',
     '946',
     '949',
     '950',
     '953',
     '977',
     '981',
     '1028',
     '1031',
     '1032',
     '1035'],
    'pdbx_PDB_ins_code': ['?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?']}},
  'P_4': {'pred': 1,
   'prob': 0.030680000000000002,
   'residues': {'auth_asym_id': ['R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R',
     'R'],
    'auth_seq_id': ['843',
     '872',
     '875',
     '904',
     '908',
     '911',
     '912',
     '941',
     '944',
     '945',
     '948',
     '1081',
     '1103',
     '1104',
     '1105',
     '1106',
     '1107'],
    'pdbx_PDB_ins_code': ['?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?']}},
  'P_5': {'pred': 0,
   'prob': 0.01999,
   'residues': {'auth_asym_id': ['R', 'R', 'R', 'R', 'R', 'R', 'R', 'R'],
    'auth_seq_id': ['896', '954', '957', '958', '965', '966', '967', '970'],
    'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?']}},
  'P_6': {'pred': 0,
   'prob': 0.02026,
   'residues': {'auth_asym_id': ['R', 'R', 'R', 'R', 'R', 'R', 'R', 'R'],
    'auth_seq_id': ['1033',
     '1074',
     '1079',
     '1080',
     '1082',
     '1083',
     '1085',
     '1086'],
    'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?']}}},
 '22mj': {'P_0': {'pred': 1,
   'prob': 0.030410000000000003,
   'residues': {'auth_asym_id': ['A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A'],
    'auth_seq_id': ['114',
     '115',
     '116',
     '117',
     '118',
     '119',
     '120',
     '122',
     '130',
     '131',
     '132',
     '133',
     '134',
     '135',
     '144',
     '146',
     '147',
     '148',
     '150',
     '151',
     '152',
     '153',
     '155',
     '156',
     '157',
     '158',
     '159',
     '160',
     '161',
     '163',
     '164',
     '167',
     '171',
     '172',
     '178',
     '179',
     '180',
     '181',
     '184',
     '189',
     '193',
     '194',
     '195',
     '196',
     '198',
     '222',
     '223',
     '225',
     '226',
     '229',
     '230',
     '233',
     '236',
     '272'],
    'pdbx_PDB_ins_code': ['?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?']}},
  'P_1': {'pred': 0,
   'prob': 0.02345,
   'residues': {'auth_asym_id': ['A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A'],
    'auth_seq_id': ['16',
     '18',
     '47',
     '49',
     '88',
     '100',
     '101',
     '102',
     '110',
     '136',
     '138',
     '143',
     '145',
     '186',
     '188',
     '271',
     '272',
     '273',
     '289',
     '312',
     '314'],
    'pdbx_PDB_ins_code': ['?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?']}},
  'P_2': {'pred': 0,
   'prob': 0.020130000000000002,
   'residues': {'auth_asym_id': ['A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A'],
    'auth_seq_id': ['218',
     '221',
     '223',
     '224',
     '227',
     '238',
     '239',
     '240',
     '241',
     '242',
     '270'],
    'pdbx_PDB_ins_code': ['?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?']}},
  'P_3': {'pred': 0,
   'prob': 0.0201,
   'residues': {'auth_asym_id': ['A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A'],
    'auth_seq_id': ['36',
     '37',
     '38',
     '39',
     '40',
     '41',
     '43',
     '44',
     '45',
     '48',
     '83',
     '85',
     '103'],
    'pdbx_PDB_ins_code': ['?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?']}},
  'P_4': {'pred': 0,
   'prob': 0.02015,
   'residues': {'auth_asym_id': ['A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A'],
    'auth_seq_id': ['24',
     '25',
     '53',
     '54',
     '55',
     '56',
     '57',
     '93',
     '94',
     '95',
     '96',
     '128',
     '129',
     '149'],
    'pdbx_PDB_ins_code': ['?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?']}},
  'P_5': {'pred': 0,
   'prob': 0.02044,
   'residues': {'auth_asym_id': ['A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A'],
    'auth_seq_id': ['22',
     '24',
     '54',
     '126',
     '149',
     '152',
     '192',
     '194',
     '196',
     '247',
     '268',
     '304',
     '305'],
    'pdbx_PDB_ins_code': ['?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?']}},
  'P_6': {'pred': 0,
   'prob': 0.020030000000000003,
   'residues': {'auth_asym_id': ['A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A'],
    'auth_seq_id': ['202',
     '206',
     '247',
     '248',
     '256',
     '257',
     '258',
     '262',
     '263',
     '264',
     '265'],
    'pdbx_PDB_ins_code': ['?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?']}},
  'P_7': {'pred': 0,
   'prob': 0.019969999999999998,
   'residues': {'auth_asym_id': ['A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A'],
    'auth_seq_id': ['23',
     '25',
     '26',
     '27',
     '28',
     '55',
     '56',
     '70',
     '71',
     '72',
     '92'],
    'pdbx_PDB_ins_code': ['?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?']}},
  'P_8': {'pred': 0,
   'prob': 0.020059999999999998,
   'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
    'auth_seq_id': ['17', '37', '40', '43', '293', '295', '297', '309', '311'],
    'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?', '?']}},
  'P_9': {'pred': 0,
   'prob': 0.020040000000000002,
   'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
    'auth_seq_id': ['153', '154', '196', '197', '198', '199', '222', '264'],
    'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?']}}},
 '6s3a': {'P_0': {'pred': 1,
   'prob': 0.02283,
   'residues': {'auth_asym_id': ['A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A'],
    'auth_seq_id': ['126',
     '128',
     '156',
     '157',
     '158',
     '159',
     '164',
     '174',
     '175',
     '176',
     '177',
     '178',
     '179',
     '182',
     '186',
     '187',
     '189',
     '190',
     '225',
     '226',
     '227',
     '228',
     '229',
     '235',
     '238',
     '239',
     '242',
     '245',
     '295'],
    'pdbx_PDB_ins_code': ['?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?']}},
  'P_1': {'pred': 0,
   'prob': 0.02026,
   'residues': {'auth_asym_id': ['A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A'],
    'auth_seq_id': ['141',
     '144',
     '145',
     '148',
     '149',
     '266',
     '267',
     '268',
     '276',
     '277',
     '278',
     '279',
     '280',
     '281',
     '282',
     '284',
     '285'],
    'pdbx_PDB_ins_code': ['?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?']}},
  'P_2': {'pred': 0,
   'prob': 0.02028,
   'residues': {'auth_asym_id': ['A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A'],
    'auth_seq_id': ['119',
     '120',
     '121',
     '122',
     '123',
     '197',
     '198',
     '199',
     '212',
     '213',
     '214',
     '215',
     '216',
     '217',
     '314',
     '317',
     '318'],
    'pdbx_PDB_ins_code': ['?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?']}},
  'P_3': {'pred': 0,
   'prob': 0.02012,
   'residues': {'auth_asym_id': ['A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A'],
    'auth_seq_id': ['128',
     '129',
     '130',
     '132',
     '133',
     '224',
     '225',
     '247',
     '248',
     '249',
     '250',
     '255',
     '258',
     '259',
     '260'],
    'pdbx_PDB_ins_code': ['?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?']}},
  'P_4': {'pred': 0,
   'prob': 0.02,
   'residues': {'auth_asym_id': ['A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A'],
    'auth_seq_id': ['164',
     '167',
     '168',
     '169',
     '200',
     '201',
     '203',
     '208',
     '209',
     '210',
     '211',
     '212',
     '213'],
    'pdbx_PDB_ins_code': ['?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?']}},
  'P_5': {'pred': 0,
   'prob': 0.02008,
   'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A'],
    'auth_seq_id': ['120', '121', '196', '317', '322', '323', '326'],
    'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?']}},
  'P_6': {'pred': 0,
   'prob': 0.019969999999999998,
   'residues': {'auth_asym_id': ['A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A'],
    'auth_seq_id': ['243',
     '244',
     '245',
     '246',
     '294',
     '295',
     '296',
     '309',
     '312',
     '313'],
    'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?']}},
  'P_7': {'pred': 0,
   'prob': 0.020040000000000002,
   'residues': {'auth_asym_id': ['A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A',
     'A'],
    'auth_seq_id': ['130',
     '131',
     '132',
     '133',
     '134',
     '135',
     '136',
     '177',
     '259',
     '260',
     '262'],
    'pdbx_PDB_ins_code': ['?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?']}},
  'P_8': {'pred': 0,
   'prob': 0.02005,
   'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
    'auth_seq_id': ['254', '264', '267', '268', '269', '270', '283', '288'],
    'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?']}},
  'P_9': {'pred': 0,
   'prob': 0.020130000000000002,
   'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
    'auth_seq_id': ['273',
     '274',
     '275',
     '281',
     '285',
     '286',
     '302',
     '304',
     '305'],
    'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?', '?']}}},
 '6vvq': {'P_0': {'pred': 1,
   'prob': 0.032780000000000004,
   'residues': {'auth_asym_id': ['C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C'],
    'auth_seq_id': ['426',
     '428',
     '449',
     '452',
     '453',
     '454',
     '455',
     '456',
     '474',
     '476',
     '477',
     '478',
     '479',
     '480',
     '481',
     '482',
     '484',
     '485',
     '486',
     '488',
     '490',
     '508',
     '510',
     '523',
     '526',
     '527',
     '530',
     '532',
     '546',
     '548',
     '551',
     '553',
     '554',
     '555',
     '556',
     '557',
     '558',
     '560',
     '568',
     '569',
     '571',
     '572',
     '573',
     '575',
     '576'],
    'pdbx_PDB_ins_code': ['?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?']}},
  'P_1': {'pred': 0,
   'prob': 0.02036,
   'residues': {'auth_asym_id': ['C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C'],
    'auth_seq_id': ['363',
     '364',
     '365',
     '366',
     '421',
     '422',
     '423',
     '424',
     '425',
     '426',
     '548',
     '549',
     '550',
     '551',
     '552',
     '554',
     '555',
     '558'],
    'pdbx_PDB_ins_code': ['?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?']}},
  'P_10': {'pred': 0,
   'prob': 0.01999,
   'residues': {'auth_asym_id': ['C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C'],
    'auth_seq_id': ['473',
     '487',
     '516',
     '517',
     '518',
     '519',
     '521',
     '522',
     '523',
     '524'],
    'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?']}},
  'P_11': {'pred': 0,
   'prob': 0.01999,
   'residues': {'auth_asym_id': ['C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C'],
    'auth_seq_id': ['410',
     '411',
     '413',
     '428',
     '430',
     '567',
     '569',
     '570',
     '571',
     '573',
     '574'],
    'pdbx_PDB_ins_code': ['?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?']}},
  'P_2': {'pred': 0,
   'prob': 0.020880000000000003,
   'residues': {'auth_asym_id': ['C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C',
     'C'],
    'auth_seq_id': ['442',
     '443',
     '444',
     '445',
     '446',
     '447',
     '448',
     '449',
     '452',
     '456',
     '461',
     '464',
     '466',
     '467',
     '468',
     '469',
     '470',
     '472',
     '492',
     '493',
     '494',
     '506',
     '507',
     '508',
     '531',
     '532',
     '546',
     '579'],
    'pdbx_PDB_ins_code': ['?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?',
     '?']}},
  'P_3': {'pred': 0,
   'prob': 0.02009,

In [35]:
import json

In [36]:
with open(resultsf.replace(".pkl", ".json"), "w") as f:
    json.dump(resultsd, f)