In [1]:
import os, pickle, tempfile, requests
import pandas as pd

In [2]:
import sys
sys.path.append("../../training_data")

In [3]:
from utils.utils import Cif
from utils.pocket_utils import Pocket

# Data

In [4]:
ups = (
    ("7gqu", "q14191"), # done
    ("8qni", "Q13191"),
    ("8v81", "P13569"),
    ("8jp0", "P32418"),
    ("7yg5", "Q15878")
    # 8f4s not available
    # 8aq6 dimer not available
    # 8uk6 already included
)

## Process AlphaFold

In [5]:
for holo, up_id in ups:
    name = f"AF-{up_id.upper()}-F1"
    outfname = f"{name.lower()}_out.cif"
    if not os.path.isfile(outfname):
        with tempfile.NamedTemporaryFile(suffix=".cif", mode="w+") as f:
            f.write(requests.get(f"https://alphafold.ebi.ac.uk/files/{name.upper()}-model_v6.cif").content.decode())
            cif = Cif(name.lower(), f.name)
            sel_res = cif.atoms.loc[cif.atoms["B_iso_or_equiv"].astype(float) > 50][["label_asym_id", "label_seq_id"]].drop_duplicates()
            with cif._extended_temp_ciff({
                    "_atom_site": cif.atoms.merge(sel_res).to_dict(orient="list")
                }) as f:
                with open(outfname, "w") as outf:
                    outf.write(f.read())

from gradio_client import Client, handle_file

client = Client("http://127.0.0.1:8998/", download_files=False)

results = {}

for up_id in (
    i[1] for i in ups
):
    results[up_id] = client.predict(
        pdb={"text": "", "files": [handle_file(f"/home/fnerin/Desktop/AlloPockets_main/models/alphafold/af-{up_id.lower()}-f1_out.cif"),]},
        chainid="A", # {"pdb_id": pdb['text'], "chain_id": chain, "chain_choices": chain_choices, "pdbdir": pdbdir}
        api_name="/predict_ensemble",
    )

results

## Collect results

In [7]:
news = {}

for holo, pdb_id, jobid, jobdir in (
    ("7gqu", "af-q14191-f1", "af-q14191-f1_out_1153095567726851806", "af-q14191-f1_out_1153095567726851806-A-2025-12-18-17-38-34-214912-c9ilpwzxalt"),
    ("8qni", "af-q13191-f1", "af-q13191-f1_out_-184824251272106742", "af-q13191-f1_out_-184824251272106742-A-2025-12-18-18-20-17-843186-5595101188430149814"),
    ("8v81", "af-p13569-f1", "af-p13569-f1_out_5062893454687777811", "af-p13569-f1_out_5062893454687777811-A-2025-12-18-18-23-47-374313-8974034245740134829"),
    ("8jp0", "af-p32418-f1", "af-p32418-f1_out_-121382155796052104", "af-p32418-f1_out_-121382155796052104-A-2025-12-18-19-05-07-618763-3016327104239585995"),
    ("7yg5", "af-q15878-f1", "af-q15878-f1_out_8248982329038707866", "af-q15878-f1_out_8248982329038707866-A-2025-12-18-19-16-13-776440-3338984357806762671")
    # ("8uk6", "af-q14191-f1", "af-q14191-f1-A-2025-12-18-14-32-07-067312-gpn757ep4vl"),
):
    path = f"../../../AlloPockets/gradio/{jobid}/{jobdir}"
    pockets_out = f"{path}/{jobid}/{jobid}_out" # /{pdb_id}_out.cif
    news[holo] = dict(
        pdb_id = pdb_id,
        # path = path,
        predsf = f"{path}/predictions.csv",
        # pockets_out = pockets_out,
        pocketsf = f"{pockets_out}/{jobid}_out.cif",
        pocketsdir = f"{pockets_out}/pockets"
    )

# news["8uk6"] = dict(
#     pdb_id = "AF-A0A1D8PQM9-F1".lower(),
#     # path = path,
#     # predsf = f"{path}/predictions.csv",
#     # pockets_out = pockets_out,
#     pocketsf = f"../../training_data/8.Apos/Extra_set/pockets/AF-A0A1D8PQM9-F1/AF-A0A1D8PQM9-F1_out/AF-A0A1D8PQM9-F1_out.cif",
#     pocketsdir = f"../../training_data/8.Apos/Extra_set/pockets/AF-A0A1D8PQM9-F1/AF-A0A1D8PQM9-F1_out/pockets"
# )

news

{'7gqu': {'pdb_id': 'af-q14191-f1',
  'predsf': '../../../AlloPockets/gradio/af-q14191-f1_out_1153095567726851806/af-q14191-f1_out_1153095567726851806-A-2025-12-18-17-38-34-214912-c9ilpwzxalt/predictions.csv',
  'pocketsf': '../../../AlloPockets/gradio/af-q14191-f1_out_1153095567726851806/af-q14191-f1_out_1153095567726851806-A-2025-12-18-17-38-34-214912-c9ilpwzxalt/af-q14191-f1_out_1153095567726851806/af-q14191-f1_out_1153095567726851806_out/af-q14191-f1_out_1153095567726851806_out.cif',
  'pocketsdir': '../../../AlloPockets/gradio/af-q14191-f1_out_1153095567726851806/af-q14191-f1_out_1153095567726851806-A-2025-12-18-17-38-34-214912-c9ilpwzxalt/af-q14191-f1_out_1153095567726851806/af-q14191-f1_out_1153095567726851806_out/pockets'},
 '8qni': {'pdb_id': 'af-q13191-f1',
  'predsf': '../../../AlloPockets/gradio/af-q13191-f1_out_-184824251272106742/af-q13191-f1_out_-184824251272106742-A-2025-12-18-18-20-17-843186-5595101188430149814/predictions.csv',
  'pocketsf': '../../../AlloPockets/gradio/af-q13191-f1_out_-184824251272106742/af-q13191-f1_out_-184824251272106742-A-2025-12-18-18-20-17-843186-5595101188430149814/af-q13191-f1_out_-184824251272106742/af-q13191-f1_out_-184824251272106742_out/af-q13191-f1_out_-184824251272106742_out.cif',
  'pocketsdir': '../../../AlloPockets/gradio/af-q13191-f1_out_-184824251272106742/af-q13191-f1_out_-184824251272106742-A-2025-12-18-18-20-17-843186-5595101188430149814/af-q13191-f1_out_-184824251272106742/af-q13191-f1_out_-184824251272106742_out/pockets'},
 '8v81': {'pdb_id': 'af-p13569-f1',
  'predsf': '../../../AlloPockets/gradio/af-p13569-f1_out_5062893454687777811/af-p13569-f1_out_5062893454687777811-A-2025-12-18-18-23-47-374313-8974034245740134829/predictions.csv',
  'pocketsf': '../../../AlloPockets/gradio/af-p13569-f1_out_5062893454687777811/af-p13569-f1_out_5062893454687777811-A-2025-12-18-18-23-47-374313-8974034245740134829/af-p13569-f1_out_5062893454687777811/af-p13569-f1_out_5062893454687777811_out/af-p13569-f1_out_5062893454687777811_out.cif',
  'pocketsdir': '../../../AlloPockets/gradio/af-p13569-f1_out_5062893454687777811/af-p13569-f1_out_5062893454687777811-A-2025-12-18-18-23-47-374313-8974034245740134829/af-p13569-f1_out_5062893454687777811/af-p13569-f1_out_5062893454687777811_out/pockets'},
 '8jp0': {'pdb_id': 'af-p32418-f1',
  'predsf': '../../../AlloPockets/gradio/af-p32418-f1_out_-121382155796052104/af-p32418-f1_out_-121382155796052104-A-2025-12-18-19-05-07-618763-3016327104239585995/predictions.csv',
  'pocketsf': '../../../AlloPockets/gradio/af-p32418-f1_out_-121382155796052104/af-p32418-f1_out_-121382155796052104-A-2025-12-18-19-05-07-618763-3016327104239585995/af-p32418-f1_out_-121382155796052104/af-p32418-f1_out_-121382155796052104_out/af-p32418-f1_out_-121382155796052104_out.cif',
  'pocketsdir': '../../../AlloPockets/gradio/af-p32418-f1_out_-121382155796052104/af-p32418-f1_out_-121382155796052104-A-2025-12-18-19-05-07-618763-3016327104239585995/af-p32418-f1_out_-121382155796052104/af-p32418-f1_out_-121382155796052104_out/pockets'},
 '7yg5': {'pdb_id': 'af-q15878-f1',
  'predsf': '../../../AlloPockets/gradio/af-q15878-f1_out_8248982329038707866/af-q15878-f1_out_8248982329038707866-A-2025-12-18-19-16-13-776440-3338984357806762671/predictions.csv',
  'pocketsf': '../../../AlloPockets/gradio/af-q15878-f1_out_8248982329038707866/af-q15878-f1_out_8248982329038707866-A-2025-12-18-19-16-13-776440-3338984357806762671/af-q15878-f1_out_8248982329038707866/af-q15878-f1_out_8248982329038707866_out/af-q15878-f1_out_8248982329038707866_out.cif',
  'pocketsdir': '../../../AlloPockets/gradio/af-q15878-f1_out_8248982329038707866/af-q15878-f1_out_8248982329038707866-A-2025-12-18-19-16-13-776440-3338984357806762671/af-q15878-f1_out_8248982329038707866/af-q15878-f1_out_8248982329038707866_out/pockets'}}

## Sites

In [8]:
with open("../../training_data/7.Extra_set/news_sites.pkl", "rb") as f:
    news_sites = pickle.load(f) # {k: v for k, v in pickle.load(f).items() if k in ("7gqu", "8qni", "8v81", "8jp0", "7yg5")}

len(news_sites), news_sites["7gqu"]

(25,
 [{'mod':      label_comp_id label_asym_id label_entity_id label_seq_id  \
   3420           X1L             D               4            .

        pdbx_PDB_ins_code auth_seq_id auth_comp_id auth_asym_id  \
   3420                 ?        1002          X1L            A

        pdbx_PDB_model_num pdbx_label_index pdbx_sifts_xref_db_name  \
   3420                  1             1002                       ?

        pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num pdbx_sifts_xref_db_res
   3420                      ?                      ?                      ?  ,
   'site':    label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
   0            VAL             A               1           55                 ?
   1            MET             A               1           56                 ?
   2            ALA             A               1           57                 ?
   3            THR             A               1          188                 ?
   4            ALA             A               1          189                 ?
   5            THR             A               1          190                 ?
   6            ALA             A               1          191                 ?
   7            SER             A               1          192                 ?
   8            ARG             A               1          196                 ?
   9            ILE             A               1          210                 ?
   10           THR             A               1          211                 ?
   11           CYS             A               1          212                 ?
   12           THR             A               1          213                 ?
   13           GLY             A               1          214                 ?
   14           ASP             A               1          329                 ?
   15           MET             A               1          330                 ?
   16           GLU             A               1          331                 ?
   17           SER             A               1          332                 ?
   18           TYR             A               1          334                 ?
   19           GLN             A               1          335                 ?
   20           TYR             A               1          376                 ?
   21           MET             A               1          380                 ?
   22           LYS             A               1          383                 ?
   23           ILE             A               1          398                 ?
   24           HIS             A               1          401                 ?
   25           PHE             A               1          402                 ?
   26           GLU             A               1          403                 ?
   27           ASP             A               1          404                 ?
   28           LYS             A               1          405                 ?

      auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
   0          570          VAL            A                  1               55
   1          571          MET            A                  1               56
   2          572          ALA            A                  1               57
   3          703          THR            A                  1              188
   4          704          ALA            A                  1              189
   5          705          THR            A                  1              190
   6          706          ALA            A                  1              191
   7          707          SER            A                  1              192
   8          711          ARG            A                  1              196
   9          725          ILE            A                  1              210
   10         726          THR            A                  1              211
   11         727          CYS            A                  1              212
   12         728          THR            A                  1              213
   13         729          GLY            A                  1              214
   14         844          ASP            A                  1              329
   15         845          MET            A                  1              330
   16         846          GLU            A                  1              331
   17         847          SER            A                  1              332
   18         849          TYR            A                  1              334
   19         850          GLN            A                  1              335
   20         891          TYR            A                  1              376
   21         895          MET            A                  1              380
   22         898          LYS            A                  1              383
   23         913          ILE            A                  1              398
   24         916          HIS            A                  1              401
   25         917          PHE            A                  1              402
   26         918          GLU            A                  1              403
   27         919          ASP            A                  1              404
   28         920          LYS            A                  1              405

      pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
   0                      UNP                 Q14191                    570
   1                      UNP                 Q14191                    571
   2                      UNP                 Q14191                    572
   3                      UNP                 Q14191                    703
   4                      UNP                 Q14191                    704
   5                      UNP                 Q14191                    705
   6                      UNP                 Q14191                    706
   7                      UNP                 Q14191                    707
   8                      UNP                 Q14191                    711
   9                      UNP                 Q14191                    725
   10                     UNP                 Q14191                    726
   11                     UNP                 Q14191                    727
   12                     UNP                 Q14191                    728
   13                     UNP                 Q14191                    729
   14                     UNP                 Q14191                    844
   15                     UNP                 Q14191                    845
   16                     UNP                 Q14191                    846
   17                     UNP                 Q14191                    847
   18                     UNP                 Q14191                    849
   19                     UNP                 Q14191                    850
   20                     UNP                 Q14191                    891
   21                     UNP                 Q14191                    895
   22                     UNP                 Q14191                    898
   23                     UNP                 Q14191                    913
   24                     UNP                 Q14191                    916
   25                     UNP                 Q14191                    917
   26                     UNP                 Q14191                    918
   27                     UNP                 Q14191                    919
   28                     UNP                 Q14191                    920

      pdbx_sifts_xref_db_res
   0                       V
   1                       M
   2                       A
   3                       T
   4                       A
   5                       T
   6                       A
   7                       S
   8                       R
   9                       I
   10                      T
   11                      C
   12                      T
   13                      G
   14                      D
   15                      M
   16                      E
   17                      S
   18                      Y
   19                      Q
   20                      Y
   21                      M
   22                      K
   23                      I
   24                      H
   25                      F
   26                      E
   27                      D
   28                      K  }])

In [9]:
news_sites = {
    f"af-{up_id.lower()}-f1": [news_sites[pdb_id][0]["site"][["pdbx_sifts_xref_db_acc", "pdbx_sifts_xref_db_num", "pdbx_sifts_xref_db_res"]],]
    for pdb_id, up_id in ups
}

for pdb_id, up_id in ups:
    if pdb_id == "8jp0":
        up_id = f"af-{up_id.lower()}-f1"
        news_sites[up_id] = [(
            news_sites[up_id][0]
            .replace({"pdbx_sifts_xref_db_acc": {"P32418-2": "P32418"}})
            .loc[news_sites[up_id][0]["pdbx_sifts_xref_db_num"].astype(int) < 800]
        ),]

news_sites

{'af-q14191-f1': [   pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num pdbx_sifts_xref_db_res
  0                  Q14191                    570                      V
  1                  Q14191                    571                      M
  2                  Q14191                    572                      A
  3                  Q14191                    703                      T
  4                  Q14191                    704                      A
  5                  Q14191                    705                      T
  6                  Q14191                    706                      A
  7                  Q14191                    707                      S
  8                  Q14191                    711                      R
  9                  Q14191                    725                      I
  10                 Q14191                    726                      T
  11                 Q14191                    727                      C
  12                 Q14191                    728                      T
  13                 Q14191                    729                      G
  14                 Q14191                    844                      D
  15                 Q14191                    845                      M
  16                 Q14191                    846                      E
  17                 Q14191                    847                      S
  18                 Q14191                    849                      Y
  19                 Q14191                    850                      Q
  20                 Q14191                    891                      Y
  21                 Q14191                    895                      M
  22                 Q14191                    898                      K
  23                 Q14191                    913                      I
  24                 Q14191                    916                      H
  25                 Q14191                    917                      F
  26                 Q14191                    918                      E
  27                 Q14191                    919                      D
  28                 Q14191                    920                      K],
 'af-q13191-f1': [   pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num pdbx_sifts_xref_db_res
  0                  Q13191                    141                      R
  1                  Q13191                    144                      T
  2                  Q13191                    145                      K
  3                  Q13191                    146                      L
  4                  Q13191                    148                      L
  5                  Q13191                    149                      I
  6                  Q13191                    152                      H
  7                  Q13191                    218                      S
  8                  Q13191                    219                      T
  9                  Q13191                    220                      I
  10                 Q13191                    221                      D
  11                 Q13191                    222                      L
  12                 Q13191                    223                      T
  13                 Q13191                    224                      C
  14                 Q13191                    239                      L
  15                 Q13191                    254                      A
  16                 Q13191                    260                      Y
  17                 Q13191                    261                      M
  18                 Q13191                    262                      A
  19                 Q13191                    263                      F
  20                 Q13191                    264                      L
  21                 Q13191                    268                      E
  22                 Q13191                    287                      L
  23                 Q13191                    362                      L
  24                 Q13191                    363                      Y
  25                 Q13191                    364                      C
  26                 Q13191                    366                      M
  27                 Q13191                    367                      G
  28                 Q13191                    368                      S
  29                 Q13191                    369                      T],
 'af-p13569-f1': [   pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num pdbx_sifts_xref_db_res
  0                  P13569                     92                      E
  1                  P13569                     95                      K
  2                  P13569                    310                      F
  3                  P13569                    311                      F
  4                  P13569                    344                      I
  5                  P13569                    345                      V
  6                  P13569                    347                      R
  7                  P13569                    348                      M
  8                  P13569                    353                      Q
  9                  P13569                    920                      V
  10                 P13569                    921                      G
  11                 P13569                    922                      V
  12                 P13569                    923                      A
  13                 P13569                    924                      D
  14                 P13569                    925                      T
  15                 P13569                    927                      L
  16                 P13569                    997                      L
  17                 P13569                   1000                      I
  18                 P13569                   1001                      V
  19                 P13569                   1004                      A
  20                 P13569                   1135                      L
  21                 P13569                   1137                      M
  22                 P13569                   1138                      N
  23                 P13569                   1139                      I
  24                 P13569                   1141                      S
  25                 P13569                   1142                      T
  26                 P13569                   1145                      W],
 'af-p32418-f1': [   pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num pdbx_sifts_xref_db_res
  0                  P32418                    132                      E
  1                  P32418                    133                      T
  2                  P32418                    134                      V
  3                  P32418                    135                      S
  4                  P32418                    137                      L
  5                  P32418                    138                      T
  6                  P32418                    141                      A
  7                  P32418                    200                      H
  8                  P32418                    203                      V
  9                  P32418                    206                      V
  10                 P32418                    207                      T
  11                 P32418                    208                      A
  12                 P32418                    210                      W
  13                 P32418                    211                      S
  14                 P32418                    241                      F
  15                 P32418                    244                      I
  16                 P32418                    245                      C
  17                 P32418                    248                      F
  18                 P32418                    249                      A
  19                 P32418                    256                      L
  20                 P32418                    279                      E],
 'af-q15878-f1': [   pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num pdbx_sifts_xref_db_res
  0                  Q15878                    209                      I
  1                  Q15878                    210                      V
  2                  Q15878                    213                      S
  3                  Q15878                    214                      I
  4                  Q15878                    217                      A
  5                  Q15878                    353                      E
  6                  Q15878                    354                      F
  7                  Q15878                    357                      E
  8                  Q15878                    358                      R
  9                  Q15878                    360                      R
  10                 Q15878                    363                      N
  11                 Q15878                    595                      S
  12                 Q15878                    596                      L
  13                 Q15878                    599                      S
  14                 Q15878                    600                      M
  15                 Q15878                    601                      K
  16                 Q15878                    602                      S
  17                 Q15878                    603                      I
  18                 Q15878                    604                      I
  19                 Q15878                    606                      L
  20                 Q15878                    696                      N
  21                 Q15878                    697                      V
  22                 Q15878                    699                      L
  23                 Q15878                    700                      A
  24                 Q15878                    701                      I
  25                 Q15878                    702                      A
  26                 Q15878                    703                      V
  27                 Q15878                    704                      D
  28                 Q15878                    705                      N]}

In [10]:
news_sites = {
    k: [cif.residues.merge(v[0]),]
    for k, v in news_sites.items()
    for cif in (Cif(k, f"{k}_out.cif"),)
}

news_sites

{'af-q14191-f1': [   label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
  0            VAL             A               1          570                 ?
  1            MET             A               1          571                 ?
  2            ALA             A               1          572                 ?
  3            THR             A               1          703                 ?
  4            ALA             A               1          704                 ?
  5            THR             A               1          705                 ?
  6            ALA             A               1          706                 ?
  7            SER             A               1          707                 ?
  8            ARG             A               1          711                 ?
  9            ILE             A               1          725                 ?
  10           THR             A               1          726                 ?
  11           CYS             A               1          727                 ?
  12           THR             A               1          728                 ?
  13           GLY             A               1          729                 ?
  14           ASP             A               1          844                 ?
  15           MET             A               1          845                 ?
  16           GLU             A               1          846                 ?
  17           SER             A               1          847                 ?
  18           TYR             A               1          849                 ?
  19           GLN             A               1          850                 ?
  20           TYR             A               1          891                 ?
  21           MET             A               1          895                 ?
  22           LYS             A               1          898                 ?
  23           ILE             A               1          913                 ?
  24           HIS             A               1          916                 ?
  25           PHE             A               1          917                 ?
  26           GLU             A               1          918                 ?
  27           ASP             A               1          919                 ?
  28           LYS             A               1          920                 ?

     auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num  \
  0          570          VAL            A                  1
  1          571          MET            A                  1
  2          572          ALA            A                  1
  3          703          THR            A                  1
  4          704          ALA            A                  1
  5          705          THR            A                  1
  6          706          ALA            A                  1
  7          707          SER            A                  1
  8          711          ARG            A                  1
  9          725          ILE            A                  1
  10         726          THR            A                  1
  11         727          CYS            A                  1
  12         728          THR            A                  1
  13         729          GLY            A                  1
  14         844          ASP            A                  1
  15         845          MET            A                  1
  16         846          GLU            A                  1
  17         847          SER            A                  1
  18         849          TYR            A                  1
  19         850          GLN            A                  1
  20         891          TYR            A                  1
  21         895          MET            A                  1
  22         898          LYS            A                  1
  23         913          ILE            A                  1
  24         916          HIS            A                  1
  25         917          PHE            A                  1
  26         918          GLU            A                  1
  27         919          ASP            A                  1
  28         920          LYS            A                  1

     pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_name pdbx_sifts_xref_db_num  \
  0                  Q14191                     UNP                    570
  1                  Q14191                     UNP                    571
  2                  Q14191                     UNP                    572
  3                  Q14191                     UNP                    703
  4                  Q14191                     UNP                    704
  5                  Q14191                     UNP                    705
  6                  Q14191                     UNP                    706
  7                  Q14191                     UNP                    707
  8                  Q14191                     UNP                    711
  9                  Q14191                     UNP                    725
  10                 Q14191                     UNP                    726
  11                 Q14191                     UNP                    727
  12                 Q14191                     UNP                    728
  13                 Q14191                     UNP                    729
  14                 Q14191                     UNP                    844
  15                 Q14191                     UNP                    845
  16                 Q14191                     UNP                    846
  17                 Q14191                     UNP                    847
  18                 Q14191                     UNP                    849
  19                 Q14191                     UNP                    850
  20                 Q14191                     UNP                    891
  21                 Q14191                     UNP                    895
  22                 Q14191                     UNP                    898
  23                 Q14191                     UNP                    913
  24                 Q14191                     UNP                    916
  25                 Q14191                     UNP                    917
  26                 Q14191                     UNP                    918
  27                 Q14191                     UNP                    919
  28                 Q14191                     UNP                    920

     pdbx_sifts_xref_db_res
  0                       V
  1                       M
  2                       A
  3                       T
  4                       A
  5                       T
  6                       A
  7                       S
  8                       R
  9                       I
  10                      T
  11                      C
  12                      T
  13                      G
  14                      D
  15                      M
  16                      E
  17                      S
  18                      Y
  19                      Q
  20                      Y
  21                      M
  22                      K
  23                      I
  24                      H
  25                      F
  26                      E
  27                      D
  28                      K  ],
 'af-q13191-f1': [   label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
  0            ARG             A               1          141                 ?
  1            THR             A               1          144                 ?
  2            LYS             A               1          145                 ?
  3            LEU             A               1          146                 ?
  4            LEU             A               1          148                 ?
  5            ILE             A               1          149                 ?
  6            HIS             A               1          152                 ?
  7            SER             A               1          218                 ?
  8            THR             A               1          219                 ?
  9            ILE             A               1          220                 ?
  10           ASP             A               1          221                 ?
  11           LEU             A               1          222                 ?
  12           THR             A               1          223                 ?
  13           CYS             A               1          224                 ?
  14           LEU             A               1          239                 ?
  15           ALA             A               1          254                 ?
  16           TYR             A               1          260                 ?
  17           MET             A               1          261                 ?
  18           ALA             A               1          262                 ?
  19           PHE             A               1          263                 ?
  20           LEU             A               1          264                 ?
  21           GLU             A               1          268                 ?
  22           LEU             A               1          287                 ?
  23           LEU             A               1          362                 ?
  24           TYR             A               1          363                 ?
  25           CYS             A               1          364                 ?
  26           MET             A               1          366                 ?
  27           GLY             A               1          367                 ?
  28           SER             A               1          368                 ?
  29           THR             A               1          369                 ?

     auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num  \
  0          141          ARG            A                  1
  1          144          THR            A                  1
  2          145          LYS            A                  1
  3          146          LEU            A                  1
  4          148          LEU            A                  1
  5          149          ILE            A                  1
  6          152          HIS            A                  1
  7          218          SER            A                  1
  8          219          THR            A                  1
  9          220          ILE            A                  1
  10         221          ASP            A                  1
  11         222          LEU            A                  1
  12         223          THR            A                  1
  13         224          CYS            A                  1
  14         239          LEU            A                  1
  15         254          ALA            A                  1
  16         260          TYR            A                  1
  17         261          MET            A                  1
  18         262          ALA            A                  1
  19         263          PHE            A                  1
  20         264          LEU            A                  1
  21         268          GLU            A                  1
  22         287          LEU            A                  1
  23         362          LEU            A                  1
  24         363          TYR            A                  1
  25         364          CYS            A                  1
  26         366          MET            A                  1
  27         367          GLY            A                  1
  28         368          SER            A                  1
  29         369          THR            A                  1

     pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_name pdbx_sifts_xref_db_num  \
  0                  Q13191                     UNP                    141
  1                  Q13191                     UNP                    144
  2                  Q13191                     UNP                    145
  3                  Q13191                     UNP                    146
  4                  Q13191                     UNP                    148
  5                  Q13191                     UNP                    149
  6                  Q13191                     UNP                    152
  7                  Q13191                     UNP                    218
  8                  Q13191                     UNP                    219
  9                  Q13191                     UNP                    220
  10                 Q13191                     UNP                    221
  11                 Q13191                     UNP                    222
  12                 Q13191                     UNP                    223
  13                 Q13191                     UNP                    224
  14                 Q13191                     UNP                    239
  15                 Q13191                     UNP                    254
  16                 Q13191                     UNP                    260
  17                 Q13191                     UNP                    261
  18                 Q13191                     UNP                    262
  19                 Q13191                     UNP                    263
  20                 Q13191                     UNP                    264
  21                 Q13191                     UNP                    268
  22                 Q13191                     UNP                    287
  23                 Q13191                     UNP                    362
  24                 Q13191                     UNP                    363
  25                 Q13191                     UNP                    364
  26                 Q13191                     UNP                    366
  27                 Q13191                     UNP                    367
  28                 Q13191                     UNP                    368
  29                 Q13191                     UNP                    369

     pdbx_sifts_xref_db_res
  0                       R
  1                       T
  2                       K
  3                       L
  4                       L
  5                       I
  6                       H
  7                       S
  8                       T
  9                       I
  10                      D
  11                      L
  12                      T
  13                      C
  14                      L
  15                      A
  16                      Y
  17                      M
  18                      A
  19                      F
  20                      L
  21                      E
  22                      L
  23                      L
  24                      Y
  25                      C
  26                      M
  27                      G
  28                      S
  29                      T  ],
 'af-p13569-f1': [   label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
  0            GLU             A               1           92                 ?
  1            LYS             A               1           95                 ?
  2            PHE             A               1          310                 ?
  3            PHE             A               1          311                 ?
  4            ILE             A               1          344                 ?
  5            VAL             A               1          345                 ?
  6            ARG             A               1          347                 ?
  7            MET             A               1          348                 ?
  8            GLN             A               1          353                 ?
  9            VAL             A               1          920                 ?
  10           GLY             A               1          921                 ?
  11           VAL             A               1          922                 ?
  12           ALA             A               1          923                 ?
  13           ASP             A               1          924                 ?
  14           THR             A               1          925                 ?
  15           LEU             A               1          927                 ?
  16           LEU             A               1          997                 ?
  17           ILE             A               1         1000                 ?
  18           VAL             A               1         1001                 ?
  19           ALA             A               1         1004                 ?
  20           LEU             A               1         1135                 ?
  21           MET             A               1         1137                 ?
  22           ASN             A               1         1138                 ?
  23           ILE             A               1         1139                 ?
  24           SER             A               1         1141                 ?
  25           THR             A               1         1142                 ?
  26           TRP             A               1         1145                 ?

     auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num  \
  0           92          GLU            A                  1
  1           95          LYS            A                  1
  2          310          PHE            A                  1
  3          311          PHE            A                  1
  4          344          ILE            A                  1
  5          345          VAL            A                  1
  6          347          ARG            A                  1
  7          348          MET            A                  1
  8          353          GLN            A                  1
  9          920          VAL            A                  1
  10         921          GLY            A                  1
  11         922          VAL            A                  1
  12         923          ALA            A                  1
  13         924          ASP            A                  1
  14         925          THR            A                  1
  15         927          LEU            A                  1
  16         997          LEU            A                  1
  17        1000          ILE            A                  1
  18        1001          VAL            A                  1
  19        1004          ALA            A                  1
  20        1135          LEU            A                  1
  21        1137          MET            A                  1
  22        1138          ASN            A                  1
  23        1139          ILE            A                  1
  24        1141          SER            A                  1
  25        1142          THR            A                  1
  26        1145          TRP            A                  1

     pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_name pdbx_sifts_xref_db_num  \
  0                  P13569                     UNP                     92
  1                  P13569                     UNP                     95
  2                  P13569                     UNP                    310
  3                  P13569                     UNP                    311
  4                  P13569                     UNP                    344
  5                  P13569                     UNP                    345
  6                  P13569                     UNP                    347
  7                  P13569                     UNP                    348
  8                  P13569                     UNP                    353
  9                  P13569                     UNP                    920
  10                 P13569                     UNP                    921
  11                 P13569                     UNP                    922

# Our results

In [11]:
model5_results = {
    holod["pdb_id"]: {
        pocket["Pocket"]: {
            "prob": pocket["Allosteric score"],
            "residues": Pocket(f'{holod["pocketsdir"]}/{pocket["Pocket"]}_atm.cif').residues
        }
        for i, pocket in pd.read_csv(holod["predsf"]).iterrows()
    }
    for holo, holod in news.items()

}

model5_results

{'af-q14191-f1': {'pocket1': {'prob': 0.6842876076698303,
   'residues':     label_comp_id label_asym_id label_seq_id pdbx_PDB_ins_code auth_seq_id  \
   0             ILE             A         1177                 ?        1177
   2             GLN             A          608                 ?         608
   4             ALA             A          831                 ?         831
   6             ASN             A          829                 ?         829
   7             ALA             A         1176                 ?        1176
   ..            ...           ...          ...               ...         ...
   177           TYR             A          839                 ?         839
   182           GLN             A          850                 ?         850
   187           ILE             A          883                 ?         883
   196           ALA             A          841                 ?         841
   204           ALA             A          820                 ?         820

       auth_asym_id
   0              A
   2              A
   4              A
   6              A
   7              A
   ..           ...
   177            A
   182            A
   187            A
   196            A
   204            A

   [61 rows x 6 columns]},
  'pocket11': {'prob': 0.2303604185581207,
   'residues':    label_comp_id label_asym_id label_seq_id pdbx_PDB_ins_code auth_seq_id  \
   0            PHE             A           46                 ?          46
   1            LEU             A          190                 ?         190
   6            GLU             A           48                 ?          48
   8            LEU             A          211                 ?         211
   11           LYS             A          210                 ?         210
   12           ILE             A           53                 ?          53
   14           GLU             A          207                 ?         207
   15           TYR             A           55                 ?          55
   24           LEU             A           47                 ?          47
   26           ILE             A          195                 ?         195
   27           ASP             A          192                 ?         192
   29           ASP             A          208                 ?         208
   35           THR             A          215                 ?         215
   36           ASP             A          216                 ?         216
   37           LEU             A          189                 ?         189
   40           TYR             A          212                 ?         212
   51           LYS             A          191                 ?         191

      auth_asym_id
   0             A
   1             A
   6             A
   8             A
   11            A
   12            A
   14            A
   15            A
   24            A
   26            A
   27            A
   29            A
   35            A
   36            A
   37            A
   40            A
   51            A  },
  'pocket7': {'prob': 0.0995553731918335,
   'residues':    label_comp_id label_asym_id label_seq_id pdbx_PDB_ins_code auth_seq_id  \
   0            ARG             A          910                 ?         910
   1            ILE             A          913                 ?         913
   6            LEU             A          737                 ?         737
   7            ASP             A          731                 ?         731
   10           LEU             A          735                 ?         735
   12           ARG             A          732                 ?         732
   13           ILE             A          852                 ?         852
   17           PHE             A          730                 ?         730
   18           LEU             A          914                 ?         914
   23           GLY             A          853                 ?         853
   25           TYR             A          849                 ?         849
   29           THR             A          573                 ?         573

      auth_asym_id
   0             A
   1             A
   6             A
   7             A
   10            A
   12            A
   13            A
   17            A
   18            A
   23            A
   25            A
   29            A  },
  'pocket14': {'prob': 0.0190463811159133,
   'residues':    label_comp_id label_asym_id label_seq_id pdbx_PDB_ins_code auth_seq_id  \
   0            ARG             A          732                 ?         732
   1            GLY             A          574                 ?         574
   4            TYR             A          575                 ?         575
   6            ASP             A          731                 ?         731
   7            PRO             A          733                 ?         733
   8            ASP             A          858                 ?         858
   9            ARG             A          857                 ?         857
   10           GLY             A          859                 ?         859
   12           LYS             A          550                 ?         550
   13           GLY             A          856                 ?         856
   15           THR             A          573                 ?         573
   16           ALA             A          572                 ?         572
   19           GLY             A          729                 ?         729
   23           ASN             A          734                 ?         734
   26           THR             A          728                 ?         728
   29           VAL             A          552                 ?         552
   30           CYS             A          727                 ?         727

      auth_asym_id
   0             A
   1             A
   4             A
   6             A
   7             A
   8             A
   9             A
   10            A
   12            A
   13            A
   15            A
   16            A
   19            A
   23            A
   26            A
   29            A
   30            A  },
  'pocket2': {'prob': 0.0054057333618402,
   'residues':     label_comp_id label_asym_id label_seq_id pdbx_PDB_ins_code auth_seq_id  \
   0             PHE             A          544                 ?         544
   1             SER             A          612                 ?         612
   4             HIS             A          546                 ?         546
   6             LYS             A         1208                 ?        1208
   8             SER             A         1205                 ?        1205
   9             LEU             A          609                 ?         609
   11            GLN             A          608                 ?         608
   14            ILE             A          614                 ?         614
   15            SER             A          547                 ?         547
   16            ASP             A         1202                 ?        1202
   17            SER             A          548                 ?         548
   20            GLY             A         1203                 ?        1203
   21            GLN             A          582                 ?         582
   22            GLN             A          605                 ?         605
   28            ASN             A          829                 ?         829
   29            SER             A          578                 ?         578
   31            LYS             A          577                 ?         577
   32            ARG             A          857                 ?         857
   34            GLY             A          574                 ?         574
   37            LYS             A          550                 ?         550
   39            GLN             A          553                 ?         553
   42            ALA             A          831                 ?         831
   44            LEU             A          579                 ?         579
   47            GLY             A          576                 ?         576
   52            LEU             A          540                 ?         540
   53            PHE             A          549                 ?         549
   62            TYR             A          575                 ?         575
   65            THR             A          573                 ?         573
   68            ALA             A          572                 ?         572
   70            LEU             A          601                 ?         601
   72            ILE             A          828                 ?         828
   84            GLU             A          669                 ?         669
   85            ARG             A          854                 ?         854
   86            GLN             A          850                 ?         850
   88            ASP             A          668                 ?         668
   92            PHE             A          581                 ?         581
   102           MET             A          826                 ?         826
   107           LEU             A          702                 ?         702
   109           THR             A          705                 ?         705
   112           HIS             A          671                 ?         671
   114           ALA             A          704                 ?         704
   118           TYR             A          849                 ?         849

       auth_asym_id
   0              A
   1              A
   4              A
   6              A
   8              A
   9              A
   11             A
   14             A
   15             A
   16             A
   17             A
   20             A
   21             A
   22             A
   28             A
   29             A
   31             A
   32             A
   34             A
   37             A
   39             A
   42             A
   44             A
   47             A
   52             A
   53             A
   62             A
   65             A
   68             A
   70             A
   72             A
   84             A
   85             A
   86             A
   88             A
   92             A
   102            A
   107            A
   109            A
   112            A
   114            A
   118            A  },
  'pocket37': {'prob': 0.0031842859461903,
   'residues':    label_comp_id label_asym_id label_seq_id pdbx_PDB_ins_code auth_seq_id  \
   0            ARG             A          940                 ?         940
   1            LEU             A          943                 ?         943
   3            GLU             A          933                 ?         933
   4            SER             A         1058                 ?        1058
   5            ASP             A          958                 ?         958
   8            THR             A          932                 ?         932
   11           PRO             A          961                 ?         961
   12           GLN             A         1059                 ?        1059
   15           PHE             A          964                 ?         964
   16           ALA             A         1054                 ?        1054
   18           MET             A          930                 ?         930
   19           GLY             A          931                 ?         931
   26           GLU             A         1057                 ?        1057
   30           TRP             A         1050                 ?        1050
   31           TRP             A          957                 ?         957
   36           SER             A          956                 ?         956
   39           ASP             A          944                 ?         944
   44           ARG             A          942                 ?         942
   45           LEU             A         1003                 ?        1003
   46           LYS             A          965                 ?         965
   47           THR             A         1006                 ?        1006
   54           LYS             A          934                 ?         934
   62           GLY             A          960                 ?         960
   64           ASN             A         1055                 ?        1055
   65           THR             A         1056                 ?        1056
   79           SER             A         1060                 ?        1060

      auth_asym_id
   0             A
   1             A
   3             A
   4             A
   5             A
   8             A
   11            A
   12            A
   15            A
   16            A
   18            A
   19            A
   26            A
   30            A
   31            A
   36            A
   39            A
   44            A
   45            A
   46            A
   47            A
   54            A
   62            A
   64            A
   65            A
   79            A  },
  'pocket12': {'prob': 0.0029302192851901,
   'residues':    label_comp_id label_asym_id label_seq_id pdbx_PDB_ins_code auth_seq_id  \
   0            GLY             A          988                 ?         988
   1            ASN             A          990                 ?         990
   4            ARG             A          987                 ?         987
   5            SER             A          989                 ?         989
   7            GLU             A         1012                 ?        1012
   10           LEU             A          984                 ?         984
   12           GLY             A          980                 ?         980
   13           LYS             A         1016                 ?        1016
   17           PHE             A          977                 ?         977
   18           ARG             A          993                 ?         993
   25           LEU             A          981                 ?         981
   27           GLY             A          978                 ?         978
   30           LYS             A         1039                 ?        1039
   31           MET             A         1038                 ?        1038
   33           PHE             A         1037                 ?        1037
   48           ILE             A          979                 ?         979
   51           ILE             A          983                 ?         983

      auth_asym_id
   0             A
   1             A
   4             A
   5             A
   7             A
   10            A
   12            A
   13            A
   17            A
   18            A
   25            A
   27            A
   30            A
   31            A
   33            A
   48            A
   51            A  },
  'pocket10': {'prob': 0.0018549936357885,
   'residues':    label_comp_id label_asym_id label_seq_id pdbx_PDB_ins_code auth_seq_id  \
   0            LEU             A          177                 ?         177
   1            ASP             A           82                 ?          82
   2            LYS             A          191                 ?         191
   3            ASP             A          216                 ?         216
   4            PHE             A           81                 ?          81
   5            GLY             A          137                 ?         137
   7            ALA             A          136                 ?         136
   9            GLY             A          220                 ?         220
   12           VAL             A          138                 ?         138
   13           ALA             A          217                 ?         217
   18           SER             A          176                 ?         176
   22           ILE             A          140                 ?         140
   23           ASP             A          143                 ?         143

      auth_asym_id
   0             A
   1             A
   2             A
   3             A
   4             A
   5             A
   7             A
   9             A
   12            A
   13            A
   18            A
   22            A
   23            A  },
  'pocket6': {'prob': 0.0011461307294666,
   'residues':    label_comp_id label_asym_id label_seq_id pdbx_PDB_ins_code auth_seq_id  \
   0            ASN             A         1181                 ?        1181
   1            ARG             A         1164                 ?        1164
   3            ALA             A         1176                 ?        1176
   4            ASP             A          832                 ?         832
   7            ASP             A          813                 ?         813
   8            LYS             A          830                 ?         830
   11           ASP             A          858                 ?         858
   13           ALA             A          831                 ?         831
   16           THR             A         1180                 ?        1180
   18           PRO             A         1175                 ?        1175
   21           LYS             A         1182                 ?        1182
   24           VAL             A          811                 ?         811
   29           ARG             A          857                 ?         857

      auth_asym_id
   0             A
   1             A
   3             A
   4             A
   7             A
   8             A
   11            A
   13            A
   16            A
   18            A
   21            A
   24            A
   29            A  },
  'pocket5': {'prob': 0.000936962373089,
   'residues':    label_comp_id label_asym_id label_seq_id pdbx_PDB_ins_code auth_seq_id  \
   0            LYS             A          892                 ?         892
   1            MET             A          895                 ?         895
   2            ASP             A          844                 ?         844
   4            GLU             A          846                 ?         846
   7            HIS             A          678                 ?         678
   10           TYR             A          891                 ?         891
   11           TRP             A          676                 ?         676
   12           PHE             A          917                 ?         917
   13           HIS             A          916                 ?         916
   16           SER             A          707                 ?         707
   19           ALA             A          706                 ?         706
   22           THR             A          705                 ?         705
   28           ILE             A          710                 ?         710
   29           HIS             A          671                 ?         671
   33           GLY             A          677                 ?         677

      auth_asym_id
   0             A
   1             A
   2             A
   4             A
   7             A
   10            A
   11            A
   12            A
   13            A
   16            A
   19            A
   22            A
   28            A
   29            A
   33            A  },
  'pocket9': {'prob': 0.0007185192080214,
   'residues':    label_comp_id label_asym_id label_seq_id pdbx_PDB_ins_code auth_seq_id  \
   0            LYS             A         1039                 ?        1039
   1            GLU             A         1030                 ?        1030
   3            ILE             A         1040                 ?        1040
   6            LYS             A         1016                 ?        1016
   8            ARG             A         1020                 ?        1020
   10           SER             A         1019                 ?        1019
   11           ILE             A          979                 ?         979

In [12]:
model5_results.keys()

dict_keys(['af-q14191-f1', 'af-q13191-f1', 'af-p13569-f1', 'af-p32418-f1', 'af-q15878-f1'])

# Results - old

## AllositePro

allositepro_resultsf = "AllositePro/allositepro_results.pkl"

with open(allositepro_resultsf, "rb") as f:
    allositepro_results = {k: v for k,v in pickle.load(f).items() if k in news}

len(allositepro_results), allositepro_results

allositepro_results.pop("7sns")

All output pockets are predicted positive.

allositepro_results = {
    pdb: {
        pocket: {
            "pred": 1,
            **pocketd
        }
        for pocket, pocketd in pockets.items()
    }
    for pdb, pockets in allositepro_results.items()
}
allositepro_results

## PASSer

passer_resultsf = "PASSer/passer_results.pkl"

with open(passer_resultsf, "rb") as f:
    passer_results = {k1: {k2: v2 for k2, v2 in v1.items() if k2 in news} for k1, v1 in pickle.load(f).items()}

len(passer_results), tuple(len(v) for v in passer_results.values()), passer_results

Top 3 pockets for each PDB are predicted positive.

passer_results = {
    model: {
        pdb: {
            pocket: {
                "pred": 1 if i <=2 else 0,
                **pocketd
            }
            for i, (pocket, pocketd) in enumerate( 
                sorted(
                    pockets.items(), 
                    key=lambda x: x[-1]["prob/score"], 
                    reverse=True
                )
            )
        }
        for pdb, pockets in pdbs.items()
    }
    for model, pdbs in passer_results.items()
}
passer_results

## DeepAllo

deepallo_resultsf = "DeepAllo/deepallo_results.pkl"

with open(deepallo_resultsf, "rb") as f:
    deepallo_results = pickle.load(f)

len(deepallo_results), deepallo_results

deepallo_results = {
    pdb: {
        pocket: {
            "prob": 0, # will be replaced by the real prob of the top3 pockets if it's in pocketd
            **pocketd
        }
        for pocket, pocketd in pockets.items()
    }
    for pdb, pockets in deepallo_results.items()
}
deepallo_results

deepallo_results["7sns"]

## STINGAllo

stingallo_resultsf = "STINGAllo/stingallo_results.pkl"

with open(stingallo_resultsf, "rb") as f:
    stingallo_results = pickle.load(f)

len(stingallo_results), stingallo_results

stingallo_results = {
    pdb: {
        pocket: {
            "pred": 1,
            **pocketd
        }
        for pocket, pocketd in pockets.items()
    }
    for pdb, pockets in stingallo_results.items()
}
stingallo_results

## AlloFusion

allofusion_resultsf = "AlloFusion/allofusion_results.pkl"

with open(allofusion_resultsf, "rb") as f:
    allofusion_results = {k.upper() if k.startswith("af") else k: v for k, v in pickle.load(f).items()}

len(allofusion_results), allofusion_results

allofusion_results = {
    pdb: {
        f"pocket_{res['auth_asym_id']}_{res['auth_seq_id']}": {
            "pred": 1,
            "residues": res.to_frame().T
        }
        for pocket, pocketd in pockets.items()
        for i, res in pocketd["residues"].iterrows()
    }
    for pdb, pockets in allofusion_results.items()
}
allofusion_results

## AllosES

alloses_resultsf = "AllosES/alloses_results.pkl"

with open(alloses_resultsf, "rb") as f:
    alloses_results = pickle.load(f)

len(alloses_results), alloses_results

Positive preds. above 0.5 probability (average) and upper pdb name for AlphaFold model.

alloses_results = {
    pdb if "af" not in pdb.lower() else pdb.upper(): {
        pocket: {
            "pred": 1 if pocketd["pro_ave"] >= 0.5 else 0,
            **pocketd
        }
        for pocket, pocketd in pockets.items()
    }
    for pdb, pockets in alloses_results.items()
}
alloses_results

alloses_results["7sns"]

## MEF-AlloSite

import json

Top 3 pockets for each PDB are predicted positive.

mefallosite_resultsf = "MEF-AlloSite/mef-allosite_results.json"

with open(mefallosite_resultsf, "r") as f:
    mefallosite_results = json.load(f)

len(mefallosite_results), mefallosite_results

mefallosite_results = {
    pdb if "af" not in pdb.lower() else pdb.upper(): {
        pocket: {
            k: v if k != "residues" else pd.DataFrame(v)
            for k, v in pocketd.items()
        }
        for pocket, pocketd in pockets.items()
    } 
    for pdb, pockets in mefallosite_results.items()
}

mefallosite_results

## ALLO

Top pocket is taken as positive prediction.

allo_resultsf = "ALLO/ALLO_results.json"

with open(allo_resultsf, "r") as f:
    allo_results = json.load(f)

len(allo_results), allo_results

allo_results = {
    pdb: {
        pocket: {
            k: v if k != "residues" else pd.DataFrame(v)
            for k, v in pocketd.items()
        }
        for pocket, pocketd in pockets.items()
    } 
    for pdb, pockets in allo_results.items()
}

allo_results

# Results - new

## All models

In [13]:
defaults = { "all_pockets_in_output": True, "prob_key": "prob" }

models = {
    "model5": { "results": model5_results, **defaults, "labelling": None },
    
    # "allositepro": { "results": allositepro_results, "all_pockets_in_output": False, "prob_key": "hitScore" },
    # "stingallo": { "results": stingallo_results, "all_pockets_in_output": False, "prob_key": None },
    # "allofusion": { "results": allofusion_results, "all_pockets_in_output": False, "prob_key": None },
    
    # "passer_ensemble": { "results": passer_results["ensemble"], **defaults, "prob_key": "prob/score" },
    # "passer_automl": { "results": passer_results["automl"], **defaults, "prob_key": "prob/score" },
    # "passer_rank": { "results": passer_results["rank"], **defaults, "prob_key": "prob/score" },
    # "deepallo": { "results": deepallo_results, **defaults },
    # "alloses": { "results": alloses_results, **defaults, "prob_key": "pro_ave" },
    # "mefallosite": { "results": mefallosite_results, **defaults },
    # "allo": { "results": allo_results, **defaults },
}
models

{'model5': {'results': {'af-q14191-f1': {'pocket1': {'prob': 0.6842876076698303,
     'residues':     label_comp_id label_asym_id label_seq_id pdbx_PDB_ins_code auth_seq_id  \
     0             ILE             A         1177                 ?        1177
     2             GLN             A          608                 ?         608
     4             ALA             A          831                 ?         831
     6             ASN             A          829                 ?         829
     7             ALA             A         1176                 ?        1176
     ..            ...           ...          ...               ...         ...
     177           TYR             A          839                 ?         839
     182           GLN             A          850                 ?         850
     187           ILE             A          883                 ?         883
     196           ALA             A          841                 ?         841
     204           ALA             A          820                 ?         820

         auth_asym_id
     0              A
     2              A
     4              A
     6              A
     7              A
     ..           ...
     177            A
     182            A
     187            A
     196            A
     204            A

     [61 rows x 6 columns]},
    'pocket11': {'prob': 0.2303604185581207,
     'residues':    label_comp_id label_asym_id label_seq_id pdbx_PDB_ins_code auth_seq_id  \
     0            PHE             A           46                 ?          46
     1            LEU             A          190                 ?         190
     6            GLU             A           48                 ?          48
     8            LEU             A          211                 ?         211
     11           LYS             A          210                 ?         210
     12           ILE             A           53                 ?          53
     14           GLU             A          207                 ?         207
     15           TYR             A           55                 ?          55
     24           LEU             A           47                 ?          47
     26           ILE             A          195                 ?         195
     27           ASP             A          192                 ?         192
     29           ASP             A          208                 ?         208
     35           THR             A          215                 ?         215
     36           ASP             A          216                 ?         216
     37           LEU             A          189                 ?         189
     40           TYR             A          212                 ?         212
     51           LYS             A          191                 ?         191

        auth_asym_id
     0             A
     1             A
     6             A
     8             A
     11            A
     12            A
     14            A
     15            A
     24            A
     26            A
     27            A
     29            A
     35            A
     36            A
     37            A
     40            A
     51            A  },
    'pocket7': {'prob': 0.0995553731918335,
     'residues':    label_comp_id label_asym_id label_seq_id pdbx_PDB_ins_code auth_seq_id  \
     0            ARG             A          910                 ?         910
     1            ILE             A          913                 ?         913
     6            LEU             A          737                 ?         737
     7            ASP             A          731                 ?         731
     10           LEU             A          735                 ?         735
     12           ARG             A          732                 ?         732
     13           ILE             A          852                 ?         852
     17           PHE             A          730                 ?         730
     18           LEU             A          914                 ?         914
     23           GLY             A          853                 ?         853
     25           TYR             A          849                 ?         849
     29           THR             A          573                 ?         573

        auth_asym_id
     0             A
     1             A
     6             A
     7             A
     10            A
     12            A
     13            A
     17            A
     18            A
     23            A
     25            A
     29            A  },
    'pocket14': {'prob': 0.0190463811159133,
     'residues':    label_comp_id label_asym_id label_seq_id pdbx_PDB_ins_code auth_seq_id  \
     0            ARG             A          732                 ?         732
     1            GLY             A          574                 ?         574
     4            TYR             A          575                 ?         575
     6            ASP             A          731                 ?         731
     7            PRO             A          733                 ?         733
     8            ASP             A          858                 ?         858
     9            ARG             A          857                 ?         857
     10           GLY             A          859                 ?         859
     12           LYS             A          550                 ?         550
     13           GLY             A          856                 ?         856
     15           THR             A          573                 ?         573
     16           ALA             A          572                 ?         572
     19           GLY             A          729                 ?         729
     23           ASN             A          734                 ?         734
     26           THR             A          728                 ?         728
     29           VAL             A          552                 ?         552
     30           CYS             A          727                 ?         727

        auth_asym_id
     0             A
     1             A
     4             A
     6             A
     7             A
     8             A
     9             A
     10            A
     12            A
     13            A
     15            A
     16            A
     19            A
     23            A
     26            A
     29            A
     30            A  },
    'pocket2': {'prob': 0.0054057333618402,
     'residues':     label_comp_id label_asym_id label_seq_id pdbx_PDB_ins_code auth_seq_id  \
     0             PHE             A          544                 ?         544
     1             SER             A          612                 ?         612
     4             HIS             A          546                 ?         546
     6             LYS             A         1208                 ?        1208
     8             SER             A         1205                 ?        1205
     9             LEU             A          609                 ?         609
     11            GLN             A          608                 ?         608
     14            ILE             A          614                 ?         614
     15            SER             A          547                 ?         547
     16            ASP             A         1202                 ?        1202
     17            SER             A          548                 ?         548
     20            GLY             A         1203                 ?        1203
     21            GLN             A          582                 ?         582
     22            GLN             A          605                 ?         605
     28            ASN             A          829                 ?         829
     29            SER             A          578                 ?         578
     31            LYS             A          577                 ?         577
     32            ARG             A          857                 ?         857
     34            GLY             A          574                 ?         574
     37            LYS             A          550                 ?         550
     39            GLN             A          553                 ?         553
     42            ALA             A          831                 ?         831
     44            LEU             A          579                 ?         579
     47            GLY             A          576                 ?         576
     52            LEU             A          540                 ?         540
     53            PHE             A          549                 ?         549
     62            TYR             A          575                 ?         575
     65            THR             A          573                 ?         573
     68            ALA             A          572                 ?         572
     70            LEU             A          601                 ?         601
     72            ILE             A          828                 ?         828
     84            GLU             A          669                 ?         669
     85            ARG             A          854                 ?         854
     86            GLN             A          850                 ?         850
     88            ASP             A          668                 ?         668
     92            PHE             A          581                 ?         581
     102           MET             A          826                 ?         826
     107           LEU             A          702                 ?         702
     109           THR             A          705                 ?         705
     112           HIS             A          671                 ?         671
     114           ALA             A          704                 ?         704
     118           TYR             A          849                 ?         849

         auth_asym_id
     0              A
     1              A
     4              A
     6              A
     8              A
     9              A
     11             A
     14             A
     15             A
     16             A
     17             A
     20             A
     21             A
     22             A
     28             A
     29             A
     31             A
     32             A
     34             A
     37             A
     39             A
     42             A
     44             A
     47             A
     52             A
     53             A
     62             A
     65             A
     68             A
     70             A
     72             A
     84             A
     85             A
     86             A
     88             A
     92             A
     102            A
     107            A
     109            A
     112            A
     114            A
     118            A  },
    'pocket37': {'prob': 0.0031842859461903,
     'residues':    label_comp_id label_asym_id label_seq_id pdbx_PDB_ins_code auth_seq_id  \
     0            ARG             A          940                 ?         940
     1            LEU             A          943                 ?         943
     3            GLU             A          933                 ?         933
     4            SER             A         1058                 ?        1058
     5            ASP             A          958                 ?         958
     8            THR             A          932                 ?         932
     11           PRO             A          961                 ?         961
     12           GLN             A         1059                 ?        1059
     15           PHE             A          964                 ?         964
     16           ALA             A         1054                 ?        1054
     18           MET             A          930                 ?         930
     19           GLY             A          931                 ?         931
     26           GLU             A         1057                 ?        1057
     30           TRP             A         1050                 ?        1050
     31           TRP             A          957                 ?         957
     36           SER             A          956                 ?         956
     39           ASP             A          944                 ?         944
     44           ARG             A          942                 ?         942
     45           LEU             A         1003                 ?        1003
     46           LYS             A          965                 ?         965
     47           THR             A         1006                 ?        1006
     54           LYS             A          934                 ?         934
     62           GLY             A          960                 ?         960
     64           ASN             A         1055                 ?        1055
     65           THR             A         1056                 ?        1056
     79           SER             A         1060                 ?        1060

        auth_asym_id
     0             A
     1             A
     3             A
     4             A
     5             A
     8             A
     11            A
     12            A
     15            A
     16            A
     18            A
     19            A
     26            A
     30            A
     31            A
     36            A
     39            A
     44            A
     45            A
     46            A
     47            A
     54            A
     62            A
     64            A
     65            A
     79            A  },
    'pocket12': {'prob': 0.0029302192851901,
     'residues':    label_comp_id label_asym_id label_seq_id pdbx_PDB_ins_code auth_seq_id  \
     0            GLY             A          988                 ?         988
     1            ASN             A          990                 ?         990
     4            ARG             A          987                 ?         987
     5            SER             A          989                 ?         989
     7            GLU             A         1012                 ?        1012
     10           LEU             A          984                 ?         984
     12           GLY             A          980                 ?         980
     13           LYS             A         1016                 ?        1016
     17           PHE             A          977                 ?         977
     18           ARG             A          993                 ?         993
     25           LEU             A          981                 ?         981
     27           GLY             A          978                 ?         978
     30           LYS             A         1039                 ?        1039
     31           MET             A         1038                 ?        1038
     33           PHE             A         1037                 ?        1037
     48           ILE             A          979                 ?         979
     51           ILE             A          983                 ?         983

        auth_asym_id
     0             A
     1             A
     4             A
     5             A
     7             A
     10            A
     12            A
     13            A
     17            A
     18            A
     25            A
     27            A
     30            A
     31            A
     33            A
     48            A
     51            A  },
    'pocket10': {'prob': 0.0018549936357885,
     'residues':    label_comp_id label_asym_id label_seq_id pdbx_PDB_ins_code auth_seq_id  \
     0            LEU             A          177                 ?         177
     1            ASP             A           82                 ?          82
     2            LYS             A          191                 ?         191
     3            ASP             A          216                 ?         216
     4            PHE             A           81                 ?          81
     5            GLY             A          137                 ?         137
     7            ALA             A          136                 ?         136
     9            GLY             A          220                 ?         220
     12           VAL             A          138                 ?         138
     13           ALA             A          217                 ?         217
     18           SER             A          176                 ?         176
     22           ILE             A          140                 ?         140
     23           ASP             A          143                 ?         143

        auth_asym_id
     0             A
     1             A
     2             A
     3             A
     4             A
     5             A
     7             A
     9             A
     12            A
     13            A
     18            A
     22            A
     23            A  },
    'pocket6': {'prob': 0.0011461307294666,
     'residues':    label_comp_id label_asym_id label_seq_id pdbx_PDB_ins_code auth_seq_id  \
     0            ASN             A         1181                 ?        1181
     1            ARG             A         1164                 ?        1164
     3            ALA             A         1176                 ?        1176
     4            ASP             A          832                 ?         832
     7            ASP             A          813                 ?         813
     8            LYS             A          830                 ?         830
     11           ASP             A          858                 ?         858
     13           ALA             A          831                 ?         831
     16           THR             A         1180                 ?        1180
     18           PRO             A         1175                 ?        1175
     21           LYS             A         1182                 ?        1182
     24           VAL             A          811                 ?         811
     29           ARG             A          857                 ?         857

        auth_asym_id
     0             A
     1             A
     3             A
     4             A
     7             A
     8             A
     11            A
     13            A
     16            A
     18            A
     21            A
     24            A
     29            A  },
    'pocket5': {'prob': 0.000936962373089,
     'residues':    label_comp_id label_asym_id label_seq_id pdbx_PDB_ins_code auth_seq_id  \
     0            LYS             A          892                 ?         892
     1            MET             A          895                 ?         895
     2            ASP             A          844                 ?         844
     4            GLU             A          846                 ?         846
     7            HIS             A          678                 ?         678
     10           TYR             A          891                 ?         891
     11           TRP             A          676                 ?         676
     12           PHE             A          917                 ?         917
     13           HIS             A          916                 ?         916
     16           SER             A          707                 ?         707
     19           ALA             A          706                 ?         706
     22           THR             A          705                 ?         705
     28           ILE             A          710                 ?         710
     29           HIS             A          671                 ?         671
     33           GLY             A          677                 ?         677

        auth_asym_id
     0             A
     1             A
     2             A
     4             A
     7             A
     10            A
     11            A
     12            A
     13            A

# Labelling - new

In [14]:
# Percentage of residues of "one" in "other"
get_overlap = lambda one, other: (
    len( one.merge(other) ) / len(one)
)

def get_label(overlaps, site_in_pocket=None, pocket_in_site=None):
    assert not (site_in_pocket==None and pocket_in_site==None)
    
    if site_in_pocket is None:
        return int( overlaps["pocket_in_site"] >= pocket_in_site )
    if pocket_in_site is None:
        return int( overlaps["site_in_pocket"] >= site_in_pocket )
    return int( overlaps["site_in_pocket"] >= site_in_pocket or overlaps["pocket_in_site"] >= pocket_in_site )

In [15]:
# get_overlaps = lambda pdb, pocketd: {
#     name: get_overlap(*one_in_other) 
#         for site in news_sites[pdb]
#             for name, one_in_other in (
#                 ("pocket_in_site", (pocketd["residues"], site["site"])),
#                 ("site_in_pocket", (site["site"], pocketd["residues"])),
#             )
# }

get_overlaps = lambda pdb, pocketd: max(
    (
        {
            name: get_overlap(*one_in_other)
            for name, one_in_other in (
                ("pocket_in_site", (pocketd["residues"], site)),
                ("site_in_pocket", (site, pocketd["residues"])),
            )
        }
        for site in news_sites[pdb]
    ),
    key=lambda x: x["site_in_pocket"]
)



# get_overlaps_special = lambda pdb, pocketd: {
#     name: get_overlap(*one_in_other) 
#         for pocketres in (pocketd["residues"],)
#             for sited in news_sites[pdb]
#                 for site in (sited["site"].query(f"auth_asym_id == '{pocketres.auth_asym_id.unique().item()}'"),)
#                     for name, one_in_other in (
#                         ("pocket_in_site", (pocketres, site)),
#                         ("site_in_pocket", (site, pocketres)),
#                     )
# }

get_overlaps_special = lambda pdb, pocketd: max(
    (
        {
            name: get_overlap(*one_in_other)
            for name, one_in_other in (
                ("pocket_in_site", (pocketres, site)),
                ("site_in_pocket", (site, pocketres)),
            )
        }
        for pocketres in (pocketd["residues"],)
            for sitei in news_sites[pdb]
                for site in (sitei.query(f"auth_asym_id == '{pocketres.auth_asym_id.unique().item()}'"),)
    ),
    key=lambda x: x["site_in_pocket"]
)

In [16]:
# special_7sns_sc will never be used
def label_results(resultsd, site_in_pocket=0.65, pocket_in_site=None, prob_key=None, topx=False, special_7sns_sc=False):
    df = pd.DataFrame((
        {
            "pdb": pdb,
            "pocket": pocket,
            **{"prob": pocketd[prob_key] for prob_key in (prob_key,) if prob_key is not None},
            # "pred": pocketd["pred"],
            "label": get_label(overlaps, site_in_pocket, pocket_in_site),
            "max_overlap": max(overlaps.values()),
            **overlaps,
        }
        for pdb, pockets in resultsd.items()
        for pocket, pocketd in pockets.items()
        for overlaps in ((
            get_overlaps_special(pdb, pocketd)
            if special_7sns_sc and pdb == "7sns"
            else get_overlaps(pdb, pocketd)
        ),)
    ))
    
    if prob_key is not None and topx:
        df["pred"] = (
            # Start from a Series where each value/row (sample/pocket) is the total number of pos. labels on its PDB
            df.groupby("pdb")["label"].transform("sum")
            # Then subtract this "total num. of pos. in a PDB" by the rank of each pocket in a PDB, sorted by the probability
            .sub(df.groupby("pdb")["prob"].rank(method="first", ascending=False))
            # If the subtraction is positive or 0 it means that the pocket is in the topX and will be assigned 1
            >= 0
        ).astype(int)
        # If a PDB has no + labelled pocket, assign the highest prob. as positive
        for pdb, group in df.groupby("pdb"):
            if group["pred"].sum() == 0:
                df.loc[ group["prob"].idxmax(), "pred" ] = 1
    
    return df.sort_values("max_overlap", ascending=False)

## Model 5.

In [17]:
labelled_results = label_results(model5_results, site_in_pocket=0.35, pocket_in_site=None, topx=True, prob_key="prob")#.iloc[:40]#.sort_values("label", ascending=False).iloc[:40] # , prob_key=models["allo"]["prob_key"]
labelled_results.iloc[:40]

,pdb,pocket,prob,label,max_overlap,pocket_in_site,site_in_pocket,pred
53,af-p13569-f1,pocket3,1.788500e-01,1,0.888889,0.489796,0.888889,0
15,af-q14191-f1,pocket21,3.319631e-04,1,0.846154,0.846154,0.379310,0
42,af-q13191-f1,pocket1,0.000000e+00,1,0.666667,0.392157,0.666667,0
179,af-q15878-f1,pocket21,4.279893e-04,0,0.666667,0.666667,0.206897,0
9,af-q14191-f1,pocket5,9.369624e-04,0,0.600000,0.600000,0.310345,0
162,af-q15878-f1,pocket45,4.124008e-03,1,0.592593,0.592593,0.551724,0
135,af-p32418-f1,pocket4,1.805010e-05,0,0.461538,0.461538,0.300000,0
45,af-q13191-f1,pocket4,0.000000e+00,0,0.363636,0.363636,0.133333,0
113,af-p32418-f1,pocket24,5.762792e-01,1,0.350000,0.145833,0.350000,1
189,af-q15878-f1,pocket8,1.230930e-04,0,0.333333,0.333333,0.241379,0
176,af-q15878-f1,pocket58,8.401477e-04,0,0.285714,0.285714,0.137931,0
111,af-p13569-f1,pocket32,7.715649e-08,0,0.285714,0.285714,0.074074,0
142,af-p32418-f1,pocket20,3.774457e-07,0,0.250000,0.250000,0.100000,0
27,af-q14191-f1,pocket23,3.398296e-05,0,0.250000,0.250000,0.068966,0
47,af-q13191-f1,pocket5,0.000000e+00,0,0.241379,0.241379,0.233333,0
3,af-q14191-f1,pocket14,1.904638e-02,0,0.235294,0.235294,0.137931,0
16,af-q14191-f1,pocket18,3.146410e-04,0,0.214286,0.214286,0.103448,0
154,af-q15878-f1,pocket41,4.180397e-02,0,0.210526,0.210526,0.137931,0
145,af-q15878-f1,pocket1,8.688558e-01,0,0.206897,0.077922,0.206897,0
4,af-q14191-f1,pocket2,5.405733e-03,0,0.172414,0.119048,0.172414,0
2,af-q14191-f1,pocket7,9.955537e-02,0,0.166667,0.166667,0.068966,0
52,af-p13569-f1,pocket1,1.000000e+00,0,0.148148,0.011019,0.148148,1
0,af-q14191-f1,pocket1,6.842876e-01,0,0.137931,0.065574,0.137931,1
31,af-q14191-f1,pocket38,2.495681e-05,0,0.133333,0.133333,0.068966,0
71,af-p13569-f1,pocket37,7.014243e-04,0,0.125000,0.125000,0.037037,0
226,af-q15878-f1,pocket42,1.117881e-08,0,0.111111,0.111111,0.034483,0
125,af-p32418-f1,pocket1,5.194906e-04,0,0.100000,0.095238,0.100000,0
167,af-q15878-f1,pocket34,2.183400e-03,0,0.076923,0.076923,0.034483,0
204,af-q15878-f1,pocket35,8.904147e-06,0,0.071429,0.071429,0.034483,0
55,af-p13569-f1,pocket6,3.824002e-03,0,0.055556,0.055556,0.037037,0
159,af-q15878-f1,pocket77,8.229024e-03,0,0.040000,0.040000,0.034483,0
147,af-q15878-f1,pocket29,3.622323e-01,0,0.034483,0.022222,0.034483,0
161,af-q15878-f1,pocket6,5.351661e-03,0,0.000000,0.000000,0.000000,0
166,af-q15878-f1,pocket3,2.202584e-03,0,0.000000,0.000000,0.000000,0
163,af-q15878-f1,pocket50,3.308967e-03,0,0.000000,0.000000,0.000000,0
168,af-q15878-f1,pocket63,1.753778e-03,0,0.000000,0.000000,0.000000,0
158,af-q15878-f1,pocket52,9.694376e-03,0,0.000000,0.000000,0.000000,0
160,af-q15878-f1,pocket76,6.090544e-03,0,0.000000,0.000000,0.000000,0
169,af-q15878-f1,pocket16,1.182304e-03,0,0.000000,0.000000,0.000000,0
157,af-q15878-f1,pocket23,2.687240e-02,0,0.000000,0.000000,0.000000,0

In [18]:
labelled_results.sort_values("prob", ascending=False).iloc[:40]

,pdb,pocket,prob,label,max_overlap,pocket_in_site,site_in_pocket,pred
52,af-p13569-f1,pocket1,1.000000,0,0.148148,0.011019,0.148148,1
144,af-q15878-f1,pocket2,0.889049,0,0.000000,0.000000,0.000000,1
145,af-q15878-f1,pocket1,0.868856,0,0.206897,0.077922,0.206897,0
0,af-q14191-f1,pocket1,0.684288,0,0.137931,0.065574,0.137931,1
113,af-p32418-f1,pocket24,0.576279,1,0.350000,0.145833,0.350000,1
114,af-p32418-f1,pocket31,0.575299,0,0.000000,0.000000,0.000000,0
146,af-q15878-f1,pocket85,0.547140,0,0.000000,0.000000,0.000000,0
147,af-q15878-f1,pocket29,0.362232,0,0.034483,0.022222,0.034483,0
115,af-p32418-f1,pocket25,0.334627,0,0.000000,0.000000,0.000000,0
1,af-q14191-f1,pocket11,0.230360,0,0.000000,0.000000,0.000000,0
116,af-p32418-f1,pocket6,0.217418,0,0.000000,0.000000,0.000000,0
148,af-q15878-f1,pocket78,0.209885,0,0.000000,0.000000,0.000000,0
149,af-q15878-f1,pocket83,0.201181,0,0.000000,0.000000,0.000000,0
53,af-p13569-f1,pocket3,0.178850,1,0.888889,0.489796,0.888889,0
2,af-q14191-f1,pocket7,0.099555,0,0.166667,0.166667,0.068966,0
150,af-q15878-f1,pocket4,0.088921,0,0.000000,0.000000,0.000000,0
151,af-q15878-f1,pocket31,0.079418,0,0.000000,0.000000,0.000000,0
152,af-q15878-f1,pocket59,0.075658,0,0.000000,0.000000,0.000000,0
117,af-p32418-f1,pocket9,0.060986,0,0.000000,0.000000,0.000000,0
153,af-q15878-f1,pocket26,0.047110,0,0.000000,0.000000,0.000000,0
154,af-q15878-f1,pocket41,0.041804,0,0.210526,0.210526,0.137931,0
155,af-q15878-f1,pocket48,0.040303,0,0.000000,0.000000,0.000000,0
156,af-q15878-f1,pocket84,0.031085,0,0.000000,0.000000,0.000000,0
157,af-q15878-f1,pocket23,0.026872,0,0.000000,0.000000,0.000000,0
54,af-p13569-f1,pocket17,0.023045,0,0.000000,0.000000,0.000000,0
3,af-q14191-f1,pocket14,0.019046,0,0.235294,0.235294,0.137931,0
118,af-p32418-f1,pocket29,0.013229,0,0.000000,0.000000,0.000000,0
119,af-p32418-f1,pocket27,0.010914,0,0.000000,0.000000,0.000000,0
158,af-q15878-f1,pocket52,0.009694,0,0.000000,0.000000,0.000000,0
159,af-q15878-f1,pocket77,0.008229,0,0.040000,0.040000,0.034483,0
120,af-p32418-f1,pocket2,0.007515,0,0.000000,0.000000,0.000000,0
160,af-q15878-f1,pocket76,0.006091,0,0.000000,0.000000,0.000000,0
4,af-q14191-f1,pocket2,0.005406,0,0.172414,0.119048,0.172414,0
161,af-q15878-f1,pocket6,0.005352,0,0.000000,0.000000,0.000000,0
162,af-q15878-f1,pocket45,0.004124,1,0.592593,0.592593,0.551724,0
55,af-p13569-f1,pocket6,0.003824,0,0.055556,0.055556,0.037037,0
56,af-p13569-f1,pocket8,0.003657,0,0.000000,0.000000,0.000000,0
57,af-p13569-f1,pocket42,0.003597,0,0.000000,0.000000,0.000000,0
163,af-q15878-f1,pocket50,0.003309,0,0.000000,0.000000,0.000000,0
5,af-q14191-f1,pocket37,0.003184,0,0.000000,0.000000,0.000000,0

In [19]:
labelled_results.sort_values(["pred", "prob"], ascending=False).iloc[:40]

,pdb,pocket,prob,label,max_overlap,pocket_in_site,site_in_pocket,pred
52,af-p13569-f1,pocket1,1.000000,0,0.148148,0.011019,0.148148,1
144,af-q15878-f1,pocket2,0.889049,0,0.000000,0.000000,0.000000,1
0,af-q14191-f1,pocket1,0.684288,0,0.137931,0.065574,0.137931,1
113,af-p32418-f1,pocket24,0.576279,1,0.350000,0.145833,0.350000,1
40,af-q13191-f1,pocket10,0.000005,0,0.000000,0.000000,0.000000,1
145,af-q15878-f1,pocket1,0.868856,0,0.206897,0.077922,0.206897,0
114,af-p32418-f1,pocket31,0.575299,0,0.000000,0.000000,0.000000,0
146,af-q15878-f1,pocket85,0.547140,0,0.000000,0.000000,0.000000,0
147,af-q15878-f1,pocket29,0.362232,0,0.034483,0.022222,0.034483,0
115,af-p32418-f1,pocket25,0.334627,0,0.000000,0.000000,0.000000,0
1,af-q14191-f1,pocket11,0.230360,0,0.000000,0.000000,0.000000,0
116,af-p32418-f1,pocket6,0.217418,0,0.000000,0.000000,0.000000,0
148,af-q15878-f1,pocket78,0.209885,0,0.000000,0.000000,0.000000,0
149,af-q15878-f1,pocket83,0.201181,0,0.000000,0.000000,0.000000,0
53,af-p13569-f1,pocket3,0.178850,1,0.888889,0.489796,0.888889,0
2,af-q14191-f1,pocket7,0.099555,0,0.166667,0.166667,0.068966,0
150,af-q15878-f1,pocket4,0.088921,0,0.000000,0.000000,0.000000,0
151,af-q15878-f1,pocket31,0.079418,0,0.000000,0.000000,0.000000,0
152,af-q15878-f1,pocket59,0.075658,0,0.000000,0.000000,0.000000,0
117,af-p32418-f1,pocket9,0.060986,0,0.000000,0.000000,0.000000,0
153,af-q15878-f1,pocket26,0.047110,0,0.000000,0.000000,0.000000,0
154,af-q15878-f1,pocket41,0.041804,0,0.210526,0.210526,0.137931,0
155,af-q15878-f1,pocket48,0.040303,0,0.000000,0.000000,0.000000,0
156,af-q15878-f1,pocket84,0.031085,0,0.000000,0.000000,0.000000,0
157,af-q15878-f1,pocket23,0.026872,0,0.000000,0.000000,0.000000,0
54,af-p13569-f1,pocket17,0.023045,0,0.000000,0.000000,0.000000,0
3,af-q14191-f1,pocket14,0.019046,0,0.235294,0.235294,0.137931,0
118,af-p32418-f1,pocket29,0.013229,0,0.000000,0.000000,0.000000,0
119,af-p32418-f1,pocket27,0.010914,0,0.000000,0.000000,0.000000,0
158,af-q15878-f1,pocket52,0.009694,0,0.000000,0.000000,0.000000,0
159,af-q15878-f1,pocket77,0.008229,0,0.040000,0.040000,0.034483,0
120,af-p32418-f1,pocket2,0.007515,0,0.000000,0.000000,0.000000,0
160,af-q15878-f1,pocket76,0.006091,0,0.000000,0.000000,0.000000,0
4,af-q14191-f1,pocket2,0.005406,0,0.172414,0.119048,0.172414,0
161,af-q15878-f1,pocket6,0.005352,0,0.000000,0.000000,0.000000,0
162,af-q15878-f1,pocket45,0.004124,1,0.592593,0.592593,0.551724,0
55,af-p13569-f1,pocket6,0.003824,0,0.055556,0.055556,0.037037,0
56,af-p13569-f1,pocket8,0.003657,0,0.000000,0.000000,0.000000,0
57,af-p13569-f1,pocket42,0.003597,0,0.000000,0.000000,0.000000,0
163,af-q15878-f1,pocket50,0.003309,0,0.000000,0.000000,0.000000,0

In [20]:
models["model5"]["labelling"] = {"site_in_pocket": 0.35, "pocket_in_site": None}

In [36]:
pd.to_pickle(models, "models_lenient_labelling.pkl")

# Labelling - old

## AllositePro

label_results(allositepro_results, site_in_pocket=0.3, pocket_in_site=None)#, prob_key=models["allositepro"]["prob_key"])

models["allositepro"]["labelling"] = {"site_in_pocket": 0.3, "pocket_in_site": None}

## PASSer

label_results(passer_results["ensemble"], site_in_pocket=0.35, pocket_in_site=None).iloc[:40] # prob_key=models["passer_ensemble"]["prob_key"]

models["passer_ensemble"]["labelling"] = {"site_in_pocket": 0.35, "pocket_in_site": None}

label_results(passer_results["automl"], site_in_pocket=0.35, pocket_in_site=None).iloc[:40] # , prob_key=models["passer_automl"]["prob_key"]

models["passer_automl"]["labelling"] = {"site_in_pocket": 0.35, "pocket_in_site": None}

models["passer_rank"]["labelling"] = {"site_in_pocket": 0.35, "pocket_in_site": None}

## DeepAllo

label_results(deepallo_results, site_in_pocket=0.35, pocket_in_site=None, special_7sns_sc=True).iloc[:40] # , prob_key=models["deepallo"]["prob_key"]

models["deepallo"]["labelling"] = {"site_in_pocket": 0.35, "pocket_in_site": None, "special_7sns_sc": True}

## STINGAllo

label_results(stingallo_results, site_in_pocket=None, pocket_in_site=1) # _topx

models["stingallo"]["labelling"] = {"site_in_pocket": None, "pocket_in_site": 1}

## AlloFusion

result = label_results(allofusion_results, site_in_pocket=None, pocket_in_site=1)
result

mask = ((result.pred == 1) & (result.label == 1))
mask

pd.concat((
    result.loc[result[mask].drop_duplicates("pdb").index],
    result[~mask]
))

models["allofusion"]["labelling"] = {"site_in_pocket": None, "pocket_in_site": 1}

## AllosES

label_results(alloses_results, site_in_pocket=0.35, pocket_in_site=None, special_7sns_sc=True).iloc[:40] # , prob_key=models["alloses"]["prob_key"]

label_results(alloses_results, site_in_pocket=0.35, pocket_in_site=None, special_7sns_sc=True).sort_values("label", ascending=False).iloc[:40] # , prob_key=models["alloses"]["prob_key"]

models["alloses"]["labelling"] = {"site_in_pocket": 0.35, "pocket_in_site": None, "special_7sns_sc": True}

## MEF-AlloSite

label_results(mefallosite_results, site_in_pocket=0.35, pocket_in_site=None).iloc[:40] # , prob_key=models["mefallosite"]["prob_key"]

models["mefallosite"]["labelling"] = {"site_in_pocket": 0.35, "pocket_in_site": None}

## ALLO

label_results(allo_results, site_in_pocket=0.3, pocket_in_site=None).iloc[:40] # , prob_key=models["allo"]["prob_key"]

label_results(allo_results, site_in_pocket=0.5, pocket_in_site=None).sort_values(["label", "pred"], ascending=False).iloc[:40] # , prob_key=models["allo"]["prob_key"]

models["allo"]["labelling"] = {"site_in_pocket": 0.5, "pocket_in_site": None}

# Scoring

## Original

models_preds = {}

for model, modeld in models.items():
    results = modeld["results"]
    if modeld["labelling"] is not None:
        labelled_results = label_results(results, **modeld["labelling"], prob_key=modeld["prob_key"])
    else:
        labelled_results = pd.DataFrame((
            {
                "pdb": pdb,
                "pocket": pocket,
                **pocketd
            }
            for pdb, pockets in results.items()
            for pocket, pocketd in pockets.items()
        ))

    preds = {}
    for pdb in news_sites:
        # if pdb == "4jqi": continue #######################################################################################
        pdbpreds = labelled_results.query(f"pdb == '{pdb}'")
        total = len(pdbpreds)
        if total > 0:
            # Top1 pred for our model
            if model == "model5":
                # pdbpreds.loc[:, "pred"] = pdbpreds[["prob"]].apply(lambda x: (x == x.max()).astype(int)).values
                pass
            # elif model == "allofusion":
            #     pdbpreds = pdbpreds.drop(
            #         pdbpreds.loc[lambda x: (x.pred == 1) & (x.label == 1)]
            #         .index[1:]
            #     )

            # # if pdb is 7sns, if there's more than 1 label 1, keep only the pred one if exists, or just 1 in general
            # if pdb == "7sns" and model not in ["allofusion", "stingallo"]:
            #     pdbpreds = pdbpreds.drop(
            #         pdbpreds.loc[pdbpreds.label == 1]
            #         .sort_values("pred", ascending=False)
            #         .index[1:]
            #     )

            tp = len( pdbpreds.loc[lambda x: (x["pred"] == 1) & (x["label"] == 1)] )
            fp = len( pdbpreds.loc[lambda x: (x["pred"] == 1) & (x["label"] == 0)] )
            fn = len( pdbpreds.loc[lambda x: (x["pred"] == 0) & (x["label"] == 1)] )
            if tp + fn == 0:
                fn = 1 # There's at least 1 allo. pocket per PDB
        else:
            tp, fp = 0, 0
            fn = 1 # There's at least 1 allo. pocket per PDB

        if total == 0 or not modeld["all_pockets_in_output"]:
            preds[pdb] = {
                "tp": tp,
                "fn": fn,
                "fp": fp
            }
        else:
            preds[pdb] = {
                "total": total,
                "tp": tp,
                "fn": fn,
                "fp": fp
            }

    models_preds[model] = preds

models_preds

from sklearn.metrics import matthews_corrcoef, f1_score, confusion_matrix

models_preds

models_metrics = {}

for model, preds in models_preds.items():
    df = pd.DataFrame(preds).T
    
    if models[model]["all_pockets_in_output"]:
        y_true = [1] * df["tp"].sum() + [1] * df["fn"].sum() + [0] * df["fp"].sum() + [0] * (df["total"].sum() - df[["tp", "fn", "fp"]].sum().sum())
        y_pred = [1] * df["tp"].sum() + [0] * df["fn"].sum() + [1] * df["fp"].sum() + [0] * (df["total"].sum() - df[["tp", "fn", "fp"]].sum().sum())

        models_metrics[model] = {
            "model": model,
            "tp": df["tp"].sum(),
            "fn": df["fn"].sum(),
            "fp": df["fp"].sum(),
            "mcc": matthews_corrcoef(y_true, y_pred),
            "macro-f1": f1_score(y_true, y_pred, average="macro"),
            "confmat": pd.DataFrame(confusion_matrix(y_true, y_pred))
        }
        
    else:
        models_metrics[model] = {
            "model": model,
            "tp": df["tp"].sum(),
            "fn": df["fn"].sum(),
            "fp": df["fp"].sum(),
        }

models_metrics = pd.DataFrame(models_metrics).T.sort_values(["tp", "mcc"], ascending=False)
models_metrics

models_metrics.infer_objects().to_csv("models_metrics.csv", index=False, sep="\t", decimal=",")

## TopX

In [32]:
models_preds = {}

for model, modeld in models.items():
    results = modeld["results"]
    if modeld["labelling"] is not None:
        labelled_results = label_results(results, **modeld["labelling"], prob_key=modeld["prob_key"], topx=True)
    else:
        labelled_results = pd.DataFrame((
            {
                "pdb": pdb,
                "pocket": pocket,
                **pocketd
            }
            for pdb, pockets in results.items()
            for pocket, pocketd in pockets.items()
        ))

    preds = {}
    for pdb in news_sites:
        # if pdb == "4jqi": continue #######################################################################################
        pdbpreds = labelled_results.query(f"pdb == '{pdb}'")
        total = len(pdbpreds)
        if total > 0:
            # # Top1 pred for our model
            # if model == "model5":
            #     pdbpreds.loc[:, "pred"] = pdbpreds[["prob"]].apply(lambda x: (x == x.max()).astype(int)).values
            # elif model == "allofusion":
            #     pdbpreds = pdbpreds.drop(
            #         pdbpreds.loc[lambda x: (x.pred == 1) & (x.label == 1)]
            #         .index[1:]
            #     )

            # # if pdb is 7sns, if there's more than 1 label 1, keep only the pred one if exists, or just 1 in general
            # if pdb == "7sns":
            #     pdbpreds = pdbpreds.drop(
            #         pdbpreds.loc[pdbpreds.label == 1]
            #         .sort_values("pred", ascending=False)
            #         .index[1:]
            #     )
                
            tp = len( pdbpreds.loc[lambda x: (x["pred"] == 1) & (x["label"] == 1)] )
            fp = len( pdbpreds.loc[lambda x: (x["pred"] == 1) & (x["label"] == 0)] )
            fn = len( pdbpreds.loc[lambda x: (x["pred"] == 0) & (x["label"] == 1)] )
            if tp + fn == 0:
                fn = 1 # There's at least 1 allo. pocket per PDB
        else:
            tp, fp = 0, 0
            fn = 1 # There's at least 1 allo. pocket per PDB

        if total == 0 or not modeld["all_pockets_in_output"]:
            preds[pdb] = {
                "tp": tp,
                "fn": fn,
                "fp": fp
            }
        else:
            preds[pdb] = {
                "total": total,
                "tp": tp,
                "fn": fn,
                "fp": fp
            }

    models_preds[model] = preds

models_preds

{'model5': {'af-q14191-f1': {'total': 40, 'tp': 0, 'fn': 1, 'fp': 1},
  'af-q13191-f1': {'total': 12, 'tp': 0, 'fn': 1, 'fp': 1},
  'af-p13569-f1': {'total': 61, 'tp': 0, 'fn': 1, 'fp': 1},
  'af-p32418-f1': {'total': 31, 'tp': 1, 'fn': 0, 'fp': 0},
  'af-q15878-f1': {'total': 85, 'tp': 0, 'fn': 1, 'fp': 1}}}

In [33]:
from sklearn.metrics import matthews_corrcoef, f1_score, confusion_matrix

In [34]:
models_metrics = {}

for model, preds in models_preds.items():
    df = pd.DataFrame(preds).T
    
    if models[model]["all_pockets_in_output"]:
        y_true = [1] * df["tp"].sum() + [1] * df["fn"].sum() + [0] * df["fp"].sum() + [0] * (df["total"].sum() - df[["tp", "fn", "fp"]].sum().sum())
        y_pred = [1] * df["tp"].sum() + [0] * df["fn"].sum() + [1] * df["fp"].sum() + [0] * (df["total"].sum() - df[["tp", "fn", "fp"]].sum().sum())

        models_metrics[model] = {
            "model": model,
            "tp": df["tp"].sum(),
            "fn": df["fn"].sum(),
            "fp": df["fp"].sum(),
            "mcc": matthews_corrcoef(y_true, y_pred),
            "macro-f1": f1_score(y_true, y_pred, average="macro"),
            "confmat": pd.DataFrame(confusion_matrix(y_true, y_pred))
        }
        
    else:
        models_metrics[model] = {
            "model": model,
            "tp": df["tp"].sum(),
            "fn": df["fn"].sum(),
            "fp": df["fp"].sum(),
        }

models_metrics = pd.DataFrame(models_metrics).T.sort_values(["tp", "mcc"], ascending=False)
models_metrics

         model tp fn fp       mcc  macro-f1                        confmat
model5  model5  1  4  4  0.182143  0.591071       0  1
0  220  4
1    4  1

In [35]:
models_metrics.infer_objects().to_csv("models_metrics_topx.csv", index=False, sep="\t", decimal=",")

# Old

In [63]:
models_preds = {}

for model, modeld in models.items():
    results = modeld["results"]
    if "model5" not in model:
        labelled_results = label_results_topx(results, **modeld["labelling"], prob_key=modeld["prob_key"])
    else:
        labelled_results = label_our_results_topx(results, **modeld["labelling"])

    preds = {}
    for pdb in news:
        pdbpreds = labelled_results.query(f"pdb == '{pdb}'")
        total = len(pdbpreds)
        if total > 0:
            if model == "allofusion":
                pdbpreds = pdbpreds.drop(
                    pdbpreds.loc[lambda x: (x.pred == 1) & (x.label == 1)]
                    .index[1:]
                )
            tp = len( pdbpreds.loc[lambda x: (x["pred"] == 1) & (x["label"] == 1)] )
            fp = len( pdbpreds.loc[lambda x: (x["pred"] == 1) & (x["label"] == 0)] )
            fn = len( pdbpreds.loc[lambda x: (x["pred"] == 0) & (x["label"] == 1)] )
            if tp + fn == 0:
                fn = 1 # There's at least 1 allo. pocket per PDB
        else:
            tp, fp = 0, 0
            fn = 1 # There's at least 1 allo. pocket per PDB

        if total == 0 or not modeld["all_pockets_in_output"]:
            preds[pdb] = {
                "tp": tp,
                "fn": fn,
                "fp": fp
            }
        else:
            preds[pdb] = {
                "total": total,
                "tp": tp,
                "fn": fn,
                "fp": fp
            }

    models_preds[model] = preds

models_preds

{'model5': {'8sgj': {'total': 28, 'tp': 1, 'fn': 0, 'fp': 0},
  'AF-A0A1D8PQM9-F1': {'total': 30, 'tp': 1, 'fn': 0, 'fp': 0},
  '7l6r': {'total': 14, 'tp': 1, 'fn': 0, 'fp': 0},
  '8vw5': {'total': 13, 'tp': 1, 'fn': 0, 'fp': 0},
  '6yhr': {'total': 20, 'tp': 1, 'fn': 0, 'fp': 0},
  '7xlq': {'total': 69, 'tp': 0, 'fn': 1, 'fp': 1},
  '5b0u': {'total': 2, 'tp': 0, 'fn': 1, 'fp': 1},
  '5uak': {'total': 75, 'tp': 1, 'fn': 0, 'fp': 0},
  '4jqi': {'total': 19, 'tp': 0, 'fn': 1, 'fp': 1}},
 'allositepro': {'8sgj': {'tp': 0, 'fn': 1, 'fp': 0},
  'AF-A0A1D8PQM9-F1': {'tp': 0, 'fn': 1, 'fp': 0},
  '7l6r': {'tp': 1, 'fn': 0, 'fp': 0},
  '8vw5': {'tp': 0, 'fn': 1, 'fp': 0},
  '6yhr': {'tp': 0, 'fn': 1, 'fp': 0},
  '7xlq': {'tp': 0, 'fn': 1, 'fp': 0},
  '5b0u': {'tp': 0, 'fn': 1, 'fp': 1},
  '5uak': {'tp': 0, 'fn': 1, 'fp': 0},
  '4jqi': {'tp': 0, 'fn': 1, 'fp': 0}},
 'stingallo': {'8sgj': {'tp': 0, 'fn': 1, 'fp': 0},
  'AF-A0A1D8PQM9-F1': {'tp': 0, 'fn': 1, 'fp': 0},
  '7l6r': {'tp': 0, 'fn': 1, 'fp': 0},
  '8vw5': {'tp': 0, 'fn': 1, 'fp': 0},
  '6yhr': {'tp': 0, 'fn': 1, 'fp': 1},
  '7xlq': {'tp': 0, 'fn': 1, 'fp': 0},
  '5b0u': {'tp': 0, 'fn': 1, 'fp': 0},
  '5uak': {'tp': 0, 'fn': 1, 'fp': 0},
  '4jqi': {'tp': 0, 'fn': 1, 'fp': 0}},
 'allofusion': {'8sgj': {'tp': 0, 'fn': 1, 'fp': 2},
  'AF-A0A1D8PQM9-F1': {'tp': 0, 'fn': 1, 'fp': 1},
  '7l6r': {'tp': 0, 'fn': 1, 'fp': 4},
  '8vw5': {'tp': 0, 'fn': 1, 'fp': 8},
  '6yhr': {'tp': 1, 'fn': 0, 'fp': 10},
  '7xlq': {'tp': 0, 'fn': 1, 'fp': 2},
  '5b0u': {'tp': 1, 'fn': 0, 'fp': 7},
  '5uak': {'tp': 1, 'fn': 0, 'fp': 16},
  '4jqi': {'tp': 0, 'fn': 1, 'fp': 5}},
 'passer_ensemble': {'8sgj': {'total': 54, 'tp': 0, 'fn': 1, 'fp': 1},
  'AF-A0A1D8PQM9-F1': {'total': 54, 'tp': 0, 'fn': 1, 'fp': 1},
  '7l6r': {'total': 23, 'tp': 1, 'fn': 0, 'fp': 0},
  '8vw5': {'total': 22, 'tp': 0, 'fn': 1, 'fp': 1},
  '6yhr': {'total': 44, 'tp': 1, 'fn': 0, 'fp': 0},
  '7xlq': {'total': 115, 'tp': 0, 'fn': 1, 'fp': 1},
  '5b0u': {'total': 7, 'tp': 0, 'fn': 1, 'fp': 1},
  '5uak': {'total': 139, 'tp': 0, 'fn': 1, 'fp': 1},
  '4jqi': {'total': 33, 'tp': 0, 'fn': 1, 'fp': 1}},
 'passer_automl': {'8sgj': {'total': 54, 'tp': 1, 'fn': 0, 'fp': 0},
  'AF-A0A1D8PQM9-F1': {'total': 54, 'tp': 0, 'fn': 1, 'fp': 1},
  '7l6r': {'total': 23, 'tp': 1, 'fn': 0, 'fp': 0},
  '8vw5': {'total': 22, 'tp': 0, 'fn': 1, 'fp': 1},
  '6yhr': {'total': 44, 'tp': 1, 'fn': 0, 'fp': 0},
  '7xlq': {'total': 115, 'tp': 0, 'fn': 1, 'fp': 1},
  '5b0u': {'total': 7, 'tp': 0, 'fn': 1, 'fp': 1},
  '5uak': {'total': 139, 'tp': 0, 'fn': 1, 'fp': 1},
  '4jqi': {'total': 33, 'tp': 0, 'fn': 1, 'fp': 1}},
 'passer_rank': {'8sgj': {'total': 54, 'tp': 1, 'fn': 0, 'fp': 0},
  'AF-A0A1D8PQM9-F1': {'total': 54, 'tp': 0, 'fn': 1, 'fp': 1},
  '7l6r': {'total': 23, 'tp': 1, 'fn': 0, 'fp': 0},
  '8vw5': {'total': 22, 'tp': 0, 'fn': 1, 'fp': 1},
  '6yhr': {'total': 44, 'tp': 0, 'fn': 1, 'fp': 1},
  '7xlq': {'total': 115, 'tp': 0, 'fn': 1, 'fp': 1},
  '5b0u': {'total': 7, 'tp': 0, 'fn': 1, 'fp': 1},
  '5uak': {'total': 139, 'tp': 0, 'fn': 1, 'fp': 1},
  '4jqi': {'total': 33, 'tp': 0, 'fn': 1, 'fp': 1}},
 'deepallo': {'8sgj': {'total': 54, 'tp': 1, 'fn': 0, 'fp': 0},
  'AF-A0A1D8PQM9-F1': {'total': 54, 'tp': 0, 'fn': 1, 'fp': 1},
  '7l6r': {'total': 24, 'tp': 0, 'fn': 1, 'fp': 1},
  '8vw5': {'total': 22, 'tp': 1, 'fn': 0, 'fp': 0},
  '6yhr': {'total': 40, 'tp': 0, 'fn': 1, 'fp': 1},
  '7xlq': {'total': 115, 'tp': 0, 'fn': 1, 'fp': 1},
  '5b0u': {'total': 7, 'tp': 0, 'fn': 1, 'fp': 1},
  '5uak': {'total': 139, 'tp': 0, 'fn': 1, 'fp': 1},
  '4jqi': {'total': 27, 'tp': 0, 'fn': 1, 'fp': 1}},
 'alloses': {'8sgj': {'total': 54, 'tp': 1, 'fn': 0, 'fp': 0},
  'AF-A0A1D8PQM9-F1': {'total': 54, 'tp': 0, 'fn': 1, 'fp': 1},
  '7l6r': {'total': 23, 'tp': 1, 'fn': 0, 'fp': 0},
  '8vw5': {'total': 22, 'tp': 0, 'fn': 1, 'fp': 1},
  '6yhr': {'total': 44, 'tp': 1, 'fn': 0, 'fp': 0},
  '7xlq': {'total': 115, 'tp': 0, 'fn': 1, 'fp': 1},
  '5b0u': {'total': 7, 'tp': 0, 'fn': 1, 'fp': 1},
  '5uak': {'total': 139, 'tp': 0, 'fn': 1, 'fp': 1},
  '4jqi': {'total': 33, 'tp': 0, 'fn': 1, 'fp': 1}},
 'mefallosite': {'8sgj': {'total': 47, 'tp': 1, 'fn': 0, 'fp': 0},
  'AF-A0A1D8PQM9-F1': {'total': 54, 'tp': 0, 'fn': 1, 'fp': 1},
  '7l6r': {'total': 19, 'tp': 1, 'fn': 0, 'fp': 0},
  '8vw5': {'total': 17, 'tp': 1, 'fn': 0, 'fp': 0},
  '6yhr': {'total': 33, 'tp': 1, 'fn': 0, 'fp': 0},
  '7xlq': {'total': 84, 'tp': 0, 'fn': 1, 'fp': 1},
  '5b0u': {'total': 4, 'tp': 0, 'fn': 1, 'fp': 1},
  '5uak': {'total': 139, 'tp': 0, 'fn': 1, 'fp': 1},
  '4jqi': {'total': 27, 'tp': 0, 'fn': 1, 'fp': 1}},
 'allo': {'8sgj': {'total': 21, 'tp': 1, 'fn': 0, 'fp': 0},
  'AF-A0A1D8PQM9-F1': {'total': 34, 'tp': 0, 'fn': 1, 'fp': 1},
  '7l6r': {'total': 14, 'tp': 0, 'fn': 1, 'fp': 1},
  '8vw5': {'total': 8, 'tp': 1, 'fn': 0, 'fp': 0},
  '6yhr': {'total': 15, 'tp': 1, 'fn': 0, 'fp': 0},
  '7xlq': {'total': 58, 'tp': 0, 'fn': 1, 'fp': 1},
  '5b0u': {'total': 2, 'tp': 0, 'fn': 1, 'fp': 1},
  '5uak': {'total': 53, 'tp': 1, 'fn': 0, 'fp': 0},
  '4jqi': {'total': 18, 'tp': 0, 'fn': 1, 'fp': 1}}}

In [64]:
from sklearn.metrics import matthews_corrcoef, f1_score, confusion_matrix

In [65]:
models_metrics = {}

for model, preds in models_preds.items():
    df = pd.DataFrame(preds).T
    
    if models[model]["all_pockets_in_output"]:
        y_true = [1] * df["tp"].sum() + [1] * df["fn"].sum() + [0] * df["fp"].sum() + [0] * (df["total"].sum() - df[["tp", "fn", "fp"]].sum().sum())
        y_pred = [1] * df["tp"].sum() + [0] * df["fn"].sum() + [1] * df["fp"].sum() + [0] * (df["total"].sum() - df[["tp", "fn", "fp"]].sum().sum())

        models_metrics[model] = {
            "model": model,
            "tp": df["tp"].sum(),
            "fn": df["fn"].sum(),
            "fp": df["fp"].sum(),
            "mcc": matthews_corrcoef(y_true, y_pred),
            "macro-f1": f1_score(y_true, y_pred, average="macro"),
            "confmat": pd.DataFrame(confusion_matrix(y_true, y_pred))
        }
        
    else:
        models_metrics[model] = {
            "model": model,
            "tp": df["tp"].sum(),
            "fn": df["fn"].sum(),
            "fp": df["fp"].sum(),
        }

models_metrics = pd.DataFrame(models_metrics).T.sort_values(["tp", "mcc"], ascending=False)
models_metrics

,model,tp,fn,fp,mcc,macro-f1,confmat
model5,model5,6,3,3,0.655172,0.827586,0 1 0 258 3 1 3 6
mefallosite,mefallosite,4,5,5,0.432396,0.716198,0 1 0 410 5 1 5 4
allo,allo,4,5,5,0.42108,0.71054,0 1 0 209 5 1 5 4
passer_automl,passer_automl,3,6,6,0.320885,0.660443,0 1 0 476 6 1 6 3
alloses,alloses,3,6,6,0.320885,0.660443,0 1 0 476 6 1 6 3
allofusion,allofusion,3,6,55,NaN,NaN,NaN
passer_ensemble,passer_ensemble,2,7,7,0.207699,0.60385,0 1 0 475 7 1 7 2
passer_rank,passer_rank,2,7,7,0.207699,0.60385,0 1 0 475 7 1 7 2
deepallo,deepallo,2,7,7,0.207423,0.603712,0 1 0 466 7 1 7 2
allositepro,allositepro,1,8,1,NaN,NaN,NaN
stingallo,stingallo,0,9,1,NaN,NaN,NaN

In [66]:
models_metrics.infer_objects().to_csv("models_metrics_top1_apos_lenient_labelling.csv", index=False, sep=";", decimal=",")

## Top1

models_preds_top1 = {}

for model, modeld in models.items():
    results = modeld["results"]
    if "model5" not in model:
        labelled_results = label_results(results, **modeld["labelling"], prob_key=modeld["prob_key"])
    else:
        labelled_results = label_our_results(results, **modeld["labelling"])

    preds = {}
    for pdb in news:
        pdbpreds = pd.DataFrame(labelled_results.query(f"pdb == '{pdb}'"))
        total = len(pdbpreds)
        if total > 0:
            if modeld["prob_key"] is not None:
                pdbpreds["pred"] = pdbpreds[["prob"]].apply(lambda x: (x == x.max()).astype(int))
            tp = len( pdbpreds.loc[lambda x: (x["pred"] == 1) & (x["label"] == 1)] )
            fp = len( pdbpreds.loc[lambda x: (x["pred"] == 1) & (x["label"] == 0)] )
            fn = len( pdbpreds.loc[lambda x: (x["pred"] == 0) & (x["label"] == 1)] )
            if tp + fn == 0:
                fn = 1 # There's at least 1 allo. pocket per PDB
        else:
            tp, fp = 0, 0
            fn = 1 # There's at least 1 allo. pocket per PDB

        if total == 0 or not modeld["all_pockets_in_output"]:
            preds[pdb] = {
                "tp": tp,
                "fn": fn,
                "fp": fp
            }
        else:
            preds[pdb] = {
                "total": total,
                "tp": tp,
                "fn": fn,
                "fp": fp
            }

    models_preds_top1[model] = preds

models_preds_top1

{'8jp0': {'8sgj': ['A']},
 '8uk6': {'AF-A0A1D8PQM9-F1': ['A']},
 '8f4s': {'7l6r': ['A']},
 '7gqu': {'6yhr': ['A']},
 '7yg5': {'7xlq': ['A']},
 '8aq6': {'5b0u': ['A']},
 '8qni': {'2ldr': ['A']},
 '8v81': {'5uak': ['A']},
 '9dnm': {'4jqi': ['A']}}

models_metrics_top1 = {}

for model, preds in models_preds_top1.items():
    df = pd.DataFrame(preds).T
    
    if models[model]["all_pockets_in_output"]:
        y_true = [1] * df["tp"].sum() + [1] * df["fn"].sum() + [0] * df["fp"].sum() + [0] * (df["total"].sum() - df[["tp", "fn", "fp"]].sum().sum())
        y_pred = [1] * df["tp"].sum() + [0] * df["fn"].sum() + [1] * df["fp"].sum() + [0] * (df["total"].sum() - df[["tp", "fn", "fp"]].sum().sum())

        models_metrics_top1[model] = {
            "model": model,
            "tp": df["tp"].sum(),
            "fn": df["fn"].sum(),
            "fp": df["fp"].sum(),
            "mcc": matthews_corrcoef(y_true, y_pred),
            "macro-f1": f1_score(y_true, y_pred, average="macro"),
            "confmat": pd.DataFrame(confusion_matrix(y_true, y_pred))
        }
        
    else:
        models_metrics_top1[model] = {
            "model": model,
            "tp": df["tp"].sum(),
            "fn": df["fn"].sum(),
            "fp": df["fp"].sum(),
        }

models_metrics_top1 = pd.DataFrame(models_metrics_top1).T.sort_values(["tp", "mcc"], ascending=False)
models_metrics_top1

models_metrics_top1.to_csv("models_metrics_top1_apos_lenient_labelling.csv", index=False)